using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Media;
using TrMarketplaceHubDesktop.Catalog;

namespace TrMarketplaceHubDesktop;

public static class BulkProductsPanel
{
    public static FrameworkElement Create(string? directory = null, Action<string>? navigate = null)
    {
        var catalog = new CatalogStore(directory); var operations = new BulkProductOperations(catalog, new ChannelProductsStore(directory)); var root = new DockPanel { Margin = new Thickness(12) }; var top = new StackPanel(); DockPanel.SetDock(top, Dock.Top); root.Children.Add(top);
        top.Children.Add(Text("Toplu ürün işlemleri", TextRole.SectionTitle)); top.Children.Add(Text("Seçili veya arama sonucundaki ürünlerde yerel değişiklikleri önce önizleyin. Preview sonrası ürün sürümü değişirse tüm işlem atomik olarak iptal edilir."));
        var controls = new WrapPanel(); top.Children.Add(controls); var search = new TextBox { Width = 240, ToolTip = "SKU, barkod, ad, marka veya kategori ara" }; controls.Children.Add(search); var operation = new ComboBox { Width = 170, ItemsSource = Enum.GetValues<BulkProductOperationKind>(), SelectedIndex = 0 }; controls.Children.Add(operation); var value = new TextBox { Width = 200, ToolTip = "Kategori, marka, ad veya açıklama için yeni değer" }; controls.Children.Add(value); var refresh = Button("Ürünleri getir"); controls.Children.Add(refresh);
        var channel = new TextBox { Width = 100, Text = "etsy", ToolTip = "Kanal (kanal planı işleminde)" }; var shop = new TextBox { Width = 120, Text = "default", ToolTip = "Mağaza" }; var listing = new TextBox { Width = 120, ToolTip = "Listing ID" }; var targetCategory = new TextBox { Width = 160, ToolTip = "Hedef kategori" }; controls.Children.Add(channel); controls.Children.Add(shop); controls.Children.Add(listing); controls.Children.Add(targetCategory);
        var products = new DataGrid { AutoGenerateColumns = false, IsReadOnly = true, SelectionMode = DataGridSelectionMode.Extended, Height = 250, EnableRowVirtualization = true }; VirtualizingPanel.SetIsVirtualizing(products, true); VirtualizingPanel.SetVirtualizationMode(products, VirtualizationMode.Recycling); foreach (var column in new[] { ("SKU", "Sku", 140d), ("Ürün", "Name", 240d), ("Marka", "Brand", 130d), ("Kategori", "Category", 150d), ("Aktif", "StatusLabel", 90d), ("Stok", "Stock", 70d), ("Sürüm", "UpdatedUtc", 160d) }) products.Columns.Add(new DataGridTextColumn { Header = column.Item1, Binding = new Binding(column.Item2), Width = column.Item3 });
        var preview = new DataGrid { AutoGenerateColumns = false, IsReadOnly = true, Height = 260, EnableRowVirtualization = true }; VirtualizingPanel.SetIsVirtualizing(preview, true); foreach (var column in new[] { ("SKU", "Sku", 130d), ("İşlem", "Operation", 130d), ("Eski", "Before", 250d), ("Yeni", "After", 250d), ("Durum", "Status", 80d), ("Hata", "Error", 260d) }) preview.Columns.Add(new DataGridTextColumn { Header = column.Item1, Binding = new Binding(column.Item2), Width = column.Item3 });
        var status = Text("Ürünleri getirerek başlayın."); var progress = new ProgressBar { Height = 18, Minimum = 0, Maximum = 100, Width = 280, Margin = new Thickness(3), Visibility = Visibility.Collapsed }; var cts = (CancellationTokenSource?)null; BulkProductPreview? currentPreview = null; List<CatalogProduct> all = [];
        void Load() { all = catalog.Products(search.Text.Trim()); products.ItemsSource = all; status.Text = $"{all.Count:N0} ürün · seçim yoksa arama sonucunun tamamı önizlemeye alınır."; }
        BulkProductOperationRequest Request() => new((BulkProductOperationKind)operation.SelectedItem!, value.Text, channel.Text, shop.Text, listing.Text, targetCategory.Text);
        var makePreview = Button("Önizlemeyi hesapla"); makePreview.Click += (_, _) => { try { var selected = products.SelectedItems.OfType<CatalogProduct>().ToList(); if (selected.Count == 0) selected = all; if (selected.Count == 0) throw new InvalidOperationException("Önizleme için ürün bulunamadı."); currentPreview = operations.Preview(selected, Request()); preview.ItemsSource = currentPreview.Lines; status.Text = $"{currentPreview.Lines.Count:N0} satır · Hazır: {currentPreview.Lines.Count(x => x.Status == "READY")} · Atlandı: {currentPreview.Lines.Count(x => x.Status == "SKIP")} · Hata: {currentPreview.Lines.Count(x => x.Status == "ERROR")}. Uygulama için açık onay gerekli."; } catch (Exception error) { status.Text = error.Message; } }; controls.Children.Add(makePreview);
        var apply = Button("Önizlemeyi onayla ve uygula"); apply.Click += async (_, _) => { if (currentPreview is null) { status.Text = "Önce önizleme hesaplayın."; return; } /* #821: high-impact, local: the operator types the READY count, re-counted at the click by re-running the preview against the store. */ var readyNow = currentPreview.Lines.Count(x => x.Status == "READY"); var intent = new DestructiveIntent("Uygula", $"{currentPreview.Request.Kind} işlemi (yerel)", readyNow, IsLocalOnly: true, Noun: "ürün"); if (!DestructiveConfirmDialog.Show(Window.GetWindow(apply), intent, () => { var again = products.SelectedItems.OfType<CatalogProduct>().ToList(); if (again.Count == 0) again = all; return operations.Preview(again, currentPreview.Request).Lines.Count(x => x.Status == "READY"); })) return; if (cts != null) return; cts = new CancellationTokenSource(); progress.Visibility = Visibility.Visible; apply.IsEnabled = false; try { var p = new Progress<int>(x => progress.Value = x); var result = await Task.Run(() => operations.Apply(currentPreview, true, cts.Token, p), cts.Token); new AuditStore(directory).Append(new() { Module = "bulk-products", Action = currentPreview.Request.Kind.ToString(), Outcome = result.Errors == 0 ? "Succeeded" : "Partial", Detail = $"{result.Applied} uygulandı, {result.Skipped} atlandı, {result.Errors} hata." }); status.Text = $"Toplu işlem tamamlandı: {result.Applied} uygulandı, {result.Skipped} atlandı, {result.Errors} hata. Canlı kanal değiştirilmedi."; Load(); currentPreview = null; preview.ItemsSource = null; } catch (OperationCanceledException) { status.Text = "Toplu işlem iptal edildi; atomik işlem geri alındı."; } catch (Exception error) { status.Text = MarketplaceConnectionStore.Redact(error.Message); } finally { cts?.Dispose(); cts = null; progress.Visibility = Visibility.Collapsed; apply.IsEnabled = true; } }; controls.Children.Add(apply);
        var cancel = Button("İptal"); cancel.Click += (_, _) => cts?.Cancel(); controls.Children.Add(cancel); controls.Children.Add(progress); refresh.Click += (_, _) => Load(); search.TextChanged += (_, _) => Load();
        var links = new WrapPanel(); links.Children.Add(Button("Ürün yönetimine git", () => navigate?.Invoke("products"))); links.Children.Add(Button("Kanal yayın matrisine git", () => navigate?.Invoke("listing-matrix"))); top.Children.Add(links); top.Children.Add(status); top.Children.Add(Text("Kanal planı işlemleri yalnız yerel ChannelProductsStore'a yazar; doğrulanmış connector preview/onay kapısı olmadan HTTP çağrısı yapılmaz.")); top.Children.Add(products); top.Children.Add(Text("İşlem önizlemesi", TextRole.SubsectionTitle)); top.Children.Add(preview); Load(); return root;
    }
    static TextBlock Text(string value, TextRole role = TextRole.Body) => TextStyles.Apply(new TextBlock { Text = value, TextWrapping = TextWrapping.Wrap, Margin = new Thickness(3, 4, 3, 7), Foreground = Brushes.DarkSlateGray }, role);
    static Button Button(string text) => new() { Content = text, Margin = new Thickness(3, 5, 3, 5) };
    static Button Button(string text, Action action) { var button = Button(text); button.Click += (_, _) => action(); return button; }
}
