using System.Globalization;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Media;
using TrMarketplaceHubDesktop.Catalog;
namespace TrMarketplaceHubDesktop;

public static class ChannelProductsPanel
{
 public static FrameworkElement Create(string channelId,string? directory=null)
 {
  var channel=channelId.Trim().ToLowerInvariant();var title=channel=="ebay"?"eBay":channel=="ozon"?"Ozon":channel=="joom"?"Joom":channelId;
  var catalog=new CatalogStore(directory);var store=new ChannelProductsStore(directory);int offset=0,total=0;CatalogProduct? selected=null;string loadedShop="";
  var root=new Grid{Margin = Spacing.Page};root.RowDefinitions.Add(new(){Height=GridLength.Auto});root.RowDefinitions.Add(new(){Height=GridLength.Auto});root.RowDefinitions.Add(new(){Height=new GridLength(1,GridUnitType.Star)});
  var heading=new StackPanel();heading.Children.Add(new TextBlock{Text=$"Yerel kanal kartları — {title} · canlı senkron değil",FontSize=21,FontWeight=FontWeights.SemiBold,TextWrapping=TextWrapping.Wrap});heading.Children.Add(new TextBlock{Text="Merkez havuzdan ürün seçin; mağazaya özel fiyat, stok ve ilan eşleştirme planını bu bilgisayarda saklayın.",TextWrapping=TextWrapping.Wrap,Margin=new Thickness(0,6,0,12),Foreground=Brushes.DimGray});root.Children.Add(heading);
  var toolbar=new WrapPanel{Margin=Spacing.BelowSection};Grid.SetRow(toolbar,1);root.Children.Add(toolbar);
  var search=new TextBox{Width=205,Margin=new Thickness(0,0,8,6),ToolTip="Ürün adı, SKU, barkod, marka veya kategori"};toolbar.Children.Add(search);
  Button Btn(string text){var b=new Button{Content=text,Padding=new Thickness(12,6,12,6),Margin=new Thickness(0,0,8,6)};toolbar.Children.Add(b);return b;}
  var find=Btn("Ara / yenile");var prev=Btn("Önceki");var next=Btn("Sonraki");var count=new TextBlock{VerticalAlignment=VerticalAlignment.Center};toolbar.Children.Add(count);
  var body=new Grid();body.ColumnDefinitions.Add(new(){Width=new GridLength(1.1,GridUnitType.Star)});body.ColumnDefinitions.Add(new(){Width=new GridLength(1,GridUnitType.Star)});Grid.SetRow(body,2);root.Children.Add(body);
  var table=new DataGrid{IsReadOnly=true,AutoGenerateColumns=false,SelectionMode=DataGridSelectionMode.Single,CanUserAddRows=false,CanUserDeleteRows=false,EnableRowVirtualization=true,EnableColumnVirtualization=false,Margin=new Thickness(0,0,16,0),MinHeight=160};VirtualizingPanel.SetIsVirtualizing(table,true);VirtualizingPanel.SetVirtualizationMode(table,VirtualizationMode.Recycling);
  void Col(string name,string path,double width){var column=GridColumns.Text(name,path,new DataGridLength(width,DataGridLengthUnitType.Star));column.MinWidth=Math.Max(column.MinWidth,name switch{"Merkez ürün"=>145,"SKU"=>120,"Fiyat"=>85,"Stok"=>75,_=>65});table.Columns.Add(column);}Col("Merkez ürün","Name",2);Col("SKU","Sku",1);Col("Stok","Stock",.55);Col("Fiyat","Price",.65);Col("Döviz","Currency",.55);body.Children.Add(table);
  var editor=new StackPanel{Margin=new Thickness(0,0,8,0)};var scroll=new ScrollViewer{Content=editor,VerticalScrollBarVisibility=ScrollBarVisibility.Auto,HorizontalScrollBarVisibility=ScrollBarVisibility.Disabled};Grid.SetColumn(scroll,1);body.Children.Add(scroll);
  var card=new TextBox{IsReadOnly=true,TextWrapping=TextWrapping.Wrap,BorderThickness=new Thickness(0),Background=Brushes.Transparent,Text="Merkez havuzdan bir ürün seçin.",Margin=Spacing.BelowSection};System.Windows.Automation.AutomationProperties.SetName(card,"Ürün kartı");editor.Children.Add(card);
  TextBox Field(string label,string value=""){var caption=new TextBlock{Text=label,Margin=new Thickness(0,7,0,3),Foreground=Brushes.DimGray};editor.Children.Add(caption);var t=new TextBox{Text=value,Padding=new Thickness(7),MinWidth=100};editor.Children.Add(t);FormField.Labelled(caption,t);return t;}
  var shop=Field("Yerel mağaza anahtarı (API bağlantısı değildir)","varsayilan");var load=new Button{Content="Bu mağazanın planını yükle",Margin=Spacing.VerticalControl,Padding=new Thickness(8)};editor.Children.Add(load);
  var scope=new TextBlock{TextWrapping=TextWrapping.Wrap,Foreground=Brushes.DarkSlateBlue};editor.Children.Add(scope);
  var listing=Field("Hedef ilan kimliği · elle girilen, doğrulanmamış");var url=Field("Hedef ilan bağlantısı · elle girilen, doğrulanmamış");var category=Field("Hedef kategori / kategori kimliği · yerel plan");var price=Field("Planlanan satış fiyatı");var currency=Field("Plan para birimi (USD / EUR / RUB / TRY)");var stock=Field("Planlanan stok");var notes=Field("Yerel not");notes.AcceptsReturn=true;notes.MinHeight=55;notes.TextWrapping=TextWrapping.Wrap;
  var save=new Button{Content="Yerel planı kaydet",Padding=Spacing.Section,Margin=new Thickness(0,14,0,6)};CommandState.Apply(save,DisabledReason.StoreState("Önce ürün seçip planı yükleyin."));editor.Children.Add(save);var status=new TextBlock{Text="Uzaktaki ilan durumu bilinmiyor. Bu ekran pazaryerine ürün, fiyat veya stok göndermez.",TextWrapping=TextWrapping.Wrap,Foreground=Brushes.DimGray,Margin=new Thickness(0,6,0,12)};editor.Children.Add(status);
  void LoadPlan(){if(selected==null)return;try{loadedShop=shop.Text.Trim();var plan=store.Find(channel,loadedShop,selected.Id);listing.Text=plan?.ListingId??"";url.Text=plan?.ListingUrl??"";category.Text=plan?.TargetCategory??"";price.Text=(plan?.PlannedPrice??selected.Price).ToString(CultureInfo.CurrentCulture);currency.Text=plan?.Currency??selected.Currency;stock.Text=(plan?.PlannedStock??selected.Stock).ToString(CultureInfo.CurrentCulture);notes.Text=plan?.Notes??"";scope.Text=$"Mağaza: {loadedShop} · "+(plan==null?"Kaydedilmemiş öneri — merkez değerleri":"Yerel taslak · "+TimeDisplay.Format(plan.UpdatedUtc));CommandState.Apply(save,null);status.Text="Uzaktaki ilan durumu bilinmiyor. Plan yalnızca bu bilgisayara kaydedilir.";}catch(Exception ex){CommandState.Apply(save,DisabledReason.StoreState("Plan yüklenemedi."));status.Text=ex.Message;}}
  table.SelectionChanged+=(_,_)=>{selected=table.SelectedItem as CatalogProduct;CommandState.Apply(save,DisabledReason.StoreState("Önce planı yükleyin."));if(selected==null){card.Text="Merkez havuzdan bir ürün seçin.";return;}var p=selected;card.Text=$"{p.Name}\n\nMerkez kimliği: {p.Id}\nKaynak: {p.SourceId}\nSKU: {p.Sku}\nBarkod: {p.Barcode}\nGTIN: {p.Gtin}\nMarka: {p.Brand}\nKategori: {p.Category}\nMaliyet: {p.Cost} {p.CostCurrency}\nMerkez fiyatı: {p.Price} {p.Currency}\nMerkez stok: {p.Stock} · {p.StatusLabel}\nEtsy ilan kimliği: {p.EtsyListingId}\n\nAçıklama: {p.Description}\n\nGörsel bağlantıları (otomatik indirilmez):\n{p.ImageUrls}";LoadPlan();};
  shop.TextChanged+=(_,_)=>{CommandState.Apply(save,DisabledReason.StoreState("Mağaza değişti; planı yeniden yükleyin."));scope.Text="Mağaza değişti; planı yükleyin.";};load.Click+=(_,_)=>LoadPlan();
  save.Click+=(_,_)=>{try{if(selected==null||loadedShop!=shop.Text.Trim())throw new ArgumentException("Ürün seçin ve mağaza planını yeniden yükleyin.");if(!decimal.TryParse(price.Text,NumberStyles.AllowDecimalPoint|NumberStyles.AllowLeadingSign,CultureInfo.CurrentCulture,out var amount))throw new ArgumentException("Fiyat geçersiz; sistemin ondalık ayırıcısını kullanın.");if(!int.TryParse(stock.Text,out var qty))throw new ArgumentException("Stok tam sayı olmalı.");store.Save(new(){ChannelId=channel,ShopId=loadedShop,ProductId=selected.Id,ListingId=listing.Text.Trim(),ListingUrl=url.Text.Trim(),TargetCategory=category.Text.Trim(),PlannedPrice=amount,Currency=currency.Text.Trim().ToUpperInvariant(),PlannedStock=qty,Notes=notes.Text});LoadPlan();status.Text="Yerel plan kaydedildi. Merkez havuz ve pazaryeri değiştirilmedi.";}catch(Exception ex){status.Text=ex.Message;}};
  void Refresh(){try{var page=catalog.Search(search.Text.Trim(),offset,200);total=page.Total;table.ItemsSource=page.Items;count.Text=total==0?"Ürün yok — XML kaynaklarından havuza aktarın":$"{offset+1}–{offset+page.Items.Count} / {total}";CommandState.Apply(prev,offset>0?null:DisabledReason.StoreState("İlk sayfadasınız."));CommandState.Apply(next,offset+200<total?null:DisabledReason.StoreState("Son sayfadasınız."));}catch(Exception ex){status.Text="Havuz okunamadı: "+ex.Message;}}
  find.Click+=(_,_)=>{offset=0;Refresh();};search.KeyDown+=(_,e)=>{if(e.Key==System.Windows.Input.Key.Enter){offset=0;Refresh();}};prev.Click+=(_,_)=>{offset=Math.Max(0,offset-200);Refresh();};next.Click+=(_,_)=>{offset+=200;Refresh();};root.Loaded+=(_,_)=>{offset=0;Refresh();};Refresh();return root;
 }
}

