using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Media;

namespace TrMarketplaceHubDesktop;

public static class DataQualityPanel
{
    public static FrameworkElement Create(string? directory = null, Action<string>? navigate = null)
    {
        var service = new DataQualityService(directory); var root = new DockPanel { Margin = Spacing.Section }; var top = new StackPanel(); DockPanel.SetDock(top, Dock.Top); root.Children.Add(top); top.Children.Add(Text("Veri kalite merkezi", TextRole.SectionTitle)); top.Children.Add(Text("Ürün, XML, Excel kaynaklı katalog ve kanal planı sorunlarını canlı sync öncesi görünür yapar. Öneriler preview'dir; kör otomatik düzeltme yoktur."));
        var bar = new WrapPanel(); top.Children.Add(bar); var query = new TextBox { Width = 220, ToolTip = "SKU, ürün, kaynak, kanal veya hata ara" }; var severity = new ComboBox { Width = 110, ItemsSource = new[] { "Tümü", "Critical", "Error", "Warning" }, SelectedIndex = 0 }; var state = new ComboBox { Width = 110, ItemsSource = new[] { "Tümü", "Open", "Resolved" }, SelectedIndex = 0 }; var type = new ComboBox { Width = 170, ItemsSource = new[] { "Tümü", "DuplicateSku", "DuplicateBarcode", "DuplicateListing", "MissingName", "MissingIdentity", "InvalidNumber", "InvalidCurrency", "InvalidVatRate", "InvalidImageUrl", "MissingXmlSource", "XmlRunFailed", "LiveApiBlocked" }, SelectedIndex = 0 }; bar.Children.Add(query); bar.Children.Add(severity); bar.Children.Add(state); bar.Children.Add(type); var scan = Button("Tara / yenile"); bar.Children.Add(scan); var resolve = Button("Seçileni çözüldü işaretle"); bar.Children.Add(resolve);
        var summary = Text(""); top.Children.Add(summary); var grid = new DataGrid { AutoGenerateColumns = false, IsReadOnly = true, SelectionMode = DataGridSelectionMode.Single, EnableRowVirtualization = true }; VirtualizingPanel.SetIsVirtualizing(grid, true); VirtualizingPanel.SetVirtualizationMode(grid, VirtualizationMode.Recycling); foreach (var c in new[] { ("Önem", "Severity", 80d), ("Tür", "Type", 145d), ("SKU", "Sku", 130d), ("Ürün", "ProductId", 150d), ("Kanal", "Marketplace", 100d), ("Mağaza", "ShopId", 110d), ("Kaynak", "SourceId", 140d), ("Açıklama", "Message", 350d), ("Durum", "Status", 90d) }) grid.Columns.Add(new DataGridTextColumn { Header = c.Item1, Binding = new Binding(c.Item2), Width = c.Item3 }); root.Children.Add(grid);
        DataQualityIssue? selected = null; var detail = Text("Bir sorun seçin."); top.Children.Add(detail); var openProduct = Button("İlgili kayda git"); openProduct.Click += (_, _) => { if (selected is null) { detail.Text = "Önce bir kalite kaydı seçin."; return; } navigate?.Invoke(selected.Type.Contains("Xml", StringComparison.OrdinalIgnoreCase) || selected.Type.Contains("Source", StringComparison.OrdinalIgnoreCase) ? "xml" : selected.Type.Contains("Listing", StringComparison.OrdinalIgnoreCase) || selected.Marketplace.Length > 0 ? "connections" : "products"); }; var openXml = Button("XML ekranına git"); openXml.Click += (_, _) => navigate?.Invoke("xml"); top.Children.Add(new WrapPanel { Children = { openProduct, openXml } });
        void Reload() { var rows = service.List(query.Text, severity.SelectedItem?.ToString() == "Tümü" ? null : severity.SelectedItem?.ToString(), state.SelectedItem?.ToString() == "Tümü" ? null : state.SelectedItem?.ToString(), type.SelectedItem?.ToString() == "Tümü" ? null : type.SelectedItem?.ToString()); grid.ItemsSource = rows; var totals = service.Summary(); summary.Text = $"{totals.Total:N0} sorun · Kritik {totals.Critical} · Hata {totals.Error} · Uyarı {totals.Warning} · Açık {totals.Open} · Çözüldü {totals.Resolved}"; }
        void Scan() { try { service.Scan(); Reload(); detail.Text = "Tarama tamamlandı. Aynı fingerprint tekrar çoğaltılmaz."; } catch (Exception error) { detail.Text = MarketplaceConnectionStore.Redact(error.Message); } }
        grid.SelectionChanged += (_, _) => { selected = grid.SelectedItem as DataQualityIssue; detail.Text = selected is null ? "Bir sorun seçin." : $"{selected.Severity} · {selected.Type}\n{selected.Message}\nÖneri: {selected.Suggestion}\nÜrün: {selected.ProductId} · Kaynak: {selected.SourceId}"; }; resolve.Click += (_, _) => { if (selected is null) { detail.Text = "Önce sorun seçin."; return; } service.Resolve(selected.Id); Reload(); detail.Text = "Sorun çözüldü olarak işaretlendi; otomatik ürün düzeltmesi yapılmadı."; }; scan.Click += (_, _) => Scan(); query.TextChanged += (_, _) => Reload(); severity.SelectionChanged += (_, _) => Reload(); state.SelectionChanged += (_, _) => Reload(); type.SelectionChanged += (_, _) => Reload(); Scan(); return root;
    }
    static TextBlock Text(string value, TextRole role = TextRole.Body) => TextStyles.Apply(new TextBlock { Text = value, TextWrapping = TextWrapping.Wrap, Margin = Spacing.BodyBlock, Foreground = Brushes.DarkSlateGray }, role);
    static Button Button(string text) => new() { Content = text, Margin = new Thickness(3, 5, 3, 5) };
}
