using System.Windows;
using System.Windows.Controls;
using TrMarketplaceHubDesktop.Catalog;

namespace TrMarketplaceHubDesktop;

public partial class MainWindow
{
    FrameworkElement BuildTaxonomy()
    {
        var taxonomy = new TaxonomyStore(dataDirectory); var aliases = new TaxonomyAliasStore(dataDirectory); // #912
        var panel = new StackPanel { Margin = new Thickness(DesignTokens.SpacePage), MaxWidth = 1200 };
        panel.Children.Add(Heading("Kategori, marka ve özellik merkezi"));
        panel.Children.Add(Hint("Yerel sözlük, kanal/mağaza eşlemeleri ve eksik/stale durumları tek ekranda izlenir. Öneriler yalnız isim normalizasyonuna dayanır; canlı marketplace yazımı yapılmaz."));
        var kind = new ComboBox { ItemsSource = Enum.GetValues<TaxonomyKind>(), SelectedItem = TaxonomyKind.Category, Width = 180 };
        var marketplace = new TextBox { Text = "etsy", Width = 120 };
        var shop = new TextBox { Text = "default", Width = 140 };
        var search = new TextBox { Width = 180, ToolTip = "Yerel ad, değer veya harici anahtar ara" };
        var name = new TextBox { Width = 180 }; var value = new TextBox { Width = 180 }; var external = new TextBox { Width = 220 };
        var externalBatch = new TextBox { Width = 420, Height = 65, AcceptsReturn = true, TextWrapping = TextWrapping.Wrap, ToolTip = "Her satıra bir harici kategori/marka adı" };
        var status = Hint("");
        var localGrid = new DataGrid { AutoGenerateColumns = true, IsReadOnly = true, Height = 230, EnableRowVirtualization = true };
        var mappingGrid = new DataGrid { AutoGenerateColumns = true, IsReadOnly = true, Height = 250, EnableRowVirtualization = true };
        var historyGrid = new DataGrid { AutoGenerateColumns = true, IsReadOnly = true, Height = 200, EnableRowVirtualization = true };
        var aliasGrid = new DataGrid { AutoGenerateColumns = true, IsReadOnly = true, Height = 200, EnableRowVirtualization = true }; // #912
        var attributeRules = new CategoryAttributeRuleStore(dataDirectory); var ruleGrid = new DataGrid { AutoGenerateColumns = true, IsReadOnly = true, Height = 200, EnableRowVirtualization = true }; // #915
        var snapshots = new TaxonomySnapshotStore(dataDirectory); var snapshotGrid = new DataGrid { AutoGenerateColumns = true, IsReadOnly = true, Height = 200, EnableRowVirtualization = true }; // #918
        var brandMapping = new BrandMappingStore(dataDirectory); var brandAliasGrid = new DataGrid { AutoGenerateColumns = true, IsReadOnly = true, Height = 200, EnableRowVirtualization = true }; var brandQueueGrid = new DataGrid { AutoGenerateColumns = true, IsReadOnly = true, Height = 220, EnableRowVirtualization = true }; // #917
        var valueMapping = new AttributeValueMappingStore(dataDirectory); var valueAliasGrid = new DataGrid { AutoGenerateColumns = true, IsReadOnly = true, Height = 200, EnableRowVirtualization = true }; var valueQueueGrid = new DataGrid { AutoGenerateColumns = true, IsReadOnly = true, Height = 200, EnableRowVirtualization = true }; // #916
        var reviewQueue = new CategoryReviewQueue(dataDirectory); var reviewGrid = new DataGrid { AutoGenerateColumns = true, IsReadOnly = true, Height = 220, EnableRowVirtualization = true, SelectionMode = DataGridSelectionMode.Extended }; // #913
        IReadOnlyList<TaxonomySuggestion> pendingSuggestions = [];
        void Refresh()
        {
            var selected = (TaxonomyKind)kind.SelectedItem!; var market = marketplace.Text.Trim(); var shopId = shop.Text.Trim();
            var local = taxonomy.List(selected).Where(x => string.IsNullOrWhiteSpace(search.Text) || $"{x.Name} {x.Value}".Contains(search.Text.Trim(), StringComparison.CurrentCultureIgnoreCase)).ToList();
            localGrid.ItemsSource = local; var views = taxonomy.MappingViews(selected, market, shopId, search.Text.Trim()); mappingGrid.ItemsSource = views; historyGrid.ItemsSource = taxonomy.History(selected, market, shopId); aliasGrid.ItemsSource = aliases.List(); /* #912 */ reviewGrid.ItemsSource = reviewQueue.List(CategoryReviewItem.Pending); /* #913 */ ruleGrid.ItemsSource = attributeRules.List(); /* #915 */ valueAliasGrid.ItemsSource = valueMapping.ListAliases(); valueQueueGrid.ItemsSource = valueMapping.ListQueue(AttributeValueQueueItem.Pending); /* #916 */ brandAliasGrid.ItemsSource = brandMapping.ListAliases(); brandQueueGrid.ItemsSource = brandMapping.List(BrandReviewItem.Pending); var brandDuplicates = brandMapping.Duplicates().Count; /* #917 */
            var mapped = views.Count(x => x.Status == "MAPPED");
            var missing = views.Count(x => x.Status == "MISSING");
            var stale = views.Count(x => x.Status == "STALE");
            var invalid = views.Count(x => x.Status == "INVALID");
            status.Text = $"{local.Count} yerel kayıt · {mapped} eşleşmiş · {missing} eksik · {stale} stale · {invalid} geçersiz" + (brandDuplicates > 0 ? $" · {brandDuplicates} mükerrer marka adı" : ""); /* #917 */ var snapshot = snapshots.Refresh(TaxonomySnapshotStore.LocalScope, DateTime.UtcNow); snapshotGrid.ItemsSource = snapshots.History(TaxonomySnapshotStore.LocalScope); status.Text += " · " + TaxonomySnapshotStore.Describe(snapshot, DateTime.UtcNow); /* #918 */
        }
        kind.SelectionChanged += (_, _) => Refresh(); marketplace.TextChanged += (_, _) => Refresh(); shop.TextChanged += (_, _) => Refresh(); search.TextChanged += (_, _) => Refresh();
        var save = Button("Yerel kaydı kaydet", () => { taxonomy.Save(new TaxonomyEntry { Kind = (TaxonomyKind)kind.SelectedItem!, Name = name.Text, Value = value.Text }); name.Clear(); value.Clear(); Refresh(); });
        // #919: what the mapping would touch, before it touches anything -- the products whose readiness on this channel changes and their plans; an impact asks, a cancel changes nothing, and the apply refuses when the taxonomy moved since the preview.
        var map = Button("Harici anahtarı eşle", () => { if (localGrid.SelectedItem is not TaxonomyEntry entry) throw new InvalidOperationException("Önce yerel listeden kayıt seçin."); var impact = MappingImpact.Preview(dataDirectory, (TaxonomyKind)kind.SelectedItem!, external.Text, entry.Id, marketplace.Text, shop.Text, store.Products(), new ChannelProductsStore(dataDirectory).List()); if (impact.RequiresConfirmation && !DialogShell.Confirm(this, "Eşleme etkisi", impact.Body, "Uygula", destructive: false)) { status.Text = "Eşleme uygulanmadı; hiçbir şey değişmedi."; return; } MappingImpact.Apply(dataDirectory, impact); external.Clear(); Refresh(); status.Text = impact.Level == MappingImpactLevel.None ? "Eşleme uygulandı; etkilenen ürün yok." : $"Eşleme uygulandı; {impact.AffectedProducts} ürün, {impact.AffectedPlans} plan etkilendi."; });
        // #920: a rollback proposal returns the selected mapping to its previous revision -- blocked (no previous, target gone, later unrelated edits) it only says why; clean, it asks with the impact and applies behind the stale guard.
        var rollback = Button("Seçili eşlemeyi geri al (öneri)", () => { if (mappingGrid.SelectedItem is not TaxonomyMappingView view || view.ExternalKey.Length == 0) throw new InvalidOperationException("Önce kanal/mağaza eşleme listesinden eşlenmiş bir satır seçin."); var proposal = MappingRollback.Propose(dataDirectory, view.Kind, view.ExternalKey, view.Marketplace, view.ShopId, store.Products(), new ChannelProductsStore(dataDirectory).List()); if (proposal.Blocked) { status.Text = proposal.Headline; return; } if (!DialogShell.Confirm(this, "Eşlemeyi geri al", proposal.Body, "Geri al", destructive: false)) { status.Text = "Geri alma uygulanmadı; hiçbir şey değişmedi."; return; } MappingRollback.Apply(dataDirectory, proposal); Refresh(); status.Text = $"Eşleme geri alındı: {proposal.ExternalKey} → {proposal.PreviousName}."; });
        var suggest = Button("İsim önerisi oluştur", () => { pendingSuggestions = taxonomy.SuggestBulk((TaxonomyKind)kind.SelectedItem!, externalBatch.Text.Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries)); mappingGrid.ItemsSource = pendingSuggestions; var suggested = pendingSuggestions.Count(x => x.Status == "SUGGESTED"); var unmatched = pendingSuggestions.Count(x => x.Status == "UNMATCHED"); status.Text = $"{suggested} öneri · {unmatched} eşleşmeyen; henüz yazılmadı."; });
        var bulk = Button("Toplu eşlemeyi önizle / onayla", () => { if (pendingSuggestions.Count == 0) throw new InvalidOperationException("Önce harici anahtar listesinden öneri oluşturun."); var previews = pendingSuggestions.Where(x => x.LocalId is not null).Select(x => MappingImpact.Preview(dataDirectory, (TaxonomyKind)kind.SelectedItem!, x.ExternalKey, x.LocalId!, marketplace.Text, shop.Text, store.Products(), new ChannelProductsStore(dataDirectory).List())).ToList(); var text = string.Join("\n", previews.Select(x => $"{x.ExternalKey} → {x.LocalName}: {x.AffectedProducts} ürün, {x.AffectedPlans} plan")); if (MessageBox.Show(text + $"\n\nToplam {previews.Sum(x => x.AffectedProducts)} ürünün bu kanaldaki hazırlığı değişir. Sadece önerilen eşleşmeler yerel veritabanına yazılsın mı?", "Eşleme önizlemesi", MessageBoxButton.YesNo, MessageBoxImage.Question) != MessageBoxResult.Yes) { status.Text += " · Toplu eşleme uygulanmadı; hiçbir şey değişmedi."; return; } foreach (var preview in previews) MappingImpact.Apply(dataDirectory, preview); /* #919: each mapping behind the stale guard */ Refresh(); status.Text += " · Toplu eşleme uygulandı."; });
        var row = new WrapPanel(); row.Children.Add(new TextBlock { Text = "Tür", VerticalAlignment = VerticalAlignment.Center, Margin = Spacing.Inline }); row.Children.Add(kind); row.Children.Add(new TextBlock { Text = "Kanal", VerticalAlignment = VerticalAlignment.Center, Margin = Spacing.Inline }); row.Children.Add(marketplace); row.Children.Add(new TextBlock { Text = "Mağaza", VerticalAlignment = VerticalAlignment.Center, Margin = Spacing.Inline }); row.Children.Add(shop); row.Children.Add(new TextBlock { Text = "Ara", VerticalAlignment = VerticalAlignment.Center, Margin = Spacing.Inline }); row.Children.Add(search); panel.Children.Add(row);
        var localRow = new WrapPanel(); localRow.Children.Add(new TextBlock { Text = "Yerel ad", VerticalAlignment = VerticalAlignment.Center, Margin = Spacing.Inline }); localRow.Children.Add(name); localRow.Children.Add(new TextBlock { Text = "Değer", VerticalAlignment = VerticalAlignment.Center, Margin = Spacing.Inline }); localRow.Children.Add(value); localRow.Children.Add(save); panel.Children.Add(localRow);
        // #912: an alias is added for the local category selected in the dictionary; only an approved one is applied by the import.
        var alias = new TextBox { Width = 260 }; var aliasApproved = new CheckBox { Content = "Onaylı (içe aktarmada otomatik uygulanır)", IsChecked = true, VerticalAlignment = VerticalAlignment.Center, Margin = Spacing.Inline };
        var addAlias = Button("Takma adı ekle", () => { if (localGrid.SelectedItem is not TaxonomyEntry entry) throw new InvalidOperationException("Önce yerel listeden kategori seçin."); var view = aliases.Save(alias.Text, entry.Id, aliasApproved.IsChecked == true, "manual"); alias.Clear(); Refresh(); status.Text = $"Takma ad kaydedildi: {view.CategoryName} ← {view.Alias} ({(view.Approved ? "onaylı" : "beklemede")})."; });
        var removeAlias = Button("Seçili takma adı kaldır", () => { if (aliasGrid.SelectedItem is not TaxonomyAliasView view) throw new InvalidOperationException("Önce takma ad listesinden seçim yapın."); aliases.Remove(view.Alias); Refresh(); });
        var aliasRow = new WrapPanel(); Label(aliasRow, "Takma ad (tedarikçinin yazımı)", alias); aliasRow.Children.Add(aliasApproved); aliasRow.Children.Add(addAlias); aliasRow.Children.Add(removeAlias); panel.Children.Add(aliasRow);
        // #913: the review queue acts only on the rows the operator selected and previewed -- approve them all to the selected local category, or reject them.
        var approveReview = Button("Seçili kuyruk değerlerini seçili kategoriye onayla", () => { if (localGrid.SelectedItem is not TaxonomyEntry entry) throw new InvalidOperationException("Önce yerel listeden kategori seçin."); var items = reviewGrid.SelectedItems.OfType<CategoryReviewItem>().ToList(); if (items.Count == 0) throw new InvalidOperationException("Önce inceleme kuyruğundan değer seçin."); var preview = string.Join("\n", items.Take(20).Select(i => $"• {i.Value} ({i.Count} satır, kaynak {i.SourceId[..Math.Min(8, i.SourceId.Length)]})")) + (items.Count > 20 ? $"\n… ve {items.Count - 20} değer daha" : ""); if (!DialogShell.Confirm(this, "Toplu onay", $"{items.Count} değer '{entry.Name}' kategorisinin onaylı takma adı olacak; sonraki içe aktarmalar bunları uygular.\n{preview}", "Onayla", destructive: false)) return; var done = reviewQueue.ApproveBulk(items, entry.Id, true, DateTime.UtcNow); Refresh(); status.Text = $"{done} değer onaylandı ve sözlüğe yazıldı."; });
        var rejectReview = Button("Seçili kuyruk değerlerini reddet", () => { var items = reviewGrid.SelectedItems.OfType<CategoryReviewItem>().ToList(); if (items.Count == 0) throw new InvalidOperationException("Önce inceleme kuyruğundan değer seçin."); if (!DialogShell.Confirm(this, "Toplu ret", $"{items.Count} değer reddedilecek; bir sonraki görülmede yeniden kuyruğa girer.", "Reddet")) return; var done = reviewQueue.RejectBulk(items, true, DateTime.UtcNow); Refresh(); status.Text = $"{done} değer reddedildi."; });
        var reviewRow = new WrapPanel(); reviewRow.Children.Add(approveReview); reviewRow.Children.Add(rejectReview); panel.Children.Add(reviewRow);
        // #915: an attribute rule belongs to the local category selected in the dictionary; the attribute's allowed values are the Attribute entries of that name.
        var ruleAttribute = new TextBox { Width = 220 }; var ruleRequired = new CheckBox { Content = "Zorunlu", IsChecked = true, VerticalAlignment = VerticalAlignment.Center, Margin = Spacing.Inline };
        var addRule = Button("Özellik kuralı ekle", () => { if (localGrid.SelectedItem is not TaxonomyEntry entry) throw new InvalidOperationException("Önce yerel listeden kategori seçin."); var rule = attributeRules.Save(entry.Id, ruleAttribute.Text, ruleRequired.IsChecked == true); ruleAttribute.Clear(); Refresh(); status.Text = $"Özellik kuralı kaydedildi: {rule.CategoryName} · {rule.Attribute} ({(rule.Required ? "zorunlu" : "isteğe bağlı")})."; });
        var removeRule = Button("Seçili özellik kuralını kaldır", () => { if (ruleGrid.SelectedItem is not CategoryAttributeRule rule) throw new InvalidOperationException("Önce kural listesinden seçim yapın."); attributeRules.Remove(rule.CategoryId, rule.Attribute); Refresh(); });
        var ruleRow = new WrapPanel(); Label(ruleRow, "Özellik adı (seçili kategori için)", ruleAttribute); ruleRow.Children.Add(ruleRequired); ruleRow.Children.Add(addRule); ruleRow.Children.Add(removeRule); panel.Children.Add(ruleRow);
        // #916: a supplier's spelling of an allowed value is an alias of that value; the queue holds the spellings no alias placed, with their evidence.
        var valueAttribute = new TextBox { Width = 160 }; var valueAlias = new TextBox { Width = 180 }; var valueCanonical = new TextBox { Width = 180 }; var valueApproved = new CheckBox { Content = "Onaylı", IsChecked = true, VerticalAlignment = VerticalAlignment.Center, Margin = Spacing.Inline };
        var addValueAlias = Button("Değer takma adı ekle", () => { var view = valueMapping.SaveAlias(valueAttribute.Text, valueAlias.Text, valueCanonical.Text, valueApproved.IsChecked == true, "manual"); valueAlias.Clear(); Refresh(); status.Text = $"Değer takma adı kaydedildi: {view.Attribute} · {view.Alias} → {view.CanonicalValue} ({(view.Approved ? "onaylı" : "beklemede")})."; });
        var removeValueAlias = Button("Seçili değer takma adını kaldır", () => { if (valueAliasGrid.SelectedItem is not AttributeValueAliasView view) throw new InvalidOperationException("Önce değer takma adı listesinden seçim yapın."); valueMapping.RemoveAlias(view.Attribute, view.Alias); Refresh(); });
        var approveValue = Button("Seçili kuyruk değerini kanonik değere onayla", () => { if (valueQueueGrid.SelectedItem is not AttributeValueQueueItem item) throw new InvalidOperationException("Önce değer kuyruğundan seçim yapın."); var done = valueMapping.ApproveQueued(item.Attribute, item.Value, valueCanonical.Text); Refresh(); status.Text = $"Değer onaylandı: {done.Attribute} · {done.Value} → {valueCanonical.Text.Trim()}."; });
        var rejectValue = Button("Seçili kuyruk değerini reddet", () => { if (valueQueueGrid.SelectedItem is not AttributeValueQueueItem item) throw new InvalidOperationException("Önce değer kuyruğundan seçim yapın."); valueMapping.RejectQueued(item.Attribute, item.Value); Refresh(); });
        // #917: a brand alias belongs to the local brand selected in the dictionary; a queued string is approved to that brand (the operator's choice, not the suggestion's) or rejected as a false positive.
        var brandAlias = new TextBox { Width = 220 }; var brandAliasApproved = new CheckBox { Content = "Onaylı", IsChecked = true, VerticalAlignment = VerticalAlignment.Center, Margin = Spacing.Inline };
        var addBrandAlias = Button("Marka takma adı ekle", () => { if (localGrid.SelectedItem is not TaxonomyEntry entry || entry.Kind != TaxonomyKind.Brand) throw new InvalidOperationException("Önce yerel listeden marka seçin (tür: Brand)."); var view = brandMapping.SaveAlias(brandAlias.Text, entry.Id, brandAliasApproved.IsChecked == true, "manual"); brandAlias.Clear(); Refresh(); status.Text = $"Marka takma adı kaydedildi: {view.BrandName} ← {view.Alias} ({(view.Approved ? "onaylı" : "beklemede")})."; });
        var removeBrandAlias = Button("Seçili marka takma adını kaldır", () => { if (brandAliasGrid.SelectedItem is not BrandAliasView view) throw new InvalidOperationException("Önce marka takma adı listesinden seçim yapın."); brandMapping.RemoveAlias(view.Alias); Refresh(); });
        var approveBrand = Button("Seçili kuyruk markasını seçili markaya onayla", () => { if (localGrid.SelectedItem is not TaxonomyEntry entry || entry.Kind != TaxonomyKind.Brand) throw new InvalidOperationException("Önce yerel listeden marka seçin (tür: Brand)."); if (brandQueueGrid.SelectedItem is not BrandReviewItem item) throw new InvalidOperationException("Önce marka kuyruğundan seçim yapın."); var done = brandMapping.Approve(item.SourceId, item.Key, entry.Id); Refresh(); status.Text = $"Marka onaylandı: {done.Value} → {entry.Name}."; });
        var rejectBrand = Button("Seçili kuyruk markasını reddet", () => { if (brandQueueGrid.SelectedItem is not BrandReviewItem item) throw new InvalidOperationException("Önce marka kuyruğundan seçim yapın."); brandMapping.Reject(item.SourceId, item.Key); Refresh(); status.Text = "Marka önerisi reddedildi; bu marka bu yazım için bir daha önerilmez."; });
        var brandRow = new WrapPanel(); Label(brandRow, "Marka takma adı (tedarikçinin yazımı)", brandAlias); brandRow.Children.Add(brandAliasApproved); brandRow.Children.Add(addBrandAlias); brandRow.Children.Add(removeBrandAlias); brandRow.Children.Add(approveBrand); brandRow.Children.Add(rejectBrand); panel.Children.Add(brandRow);
        var valueRow = new WrapPanel(); Label(valueRow, "Özellik", valueAttribute); Label(valueRow, "Tedarikçi yazımı", valueAlias); Label(valueRow, "Kanonik (izinli) değer", valueCanonical); valueRow.Children.Add(valueApproved); valueRow.Children.Add(addValueAlias); valueRow.Children.Add(removeValueAlias); valueRow.Children.Add(approveValue); valueRow.Children.Add(rejectValue); panel.Children.Add(valueRow);
        var mappingRow = new WrapPanel(); mappingRow.Children.Add(new TextBlock { Text = "Harici anahtar", VerticalAlignment = VerticalAlignment.Center, Margin = Spacing.Inline }); mappingRow.Children.Add(external); mappingRow.Children.Add(map); mappingRow.Children.Add(rollback); /* #920 */ panel.Children.Add(mappingRow);
        var bulkRow = new StackPanel(); bulkRow.Children.Add(new TextBlock { Text = "Toplu öneri listesi (satır başına bir değer)", Margin = Spacing.Inline }); bulkRow.Children.Add(externalBatch); var bulkButtons = new WrapPanel(); bulkButtons.Children.Add(suggest); bulkButtons.Children.Add(bulk); bulkRow.Children.Add(bulkButtons); panel.Children.Add(bulkRow);
        var tabs = new TabControl(); tabs.Items.Add(new TabItem { Header = "Yerel sözlük", Content = localGrid }); tabs.Items.Add(new TabItem { Header = "Kanal / mağaza eşleme", Content = mappingGrid }); tabs.Items.Add(new TabItem { Header = "Eşleme geçmişi", Content = historyGrid }); tabs.Items.Add(new TabItem { Header = "Takma adlar", Content = aliasGrid }); /* #912 */ tabs.Items.Add(new TabItem { Header = "İnceleme kuyruğu", Content = reviewGrid }); /* #913 */ tabs.Items.Add(new TabItem { Header = "Özellik kuralları", Content = ruleGrid }); /* #915 */ tabs.Items.Add(new TabItem { Header = "Değer takma adları", Content = valueAliasGrid }); tabs.Items.Add(new TabItem { Header = "Değer kuyruğu", Content = valueQueueGrid }); /* #916 */ tabs.Items.Add(new TabItem { Header = "Marka takma adları", Content = brandAliasGrid }); tabs.Items.Add(new TabItem { Header = "Marka kuyruğu", Content = brandQueueGrid }); /* #917 */ tabs.Items.Add(new TabItem { Header = "Sürümler", Content = snapshotGrid }); /* #918 */ panel.Children.Add(tabs); panel.Children.Add(status); Refresh(); return Scroll(panel);
    }
}
