using System.Globalization;
using System.Windows;
using System.Windows.Controls;
using TrMarketplaceHubDesktop.Catalog;
namespace TrMarketplaceHubDesktop;
public partial class MainWindow {
 FrameworkElement BuildPricePolicies(){
 var panel=new StackPanel{Margin=new Thickness(20),MaxWidth=800,HorizontalAlignment=HorizontalAlignment.Left};panel.Children.Add(Heading("Pazaryeri satış ve üstü çizili fiyat formülleri"));panel.Children.Add(Hint("Alış fiyatı TL olan ürünlerde x alış fiyatıdır. CASE formülü TL sonuç üretir, hedef dövize çevrilir. Kayıtlı kuralla önizleme ürün fiyatını değiştirmez ve pazaryerine göndermez."));
 var channel=new ComboBox{ItemsSource=new[]{"etsy","ebay","ozon","joom","wish","amazon","trendyol","hepsiburada"},SelectedIndex=0,IsEditable=true};var shop=new TextBox();var formula=new TextBox{Text="x",Height=85,AcceptsReturn=true,TextWrapping=TextWrapping.Wrap};var listFormula=new TextBox{Text="x",Height=85,AcceptsReturn=true,TextWrapping=TextWrapping.Wrap};var currency=new ComboBox{ItemsSource=new[]{"TRY","USD","EUR","GBP"},SelectedIndex=0};var rate=new TextBox{Text="1"};var observed=new TextBox();var minimum=new TextBox{Text="0"};var margin=new TextBox{Text="0"};var output=Hint("");PricePolicy? loaded=null;
 Label(panel,"Pazaryeri",channel);Label(panel,"Mağaza anahtarı",shop);Label(panel,"Satış fiyatı formülü",formula);Label(panel,"Üstü çizili / liste fiyatı formülü",listFormula);Label(panel,"Satış dövizi",currency);Label(panel,"1 dövizin TL karşılığı (manuel kur)",rate);Label(panel,"Kur gözlem tarihi (ISO, örn. 2026-09-11T09:00:00+03:00)",observed);Label(panel,"Minimum satış fiyatı (hedef döviz)",minimum);Label(panel,"Alış üstü minimum fark (TL; net kâr değildir)",margin);
 static decimal Number(string text){if(!decimal.TryParse(text,NumberStyles.AllowDecimalPoint|NumberStyles.AllowLeadingSign,CultureInfo.InvariantCulture,out var n))throw new InvalidOperationException("Ondalık ayırıcı olarak nokta kullanın.");return n;}
 panel.Children.Add(Button("Kuralı yükle",()=>{loaded=store.GetPricePolicy(channel.Text,shop.Text)??new(){Channel=channel.Text.Trim().ToLowerInvariant(),Shop=shop.Text.Trim()};formula.Text=loaded.Formula;listFormula.Text=loaded.ListFormula;currency.SelectedItem=loaded.Currency;rate.Text=loaded.TryPerUnit.ToString(CultureInfo.InvariantCulture);observed.Text="";minimum.Text=loaded.MinimumPrice.ToString(CultureInfo.InvariantCulture);margin.Text=loaded.MinimumMarginTry.ToString(CultureInfo.InvariantCulture);output.Text=loaded.Version==0?"Yeni kural; kaydedilmedi.":"Kural yüklendi.";}));
 panel.Children.Add(Button("Kuralı kaydet",()=>{if(loaded==null||loaded.Channel!=channel.Text.Trim().ToLowerInvariant()||loaded.Shop!=shop.Text.Trim())throw new InvalidOperationException("Önce mağazanın kuralını yükleyin.");DateTimeOffset? time=null;if(!string.IsNullOrWhiteSpace(observed.Text)){if(!DateTimeOffset.TryParse(observed.Text,CultureInfo.InvariantCulture,DateTimeStyles.None,out var parsed))throw new InvalidOperationException("Kur tarihi geçersiz.");time=parsed;}loaded=store.SavePricePolicy(new(){Channel=loaded.Channel,Shop=loaded.Shop,Version=loaded.Version,Formula=formula.Text,ListFormula=listFormula.Text,Currency=currency.SelectedItem?.ToString()??"",TryPerUnit=Number(rate.Text),MinimumPrice=Number(minimum.Text),MinimumMarginTry=Number(margin.Text)});output.Text="Fiyat kuralı kaydedildi. Canlı fiyat değişmedi.";}));
 var product=new ComboBox{DisplayMemberPath="Name",MinWidth=350};Label(panel,"Ürün",product);panel.Children.Add(Button("Ürün listesini yenile",()=>product.ItemsSource=store.Products()));panel.Children.Add(Button("Kayıtlı kuralla önizle",()=>{output.Text="";if(product.SelectedItem is not CatalogProduct p)throw new InvalidOperationException("Ürün seçin.");var result=store.PreviewPrice(channel.Text,shop.Text,p.Id);output.Text=$"{p.Sku}: {result.Price} {result.Currency} — satış {result.FormulaPriceTry} TL, üstü çizili/liste {result.ListPrice} {result.Currency}. Kaydedilmemiş form değişiklikleri kullanılmaz.";}));panel.Children.Add(output);return Scroll(panel);
 }
}

