using System.Windows;
using System.Windows.Controls;
using System.Text.Json;
using TrMarketplaceHubDesktop.Catalog;

namespace TrMarketplaceHubDesktop;
public partial class MainWindow
{
 FrameworkElement BuildSync(){
  var sync=new SyncStore(dataDirectory);var automation=new AutomationStore(dataDirectory);var xmlRuns=new XmlRunStore(dataDirectory);
  var panel=new StackPanel{Margin=new Thickness(DesignTokens.SpacePage),MaxWidth=1200};panel.Children.Add(Heading("Sync ve işlem merkezi"));panel.Children.Add(Hint("Kanal, mağaza, XML, otomasyon ve hata durumlarını tek merkezde izleyin. Başarılı işler tekrar gönderilmez; retry yalnızca yeniden denenebilir hata sınıflarında açıktır."));
  var channel=new TextBox{Text="etsy",Width=120};var operation=new ComboBox{ItemsSource=new[]{"stock","price","product","order"},SelectedIndex=0,Width=120};var entity=new TextBox{Width=180};var version=new TextBox{Text="v1",Width=120};var query=new TextBox{Width=170,ToolTip="Kanal, işlem, varlık veya hata ara"};var state=new ComboBox{ItemsSource=new[]{"Tümü","Pending","Running","Succeeded","Failed"},SelectedIndex=0,Width=120};
  var grid=new DataGrid{AutoGenerateColumns=false,IsReadOnly=true,Height=300,EnableRowVirtualization=true};VirtualizingPanel.SetIsVirtualizing(grid,true);VirtualizingPanel.SetVirtualizationMode(grid,VirtualizationMode.Recycling);
  foreach(var x in new[]{("Kanal","Channel",85d),("İşlem","Operation",95d),("Varlık","EntityId",150d),("Durum","Status",90d),("Hata sınıfı","ErrorClass",110d),("Deneme","FailureCount",65d),("Son hata","LastError",260d),("Güncelleme","UpdatedUtc",155d)})grid.Columns.Add(new DataGridTextColumn{Header=x.Item1,Binding=new System.Windows.Data.Binding(x.Item2),Width=x.Item3});
  var xmlGrid=new DataGrid{AutoGenerateColumns=false,IsReadOnly=true,Height=260,EnableRowVirtualization=true};foreach(var x in new[]{("Kaynak","SourceId",160d),("Durum","Status",110d),("Başlangıç","StartedUtc",155d),("Bitiş","FinishedUtc",155d),("Yeni","Added",60d),("Güncel","Updated",60d),("Aynı","Unchanged",60d),("Hata","Error",260d)})xmlGrid.Columns.Add(new DataGridTextColumn{Header=x.Item1,Binding=new System.Windows.Data.Binding(x.Item2),Width=x.Item3});
  var autoGrid=new DataGrid{AutoGenerateColumns=true,IsReadOnly=true,Height=260,EnableRowVirtualization=true};var errors=Hint("");var status=Hint("");IReadOnlyList<SyncJob> jobs=[];
  var viewStore=new UiPreferenceStore(dataDirectory);var savedViews=new ComboBox{Width=170,DisplayMemberPath="Name"};var viewName=new TextBox{Width=135,ToolTip="Kayıtlı sync görünümü adı"};
  void Refresh(){jobs=sync.List();var q=query.Text.Trim();var selected=state.SelectedItem?.ToString()??"Tümü";grid.ItemsSource=jobs.Where(j=>(selected=="Tümü"||j.Status.ToString()==selected)&&(q.Length==0||$"{j.Channel} {j.Operation} {j.EntityId} {j.LastError} {j.ErrorClass}".Contains(q,StringComparison.CurrentCultureIgnoreCase))).ToList();xmlGrid.ItemsSource=xmlRuns.List();autoGrid.ItemsSource=automation.List();var failed=jobs.Count(x=>x.Status==SyncStatus.Failed);errors.Text=$"{jobs.Count} sync işi · {failed} hata · Yeniden denenebilir hata sınıfları: Network, Authentication, RateLimit, Unknown.";}
  void ReloadViews()=>savedViews.ItemsSource=viewStore.ListViews("sync");
  void LoadView(SavedUiView view){using var doc=JsonDocument.Parse(view.Payload);var root=doc.RootElement;channel.Text=root.GetProperty("channel").GetString()??"";operation.SelectedItem=root.GetProperty("operation").GetString()??"stock";entity.Text=root.GetProperty("entity").GetString()??"";version.Text=root.GetProperty("version").GetString()??"v1";query.Text=root.GetProperty("query").GetString()??"";state.SelectedItem=root.GetProperty("state").GetString()??"Tümü";}
  var enqueue=Button("Kuyruğa ekle",()=>{var job=sync.Enqueue(new SyncRequest(channel.Text.Trim(),operation.SelectedItem?.ToString()??"stock",entity.Text.Trim(),version.Text.Trim()));status.Text=$"Sync işi hazır: {job.Id}";Refresh();});var retry=Button("Seçili işi tekrar dene",()=>{if(grid.SelectedItem is not SyncJob job)throw new InvalidOperationException("Önce bir sync işi seçin.");sync.Retry(job.Id);status.Text="Sync işi tekrar kuyruğa alındı.";Refresh();});query.TextChanged+=(_,_)=>Refresh();state.SelectionChanged+=(_,_)=>Refresh();savedViews.SelectionChanged+=(_,_)=>{if(savedViews.SelectedItem is SavedUiView view)try{LoadView(view);}catch{status.Text="Kayıtlı görünüm okunamadı.";}};
  var row=new WrapPanel();row.Children.Add(new TextBlock{Text="Kanal",Margin=Spacing.Inline,VerticalAlignment=VerticalAlignment.Center});row.Children.Add(channel);row.Children.Add(operation);row.Children.Add(entity);row.Children.Add(version);row.Children.Add(enqueue);row.Children.Add(retry);row.Children.Add(query);row.Children.Add(state);row.Children.Add(new TextBlock{Text="Görünüm",Margin=new Thickness(8,4,2,4),VerticalAlignment=VerticalAlignment.Center});row.Children.Add(savedViews);row.Children.Add(viewName);row.Children.Add(Button("Kaydet",()=>{viewStore.SaveView("sync",viewName.Text,JsonSerializer.Serialize(new{channel=channel.Text,operation=operation.SelectedItem?.ToString()??"stock",entity=entity.Text,version=version.Text,query=query.Text,state=state.SelectedItem?.ToString()??"Tümü"}));viewName.Clear();ReloadViews();}));row.Children.Add(Button("Sil",()=>{if(savedViews.SelectedItem is not SavedUiView view)throw new InvalidOperationException("Önce görünüm seçin.");viewStore.DeleteView("sync",view.Name);ReloadViews();}));
  var dispatch=new WrapPanel();dispatch.Children.Add(Button("Seçili üründe Etsy önizlemesi",()=>CreateEtsyDispatchPreview(status)));dispatch.Children.Add(AsyncButton("Önizlemeyi açık onayla ve gönder",()=>ApproveEtsyDispatchAsync(status)));
  panel.Children.Add(row);panel.Children.Add(errors);panel.Children.Add(status);
  var tabs=new TabControl();tabs.Items.Add(new TabItem{Header="Sync işleri",Content=grid});tabs.Items.Add(new TabItem{Header="XML geçmişi",Content=xmlGrid});tabs.Items.Add(new TabItem{Header="Otomasyon işleri",Content=autoGrid});panel.Children.Add(tabs);panel.Children.Add(dispatch);ReloadViews();Refresh();return Scroll(panel);
 }
}
