using System.Windows;
using System.Windows.Controls;
using TrMarketplaceHubDesktop.Catalog;
namespace TrMarketplaceHubDesktop;
public partial class MainWindow {
 FrameworkElement BuildStockPolicies(){
  var panel=new StackPanel{Margin=new Thickness(DesignTokens.SpacePage),MaxWidth=750,HorizontalAlignment=HorizontalAlignment.Left};
  panel.Children.Add(Heading("Mağaza stok ayarları"));panel.Children.Add(Hint("Yerel katalog stoğundan mağaza güvenlik payını, üst sınırı ve aktif rezervasyonları uygular. Ürün stoğu değişmez, pazaryerine gönderim yapılmaz."));
  var channel=new TextBox{Text="etsy"};var shop=new TextBox();var safety=new TextBox{Text="0"};var maximum=new TextBox();var result=Hint("");StockPolicy? loaded=null;
  Label(panel,"Pazaryeri anahtarı (etsy, ebay, ozon…)",channel);Label(panel,"Mağaza anahtarı",shop);Label(panel,"Ek güvenlik stoğu",safety);Label(panel,"Maksimum gösterilecek stok (boş: sınırsız)",maximum);
  panel.Children.Add(Button("Ayarları yükle",()=>{loaded=store.GetStockPolicy(channel.Text,shop.Text)??new(){Channel=channel.Text.Trim().ToLowerInvariant(),Shop=shop.Text.Trim()};safety.Text=loaded.SafetyStock.ToString();maximum.Text=loaded.MaximumStock?.ToString()??"";result.Text=loaded.Version==0?"Yeni ayar; kaydedilmedi.":"Kayıtlı ayar yüklendi.";}));
  panel.Children.Add(Button("Ayarları kaydet",()=>{if(loaded==null||loaded.Channel!=channel.Text.Trim().ToLowerInvariant()||loaded.Shop!=shop.Text.Trim())throw new InvalidOperationException("Önce bu mağazanın ayarlarını yükleyin.");if(!int.TryParse(safety.Text,out var n)||n<0)throw new InvalidOperationException("Güvenlik stoğu negatif olmayan tam sayı olmalı.");int? cap=null;if(!string.IsNullOrWhiteSpace(maximum.Text)){if(!int.TryParse(maximum.Text,out var c)||c<0)throw new InvalidOperationException("Üst sınır negatif olmayan tam sayı olmalı.");cap=c;}loaded=store.SaveStockPolicy(new(){Channel=loaded.Channel,Shop=loaded.Shop,Version=loaded.Version,SafetyStock=n,MaximumStock=cap});result.Text="Mağaza stok politikası kaydedildi. Dış gönderim yapılmadı.";}));
  var product=new ComboBox{DisplayMemberPath="Name",MinWidth=350};Label(panel,"Önizlenecek ürün",product);panel.Children.Add(Button("Ürün listesini yenile",()=>product.ItemsSource=store.Products()));
  panel.Children.Add(Button("Kayıtlı ayarla stok önizle",()=>{if(product.SelectedItem is not CatalogProduct p)throw new InvalidOperationException("Ürün listesini yenileyip ürün seçin.");var projection=store.ProjectStock(channel.Text,shop.Text,p.Id,DateTime.UtcNow);result.Text=$"{p.Sku} → gösterilebilir stok: {projection.Available} · kaynak stoku: {projection.State} · {projection.Words} · çoklu kaynak: {store.AggregateStock(p.Id,DateTime.UtcNow).Words}. Kaydedilmemiş form değişiklikleri kullanılmaz."; /* #932; #935 */}));
  // #933: safety buffer profiles -- for a product, a source or a store, effective from a date; the most specific one in force wins over the policy's safety stock; profiles of one scope never overlap.
  var buffers=new SafetyBufferProfileStore(dataDirectory);var bufferScope=new ComboBox{ItemsSource=SafetyBufferProfile.Scopes,SelectedIndex=2};var bufferScopeId=new TextBox();var bufferUnits=new TextBox{Text="0"};var bufferFrom=new TextBox();var bufferTo=new TextBox();var bufferNote=new TextBox();var bufferGrid=new DataGrid{AutoGenerateColumns=true,IsReadOnly=true,Height=160,EnableRowVirtualization=true};
  static DateTime BufferUtc(string text){if(!DateTimeOffset.TryParse(text,System.Globalization.CultureInfo.InvariantCulture,System.Globalization.DateTimeStyles.AssumeUniversal,out var parsed))throw new InvalidOperationException("Profil tarihi geçersiz; ISO biçimi kullanın (örn. 2026-10-01T00:00:00Z).");return parsed.UtcDateTime;}
  panel.Children.Add(Hint("Güvenlik tamponu profilleri: ürün, kaynak ya da mağaza için tarihli tampon; en özel olan geçerlidir (ürün > kaynak > mağaza > politika). Kapsam kimliği: ürün için ürün kimliği, kaynak için kaynak kimliği, mağaza için pazaryeri/mağaza (örn. etsy/S1). Aynı kapsamda çakışan dönem reddedilir."));
  Label(panel,"Tampon kapsamı",bufferScope);Label(panel,"Kapsam kimliği",bufferScopeId);Label(panel,"Tampon (adet; 0 = tampon yok)",bufferUnits);Label(panel,"Geçerlilik başlangıcı (ISO UTC)",bufferFrom);Label(panel,"Geçerlilik bitişi (ISO UTC; boş = açık)",bufferTo);Label(panel,"Profil notu",bufferNote);
  panel.Children.Add(Button("Tampon profili kaydet",()=>{if(!int.TryParse(bufferUnits.Text,System.Globalization.NumberStyles.Integer,System.Globalization.CultureInfo.InvariantCulture,out var units))throw new InvalidOperationException("Tampon tam sayı olmalı.");var saved=buffers.Save(bufferScope.SelectedItem?.ToString()??"store",bufferScopeId.Text,units,BufferUtc(bufferFrom.Text),string.IsNullOrWhiteSpace(bufferTo.Text)?null:BufferUtc(bufferTo.Text),bufferNote.Text,DateTime.UtcNow);bufferGrid.ItemsSource=buffers.List();result.Text=$"Tampon profili kaydedildi: {saved.Scope} {saved.ScopeId} → {saved.Buffer} adet, {saved.Period}.";}));
  panel.Children.Add(Button("Tampon profillerini listele",()=>bufferGrid.ItemsSource=buffers.List()));panel.Children.Add(bufferGrid);
  // #936: the stock fallback -- which source would stand in for the selected product's stale stock, and the operator's approval of it, bound to that source's configuration revision; nothing switches by itself.
  var fallbackSource=new TextBox();panel.Children.Add(Hint("Yedek stok: kayıtlı stok bayatken uygun yedek kaynağın taze stoku ancak onayınızla kullanılır; onay kaynağın yapılandırma revizyonuna bağlıdır, kaynak düzenlenince düşer. Eşit öncelikli adaylarda kaynak kimliğini yazın."));Label(panel,"Yedek kaynak kimliği (boş: seçilen aday)",fallbackSource);
  panel.Children.Add(Button("Yedek stok seçimini göster",()=>{if(product.SelectedItem is not CatalogProduct p)throw new InvalidOperationException("Ürün listesini yenileyip ürün seçin.");var selection=store.SelectFallbackStock(p.Id,DateTime.UtcNow);result.Text=$"{p.Sku} → yedek stok: {selection.Status} · {selection.Words}";}));
  panel.Children.Add(Button("Yedek stoku onayla (kaynak revizyonuna bağlı)",()=>{if(product.SelectedItem is not CatalogProduct p)throw new InvalidOperationException("Ürün listesini yenileyip ürün seçin.");var sourceId=string.IsNullOrWhiteSpace(fallbackSource.Text)?store.SelectFallbackStock(p.Id,DateTime.UtcNow).Selected?.SourceId:fallbackSource.Text.Trim();if(string.IsNullOrEmpty(sourceId))throw new InvalidOperationException("Onaylanacak yedek kaynak yok; eşit adaylarda kaynak kimliğini yazın.");var approval=store.ApproveFallbackStock(p.Id,sourceId,"",DateTime.UtcNow);result.Text=$"{p.Sku} → yedek onaylandı: kaynak rev {approval.SourceRevision}. Kaynak yapılandırması değişirse onay düşer. Dış gönderim yapılmadı.";}));
  panel.Children.Add(Button("Yedek onayını kaldır",()=>{if(product.SelectedItem is not CatalogProduct p)throw new InvalidOperationException("Ürün listesini yenileyip ürün seçin.");result.Text=store.RevokeFallbackStock(p.Id,DateTime.UtcNow)?$"{p.Sku} → yedek onayı kaldırıldı.":$"{p.Sku} → yedek onayı yoktu.";}));
  // #937: reservations -- units held for an order on this store until an expiry or a release; the projection subtracts the active ones; the aging report says which deserve a look.
  var reserveOrder=new TextBox();var reserveQty=new TextBox{Text="1"};var reserveHours=new TextBox{Text="48"};var releaseId=new TextBox();var releaseReason=new TextBox();var reservationGrid=new DataGrid{AutoGenerateColumns=true,IsReadOnly=true,Height=180,EnableRowVirtualization=true};
  panel.Children.Add(Hint("Rezervasyon: seçili ürünün formdaki mağazası için sipariş adedi tutar; süre boş bırakılırsa süresizdir. Gösterilebilir stoktan düşülür. Serbest bırakma gerekçe ister."));Label(panel,"Rezervasyon sipariş numarası (boş: elle)",reserveOrder);Label(panel,"Rezervasyon adedi",reserveQty);Label(panel,"Rezervasyon süresi (saat; boş: süresiz)",reserveHours);
  panel.Children.Add(Button("Rezervasyon oluştur (seçili ürün, formdaki mağaza)",()=>{if(product.SelectedItem is not CatalogProduct p)throw new InvalidOperationException("Ürün listesini yenileyip ürün seçin.");if(!int.TryParse(reserveQty.Text,System.Globalization.NumberStyles.Integer,System.Globalization.CultureInfo.InvariantCulture,out var qty))throw new InvalidOperationException("Rezervasyon adedi tam sayı olmalı.");TimeSpan? ttl=null;if(!string.IsNullOrWhiteSpace(reserveHours.Text)){if(!double.TryParse(reserveHours.Text,System.Globalization.NumberStyles.Float,System.Globalization.CultureInfo.InvariantCulture,out var hours)||hours<=0)throw new InvalidOperationException("Rezervasyon süresi pozitif saat olmalı.");ttl=TimeSpan.FromHours(hours);}var r=store.Reserve(p.Id,channel.Text,shop.Text,reserveOrder.Text,qty,DateTime.UtcNow,ttl);result.Text=$"Rezervasyon #{r.Id} oluşturuldu: {r.Sku} · {r.StoreKey} · {r.Quantity} adet · {(r.ExpiresUtc is null?"süresiz":"bitiş "+SafetyBufferProfile.Stamp(r.ExpiresUtc.Value))}. Dış gönderim yapılmadı.";}));
  Label(panel,"Serbest bırakılacak rezervasyon numarası",releaseId);Label(panel,"Serbest bırakma gerekçesi",releaseReason);
  panel.Children.Add(Button("Rezervasyonu serbest bırak",()=>{if(!long.TryParse(releaseId.Text,System.Globalization.NumberStyles.Integer,System.Globalization.CultureInfo.InvariantCulture,out var id))throw new InvalidOperationException("Rezervasyon numarası gerekli.");var r=new StockReservationStore(dataDirectory).Release(id,releaseReason.Text,DateTime.UtcNow);result.Text=$"Rezervasyon #{r.Id} serbest bırakıldı ({r.ReleaseReason}).";}));
  panel.Children.Add(Button("Rezervasyon yaşlandırma raporu",()=>{var report=store.ReservationAging(DateTime.UtcNow);reservationGrid.ItemsSource=report.Rows.Select(r=>new{r.Id,r.Sku,Mağaza=r.StoreKey,Sipariş=r.OrderId,SiparişDurumu=r.OrderState,Adet=r.Quantity,Durum=r.State,Yaş=r.AgeBucket,StokEtkisi=r.StockImpactPercent,Bayat=r.Stale,Açıklama=r.Words}).ToList();result.Text=report.Headline+(report.Stale>0?" Bayat: "+string.Join(" | ",report.StaleRows.Select(r=>"#"+r.Id+" "+string.Join("; ",r.Reasons))):"");}));
  panel.Children.Add(Button("Yalnızca bayat rezervasyonlar",()=>{var report=store.ReservationAging(DateTime.UtcNow);reservationGrid.ItemsSource=report.StaleRows.Select(r=>new{r.Id,r.Sku,Mağaza=r.StoreKey,Sipariş=r.OrderId,SiparişDurumu=r.OrderState,Adet=r.Quantity,Durum=r.State,Yaş=r.AgeBucket,StokEtkisi=r.StockImpactPercent,Açıklama=r.Words}).ToList();result.Text=report.Stale==0?"Bayat rezervasyon yok.":$"{report.Stale} bayat rezervasyon listelendi.";}));panel.Children.Add(reservationGrid);
  panel.Children.Add(result);return Scroll(panel);
 }
}
