using System.Globalization;
using System.Windows;
using System.Windows.Controls;
using TrMarketplaceHubDesktop.Catalog;
namespace TrMarketplaceHubDesktop;
public partial class MainWindow {
 FrameworkElement BuildPricePolicies(){
 var panel=new StackPanel{Margin=new Thickness(DesignTokens.SpacePage),MaxWidth=800,HorizontalAlignment=HorizontalAlignment.Left};panel.Children.Add(Heading("Mağaza fiyat kuralları"));panel.Children.Add(Hint("Alış fiyatı TL olan ürünlerde x alış fiyatıdır. CASE formülü TL sonuç üretir, hedef dövize çevrilir. Kayıtlı kuralla önizleme ürün fiyatını değiştirmez ve pazaryerine göndermez."));
 var channel=new TextBox{Text="etsy"};var shop=new TextBox();var formula=new TextBox{Text="x",Height=110,AcceptsReturn=true,TextWrapping=TextWrapping.Wrap};var currency=new ComboBox{ItemsSource=new[]{"TRY","USD","EUR","GBP"},SelectedIndex=0};var rate=new TextBox{Text="1"};var observed=new TextBox();var minimum=new TextBox{Text="0"};var margin=new TextBox{Text="0"};var enabled=new CheckBox{Content="Kural aktif",IsChecked=true};var output=Hint("");PricePolicy? loaded=null;
 var commission=new TextBox();var shipping=new TextBox();var transactionCost=new TextBox();var vatRate=new TextBox();var vatIncluded=new CheckBox{Content="KDV satış fiyatına dahil"};
 Label(panel,"Pazaryeri",channel);Label(panel,"Mağaza anahtarı",shop);Label(panel,"Fiyat formülü",formula);Label(panel,"Satış dövizi",currency);Label(panel,"1 dövizin TL karşılığı (manuel kur)",rate);Label(panel,"Kur gözlem tarihi (ISO, örn. 2026-09-11T09:00:00+03:00; TRY kural için gerekmez)",observed);Label(panel,"Minimum satış fiyatı (hedef döviz)",minimum);Label(panel,"Alış üstü minimum fark (TL; net kâr değildir)",margin);panel.Children.Add(enabled);
 panel.Children.Add(Hint("Aşağıdaki masraf alanları boş bırakılırsa kural fiyat üretmez (bilinmeyen komisyon/kargo/KDV asla 0 kabul edilmez, dispatch engellenir)."));
 Label(panel,"Komisyon oranı (%, satış tutarı üzerinden)",commission);Label(panel,"Tahmini kargo (TL)",shipping);Label(panel,"İşlem/ödeme maliyeti (TL)",transactionCost);Label(panel,"KDV oranı (%)",vatRate);panel.Children.Add(vatIncluded);
 // #923: dated commission periods per channel/shop -- immutable revisions, no overlaps, a gap refuses the price; the period in force overrides the rule's flat rate above.
 var periods=new CommissionProfileStore(dataDirectory);var periodFrom=new TextBox();var periodTo=new TextBox();var periodPercent=new TextBox();var periodFee=new TextBox{Text="0"};var periodNote=new TextBox();var periodGrid=new DataGrid{AutoGenerateColumns=true,IsReadOnly=true,Height=180,EnableRowVirtualization=true};
 void RefreshPeriods(){periodGrid.ItemsSource=periods.List(channel.Text,shop.Text);}
 static DateTime PeriodUtc(string text){if(!DateTimeOffset.TryParse(text,CultureInfo.InvariantCulture,DateTimeStyles.AssumeUniversal,out var parsed))throw new InvalidOperationException("Dönem tarihi geçersiz; ISO biçimi kullanın (örn. 2026-10-01T00:00:00Z).");return parsed.UtcDateTime;}
 panel.Children.Add(Hint("Komisyon dönemleri: tarihli bir dönem tanımlıysa o dönemin oranı ve sabit ücreti geçerlidir. Dönemler değiştirilmez; kapatma yeni bir sürüm yazar. Çakışan dönem reddedilir; dönemler arasındaki boşlukta fiyat üretilmez."));
 Label(panel,"Dönem başlangıcı (ISO UTC, örn. 2026-10-01T00:00:00Z)",periodFrom);Label(panel,"Dönem bitişi (ISO UTC; boş = açık uçlu; kapatmada da kullanılır)",periodTo);Label(panel,"Dönem komisyonu (%)",periodPercent);Label(panel,"Dönem sabit ücreti (TL)",periodFee);Label(panel,"Dönem notu",periodNote);
 panel.Children.Add(Button("Komisyon dönemi ekle",()=>{var saved=periods.Save(channel.Text,shop.Text,PeriodUtc(periodFrom.Text),string.IsNullOrWhiteSpace(periodTo.Text)?null:PeriodUtc(periodTo.Text),Number(periodPercent.Text),Number(periodFee.Text),periodNote.Text,DateTime.UtcNow);RefreshPeriods();output.Text=$"Komisyon dönemi kaydedildi: sürüm {saved.Revision}, {saved.Period}. Canlı fiyat değişmedi.";}));
 panel.Children.Add(Button("Seçili dönemi bitiş tarihinde kapat",()=>{if(periodGrid.SelectedItem is not CommissionProfile selected)throw new InvalidOperationException("Önce dönem listesinden seçim yapın.");var closed=periods.Close(channel.Text,shop.Text,selected.Revision,PeriodUtc(periodTo.Text),DateTime.UtcNow);RefreshPeriods();output.Text=$"Dönem kapatıldı: sürüm {selected.Revision} → {closed.Revision}, {closed.Period}.";}));
 panel.Children.Add(Button("Dönemleri listele",RefreshPeriods));panel.Children.Add(periodGrid);
 // #924: the operator's FX staleness policy for this channel/shop -- how old the observed rate may be and whether a staler one blocks the manual preview or only warns; an automatic live write is blocked on a stale rate in every mode.
 var fxPolicies=new FxStalenessPolicyStore(dataDirectory);FxStalenessPolicy? fxLoaded=null;var fxHours=new TextBox{Text="24"};var fxMode=new ComboBox{ItemsSource=new[]{FxStalenessPolicy.Block,FxStalenessPolicy.Warn},SelectedIndex=0};
 panel.Children.Add(Hint("Kur bayatlık politikası: gözlem tarihi eşikten eski bir kur elle önizlemede BLOCK ile reddedilir, WARN ile uyarıyla hesaplanır. Otomatik canlı yazım bayat kurla hiçbir zaman yapılmaz; kur tarihi yoksa fiyat üretilmez."));
 Label(panel,"Kur bayatlık eşiği (saat, 1-168)",fxHours);Label(panel,"Bayat kurda elle önizleme (BLOCK = engelle, WARN = uyar)",fxMode);
 panel.Children.Add(Button("Kur politikasını yükle",()=>{fxLoaded=fxPolicies.Get(channel.Text,shop.Text);fxHours.Text=fxLoaded.StaleAfterHours.ToString(CultureInfo.InvariantCulture);fxMode.SelectedItem=fxLoaded.Mode;output.Text=fxLoaded.IsDefault?"Varsayılan kur politikası (24 saat, BLOCK); kaydedilmedi.":"Kur politikası yüklendi.";}));
 panel.Children.Add(Button("Kur politikasını kaydet",()=>{if(fxLoaded==null||fxLoaded.Channel!=channel.Text.Trim().ToLowerInvariant()||fxLoaded.Shop!=shop.Text.Trim())throw new InvalidOperationException("Önce mağazanın kur politikasını yükleyin.");if(!int.TryParse(fxHours.Text,NumberStyles.Integer,CultureInfo.InvariantCulture,out var hours))throw new InvalidOperationException("Eşik saat tam sayı olmalı.");fxLoaded=fxPolicies.Save(new FxStalenessPolicy{Channel=fxLoaded.Channel,Shop=fxLoaded.Shop,Version=fxLoaded.Version,StaleAfterHours=hours,Mode=fxMode.SelectedItem?.ToString()??FxStalenessPolicy.Block});output.Text=$"Kur politikası kaydedildi: {fxLoaded.StaleAfterHours} saat, {fxLoaded.Mode}. Canlı fiyat değişmedi.";}));
 static decimal Number(string text){if(!decimal.TryParse(text,NumberStyles.AllowDecimalPoint|NumberStyles.AllowLeadingSign,CultureInfo.InvariantCulture,out var n))throw new InvalidOperationException("Ondalık ayırıcı olarak nokta kullanın.");return n;}
 static decimal? OptionalNumber(string text)=>string.IsNullOrWhiteSpace(text)?null:Number(text);
 panel.Children.Add(Button("Kuralı yükle",()=>{loaded=store.GetPricePolicy(channel.Text,shop.Text)??new(){Channel=channel.Text.Trim().ToLowerInvariant(),Shop=shop.Text.Trim()};formula.Text=loaded.Formula;currency.SelectedItem=loaded.Currency;rate.Text=loaded.TryPerUnit.ToString(CultureInfo.InvariantCulture);observed.Text=loaded.FxRateObservedUtc?.ToString("O")??"";minimum.Text=loaded.MinimumPrice.ToString(CultureInfo.InvariantCulture);margin.Text=loaded.MinimumMarginTry.ToString(CultureInfo.InvariantCulture);enabled.IsChecked=loaded.Enabled;commission.Text=loaded.CommissionPercent?.ToString(CultureInfo.InvariantCulture)??"";shipping.Text=loaded.EstimatedShippingTry?.ToString(CultureInfo.InvariantCulture)??"";transactionCost.Text=loaded.TransactionCostTry?.ToString(CultureInfo.InvariantCulture)??"";vatRate.Text=loaded.VatRatePercent?.ToString(CultureInfo.InvariantCulture)??"";vatIncluded.IsChecked=loaded.VatIncludedInSale;output.Text=loaded.Version==0?"Yeni kural; kaydedilmedi.":"Kural yüklendi.";}));
 panel.Children.Add(Button("Kuralı kaydet",()=>{if(loaded==null||loaded.Channel!=channel.Text.Trim().ToLowerInvariant()||loaded.Shop!=shop.Text.Trim())throw new InvalidOperationException("Önce mağazanın kuralını yükleyin.");DateTimeOffset? time=null;if(!string.IsNullOrWhiteSpace(observed.Text)){if(!DateTimeOffset.TryParse(observed.Text,CultureInfo.InvariantCulture,DateTimeStyles.None,out var parsed))throw new InvalidOperationException("Kur tarihi geçersiz.");time=parsed;}loaded=store.SavePricePolicy(new(){Channel=loaded.Channel,Shop=loaded.Shop,Version=loaded.Version,Formula=formula.Text,Currency=currency.SelectedItem?.ToString()??"",TryPerUnit=Number(rate.Text),MinimumPrice=Number(minimum.Text),MinimumMarginTry=Number(margin.Text),Enabled=enabled.IsChecked==true,CommissionPercent=OptionalNumber(commission.Text),EstimatedShippingTry=OptionalNumber(shipping.Text),TransactionCostTry=OptionalNumber(transactionCost.Text),VatRatePercent=OptionalNumber(vatRate.Text),VatIncludedInSale=vatIncluded.IsChecked==true,FxRateObservedUtc=time});output.Text="Fiyat kuralı kaydedildi. Canlı fiyat değişmedi.";}));
 var product=new ComboBox{DisplayMemberPath="Name",MinWidth=350};Label(panel,"Ürün",product);panel.Children.Add(Button("Ürün listesini yenile",()=>product.ItemsSource=store.Products()));panel.Children.Add(Button("Kayıtlı kuralla önizle",()=>{output.Text="";if(product.SelectedItem is not CatalogProduct p)throw new InvalidOperationException("Ürün seçin.");var result=store.PreviewPrice(channel.Text,shop.Text,p.Id);output.Text=$"{p.Sku}: {result.Price} {result.Currency} — formül sonucu {result.FormulaPriceTry} TL. Alış kökeni: {result.CostOrigin}. Komisyon: {result.CommissionOrigin}.{(result.FxWarning.Length>0?" ⚠ "+result.FxWarning+".":"")} Kaydedilmemiş form değişiklikleri kullanılmaz.";}));panel.Children.Add(output);return Scroll(panel);
 }
}

