using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Media;

namespace TrMarketplaceHubDesktop;

public static class OnboardingPanel
{
    public static void ShowWizard(Window owner, string? directory, Action<string> navigate)
    {
        var window = new Window { Owner = owner, Title = "MonoBridge ilk kurulum", Width = 980, Height = 720, MinWidth = 820, MinHeight = 600, WindowStartupLocation = WindowStartupLocation.CenterOwner, ResizeMode = ResizeMode.CanResize }; var close = new Action(() => window.Close()); window.Content = Create(directory, navigate, close); window.ShowDialog();
    }

    public static FrameworkElement Create(string? directory, Action<string>? navigate = null, Action? close = null)
    {
        var setup = new OnboardingSetupService(directory); var stateStore = new OnboardingStore(directory); var statusService = new OnboardingStatusService(directory); var root = new DockPanel { Margin = new Thickness(18) }; var top = new DockPanel(); DockPanel.SetDock(top, Dock.Top); root.Children.Add(top); var heading = Text("İlk kurulum sihirbazı", 24); top.Children.Add(heading); var skip = Button("Şimdilik atla", () => { stateStore.Skip(); close?.Invoke(); }); DockPanel.SetDock(skip, Dock.Right); top.Children.Add(skip);
        var help = Text("Her adım yalnız yerel ayar, önizleme veya salt-okunur test hazırlar. Canlı marketplace write yapılmaz; credential alanları bu sihirbazda tutulmaz."); DockPanel.SetDock(help, Dock.Top); root.Children.Add(help);
        var tabs = new TabControl(); root.Children.Add(tabs); var status = Text(""); DockPanel.SetDock(status, Dock.Bottom); root.Children.Add(status); var channel = new TextBox { Text = stateStore.Get().Channel, Width = 120 }; var shop = new TextBox { Text = stateStore.Get().ShopId, Width = 130 }; var display = new TextBox { Text = "Mağazam", Width = 220 }; DataGrid? summaryGrid = null;
        void Complete(string step, string message) { var current = stateStore.Get(); current.Channel = channel.Text.Trim().ToLowerInvariant(); current.ShopId = shop.Text.Trim(); current.CurrentStep = step; current.CompletedSteps.Add(step); stateStore.Save(current); status.Text = message; Refresh(); }
        var storePanel = new StackPanel(); storePanel.Children.Add(Text("1 · Kanal ve mağaza", 18)); AddField(storePanel, "Kanal (etsy/ebay/...)", channel); AddField(storePanel, "Mağaza kimliği", shop); AddField(storePanel, "Görünen ad", display); storePanel.Children.Add(Button("Mağaza metadata'sını kaydet", () => { setup.SaveStore(channel.Text, shop.Text, display.Text); Complete("store", "Mağaza metadata'sı kaydedildi. API durumu canlı write anlamına gelmez."); })); storePanel.Children.Add(Text("Erişim anahtarı/secret bu ekranda saklanmaz; ilgili kanalın mevcut CredentialStore bağlantı ekranını kullanın.")); tabs.Items.Add(new TabItem { Header = "Mağaza", Content = storePanel });
        var xmlName = new TextBox { Text = "Tedarikçi XML", Width = 220 }; var xmlLocation = new TextBox { Width = 520 }; var xmlPanel = new StackPanel(); xmlPanel.Children.Add(Text("2 · XML tedarikçi", 18)); AddField(xmlPanel, "Kaynak adı", xmlName); AddField(xmlPanel, "URL veya yerel dosya", xmlLocation); xmlPanel.Children.Add(Button("Kaydet ve XML ekranına geç", () => { var source = setup.SaveXml(xmlName.Text, xmlLocation.Text); Complete("xml", $"XML kaynağı {source.Name} olarak kaydedildi. Alan eşlemeyi XML yönetiminde önizleyin."); })); tabs.Items.Add(new TabItem { Header = "XML", Content = xmlPanel });
        var stockChannel = new TextBox { Text = channel.Text, Width = 120 }; var stockShop = new TextBox { Text = shop.Text, Width = 130 }; var safety = new TextBox { Text = "3", Width = 70 }; var maximum = new TextBox { Text = "20", Width = 70 }; var stockPanel = new StackPanel(); stockPanel.Children.Add(Text("3 · Varsayılan stok politikası", 18)); AddField(stockPanel, "Kanal", stockChannel); AddField(stockPanel, "Mağaza", stockShop); AddField(stockPanel, "Güvenlik stoğu", safety); AddField(stockPanel, "Maksimum stok (boş = sınırsız)", maximum); stockPanel.Children.Add(Button("Stok politikasını kaydet", () => { if (!int.TryParse(safety.Text, out var safe) || safe < 0 || (!string.IsNullOrWhiteSpace(maximum.Text) && (!int.TryParse(maximum.Text, out var max) || max < 0))) throw new InvalidOperationException("Stok değerlerini kontrol edin."); int? maxValue = string.IsNullOrWhiteSpace(maximum.Text) ? null : int.Parse(maximum.Text); setup.SaveStock(stockChannel.Text, stockShop.Text, safe, maxValue); channel.Text = stockChannel.Text; shop.Text = stockShop.Text; Complete("stock", "Stok politikası hazırlandı; canlı stok gönderimi yapılmadı."); })); tabs.Items.Add(new TabItem { Header = "Stok", Content = stockPanel });
        var priceChannel = new TextBox { Text = channel.Text, Width = 120 }; var priceShop = new TextBox { Text = shop.Text, Width = 130 }; var formula = new TextBox { Text = "x", Width = 180 }; var currency = new ComboBox { ItemsSource = LocaleSettings.SupportedCurrencies.ToArray(), SelectedItem = "TRY", Width = 90 }; var rate = new TextBox { Text = "1", Width = 80 }; var pricePanel = new StackPanel(); pricePanel.Children.Add(Text("4 · Varsayılan fiyat politikası", 18)); AddField(pricePanel, "Kanal", priceChannel); AddField(pricePanel, "Mağaza", priceShop); AddField(pricePanel, "Formül (x = maliyet)", formula); AddField(pricePanel, "Hedef döviz", currency); AddField(pricePanel, "1 hedef döviz / TL", rate); pricePanel.Children.Add(Button("Fiyat politikasını kaydet", () => { if (!decimal.TryParse(rate.Text, System.Globalization.NumberStyles.Number, System.Globalization.CultureInfo.InvariantCulture, out var exchange) || exchange <= 0) throw new InvalidOperationException("Kur 0'dan büyük olmalı."); setup.SavePrice(priceChannel.Text, priceShop.Text, formula.Text, currency.SelectedItem?.ToString() ?? "TRY", exchange); channel.Text = priceChannel.Text; shop.Text = priceShop.Text; Complete("price", "Fiyat formülü hazırlandı; canlı fiyat gönderimi yapılmadı."); })); tabs.Items.Add(new TabItem { Header = "Fiyat", Content = pricePanel });
        var excelName = new TextBox { Text = "Başlangıç Excel profili", Width = 260 }; var excelPanel = new StackPanel(); excelPanel.Children.Add(Text("5 · Excel başlangıç profili", 18)); AddField(excelPanel, "Profil adı", excelName); excelPanel.Children.Add(Button("Profili oluştur", () => { setup.SaveExcelProfile(excelName.Text); Complete("excel", "Excel profili hazırlandı; dosya içe aktarımı önizleme gerektirir."); })); tabs.Items.Add(new TabItem { Header = "Excel", Content = excelPanel });
        summaryGrid = new DataGrid { AutoGenerateColumns = false, IsReadOnly = true, Height = 300 }; foreach (var c in new[] { ("Adım", "Title", 190d), ("Durum", "State", 150d), ("Açıklama", "Detail", 500d) }) summaryGrid.Columns.Add(new DataGridTextColumn { Header = c.Item1, Binding = new Binding(c.Item2), Width = c.Item3 }); var summaryPanel = new StackPanel(); summaryPanel.Children.Add(Text("Kurulum özeti", 18)); summaryPanel.Children.Add(summaryGrid); var links = new WrapPanel(); foreach (var pair in new[] { ("Mağazalar", "connections"), ("XML", "xml"), ("Ürünler", "products"), ("Stok", "stock-policies"), ("Fiyat", "price-policies"), ("Excel", "excel"), ("Sağlık", "diagnostics") }) { var route = pair.Item2; links.Children.Add(Button(pair.Item1, () => { close?.Invoke(); navigate?.Invoke(route); })); } summaryPanel.Children.Add(links); summaryPanel.Children.Add(Button("Kurulumu tamamla", () => { stateStore.Complete("complete"); status.Text = "Kurulum tamamlandı. İstediğiniz zaman Ayarlar / ilgili modüllerden devam edebilirsiniz."; close?.Invoke(); })); tabs.Items.Add(new TabItem { Header = "Özet", Content = summaryPanel });
        void Refresh() { var summary = statusService.Build(channel.Text, shop.Text); summaryGrid!.ItemsSource = summary.Steps; heading.Text = $"İlk kurulum sihirbazı · {summary.Completed}/{summary.Total} hazır"; }
        var resume = stateStore.Get().CurrentStep; tabs.SelectedIndex = resume switch { "xml" => 1, "stock" => 2, "price" => 3, "excel" => 4, "complete" => 5, _ => 0 }; Refresh(); return root;
    }
    static void AddField(Panel panel, string label, Control control) { panel.Children.Add(new TextBlock { Text = label, Margin = new Thickness(4, 10, 2, 2), Foreground = Brushes.DarkSlateGray }); panel.Children.Add(control); }
    static TextBlock Text(string value, int size = 12) => new() { Text = value, FontSize = size, TextWrapping = TextWrapping.Wrap, Margin = new Thickness(3, 4, 3, 8), Foreground = Brushes.DarkSlateGray };
    static Button Button(string text, Action action) { var button = new Button { Content = text, Margin = new Thickness(3) }; button.Click += (_, _) => { try { action(); } catch (Exception error) { MessageBox.Show(MarketplaceConnectionStore.Redact(error.Message), "İlk kurulum", MessageBoxButton.OK, MessageBoxImage.Warning); } }; return button; }
}
