using TrMarketplaceHubDesktop.Catalog;
using System.Diagnostics;
using System.Net.Http;
using System.Text.Json;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Media;
namespace TrMarketplaceHubDesktop;
public static class OrdersPanel
{
 public static FrameworkElement Create(string? directory=null,Func<Task<EtsyCredentials>>? authorize=null,Action? catalogChanged=null,Action<Func<string,string,string,bool>>? exposeReveal=null)
 {
  var store=new OrdersStore(directory);var catalog=new CatalogStore(directory);var root=new DockPanel{Margin=Spacing.Section};var top=new StackPanel();DockPanel.SetDock(top,Dock.Top);root.Children.Add(top);
  top.Children.Add(Text("Siparişler ve kargo takibi",TextRole.SectionTitle));
  top.Children.Add(Text("Etsy siparişleri salt okunur alınır. Yolda / teslim edildi gözlemleri yerel olarak kaydedilir. Ozon ve Navlungo otomatik takip bağlantısı henüz yok."));
  var bar=new WrapPanel();top.Children.Add(bar);var search=new TextBox{Width=220,ToolTip="Sipariş, mağaza, ürün, SKU veya takip numarası ara"};bar.Children.Add(search);
  var filter=new ComboBox{Width=170,ItemsSource=new[]{"Tümü"}.Concat(OrdersRules.States.Select(OrdersRules.Label)).ToArray(),SelectedIndex=0};bar.Children.Add(filter);
  var marketplaceFilter=new ComboBox{Width=130,ItemsSource=new[]{"Tümü"},SelectedIndex=0};bar.Children.Add(marketplaceFilter);
  var shopFilter=new ComboBox{Width=140,ItemsSource=new[]{"Tümü"},SelectedIndex=0};bar.Children.Add(shopFilter);
  var stockFilter=new ComboBox{Width=145,ItemsSource=new[]{"Tümü","Stok düşüldü","Stok bekliyor"},SelectedIndex=0};bar.Children.Add(stockFilter);
  // #835: urgency from recorded states -- a band filter and a deterministic sort (score, then key).
  var urgencyFilter=new ComboBox{Width=150,ToolTip="Aciliyet bandı",ItemsSource=new[]{"Aciliyet: Tümü"}.Concat(OrderUrgencyScorer.BandOptions.Select(b=>b.Label)).ToArray(),SelectedIndex=0};System.Windows.Automation.AutomationProperties.SetName(urgencyFilter,"Aciliyet bandı");bar.Children.Add(urgencyFilter);
  var urgencySort=new CheckBox{Content="Aciliyete göre sırala",IsChecked=true,VerticalAlignment=VerticalAlignment.Center,Margin=new Thickness(6,0,0,0)};System.Windows.Automation.AutomationProperties.SetName(urgencySort,"Aciliyete göre sırala");bar.Children.Add(urgencySort);
  var viewStore=new UiPreferenceStore(directory);var savedViews=new ComboBox{Width=165,DisplayMemberPath="Name"};var viewName=new TextBox{Width=130,ToolTip="Kayıtlı sipariş görünümü adı"};bar.Children.Add(new TextBlock{Text="Görünüm",Margin=new Thickness(8,4,2,4),VerticalAlignment=VerticalAlignment.Center});bar.Children.Add(savedViews);bar.Children.Add(viewName);
  // #834: column presets built from the grid's real columns; the user's own layout is kept apart and never overwritten by a preset.
  var presetController=new OrderColumnPresetController(viewStore.Get,viewStore.Set);var columnPreset=new ComboBox{Width=150,ToolTip="Kolon ön ayarı: operasyon, kargo, finans (salt okunur) veya kendi düzenin",ItemsSource=OrderColumnPresets.Options.Select(o=>o.Label).ToList()};System.Windows.Automation.AutomationProperties.SetName(columnPreset,"Kolon ön ayarı");bar.Children.Add(new TextBlock{Text="Kolonlar",Margin=new Thickness(8,4,2,4),VerticalAlignment=VerticalAlignment.Center});bar.Children.Add(columnPreset);
  var refresh=Button(bar,"Etsy'den yenile");var cancel=Button(bar,"İptal");cancel.IsEnabled=false;var add=Button(bar,"+ Yerel sipariş");
  var status=Text("Kayıtlar yükleniyor…");top.Children.Add(status);
  var layout=new Grid{Tag="order-split"};root.Children.Add(layout);
  // #836: a resizable split whose detail width is remembered in DIP and clamped to the workspace; below 900 DIP the detail stacks under the list.
  var detailWidth=OrderWorkspaceLayout.Deserialize(viewStore.Get(OrderWorkspaceLayout.SplitPreferenceKey));var splitter=new GridSplitter{Width=6,HorizontalAlignment=HorizontalAlignment.Stretch,VerticalAlignment=VerticalAlignment.Stretch,Background=SystemColors.ControlLightBrush,Focusable=true,KeyboardIncrement=16,ToolTip="Liste ile ayrıntı arasındaki bölmeyi sürükle (ok tuşları da çalışır)"};System.Windows.Automation.AutomationProperties.SetName(splitter,"Liste ve ayrıntı bölmesi");
  var workspaceMode=OrderWorkspaceMode.SideBySide;
  var grid=new DataGrid{IsReadOnly=true,AutoGenerateColumns=false,EnableRowVirtualization=true,EnableColumnVirtualization=false,SelectionMode=DataGridSelectionMode.Single};VirtualizingPanel.SetIsVirtualizing(grid,true);VirtualizingPanel.SetVirtualizationMode(grid,VirtualizationMode.Recycling);ScrollViewer.SetCanContentScroll(grid,true);layout.Children.Add(grid);
  foreach(var (label,path,width) in new[]{("Pazaryeri","Marketplace",90),("Mağaza","ShopId",100),("Sipariş","OrderId",110),("Sipariş durumu (kaynak)","RawStatus",150),("Ödeme","PaymentStatus",110),("Stok kararı","StockDecisionLabel",130),("Kargo","DeliveryLabel",210),("Teslimat SLA","SlaLabel",120),("Taşıyıcı","Carriers",110),("Takip no","TrackingNumbers",130),("Toplam","TotalLabel",100),("Kaynak","Source",120),("Son başarılı alım","SyncLabel",140),("Aciliyet","UrgencyLabel",190)}){var column=GridColumns.Text(label,path,width);column.MinWidth=width;grid.Columns.Add(column);}
  static string ColumnKey(DataGridColumn c)=>c is DataGridBoundColumn{Binding:Binding b}?b.Path.Path:c.Header?.ToString()??"";
  var applyingLayout=false;
  IReadOnlyList<DataGridColumnLayout> CurrentColumns()=>grid.Columns.Select(c=>new DataGridColumnLayout(ColumnKey(c),c.DisplayIndex,c.Width.IsAbsolute?c.Width.Value:c.ActualWidth,c.Visibility==Visibility.Visible)).ToList();
  void ApplyLayout(DataGridLayoutState? state){if(state==null)return;applyingLayout=true;try{var byKey=grid.Columns.GroupBy(ColumnKey,StringComparer.Ordinal).ToDictionary(g=>g.Key,g=>g.First(),StringComparer.Ordinal);var order=DataGridLayoutCodec.ResolveOrder(grid.Columns.Select(ColumnKey).ToList(),state.Columns);for(var i=0;i<order.Count;i++)if(byKey.TryGetValue(order[i],out var column)&&column.DisplayIndex!=i)column.DisplayIndex=i;foreach(var saved in state.Columns){if(!byKey.TryGetValue(saved.Key,out var column))continue;if(saved.Width>0)column.Width=new DataGridLength(saved.Width);column.Visibility=saved.Visible?Visibility.Visible:Visibility.Collapsed;}
   // A PII column (none today) never shows under a preset, whatever the saved state says.
   if(presetController.Current!=OrderColumnPresets.CustomKey)foreach(var column in grid.Columns)if(OrderColumnPresets.IsPii(ColumnKey(column)))column.Visibility=Visibility.Collapsed;}finally{applyingLayout=false;}}
  void SyncPresetCombo(){applyingLayout=true;try{columnPreset.SelectedIndex=OrderColumnPresets.Options.ToList().FindIndex(o=>o.Key==presetController.Current);}finally{applyingLayout=false;}}
  void UserEditedLayout(){if(applyingLayout||grid.Columns.Count==0)return;try{presetController.UserEdited(new DataGridLayoutState(DataGridLayoutCodec.CurrentVersion,CurrentColumns(),"",false));}catch(Exception e){status.Text="Kolon düzeni kaydedilemedi: "+MarketplaceConnectionStore.Redact(e.Message);}SyncPresetCombo();}
  columnPreset.SelectionChanged+=(_,_)=>{if(applyingLayout||columnPreset.SelectedIndex<0)return;var key=OrderColumnPresets.Options[columnPreset.SelectedIndex].Key;ApplyLayout(presetController.Select(key,grid.Columns.Select(ColumnKey).ToList(),CurrentColumns()));};
  ApplyLayout(presetController.Initial(grid.Columns.Select(ColumnKey).ToList(),CurrentColumns()));SyncPresetCombo();
  grid.ColumnDisplayIndexChanged+=(_,_)=>UserEditedLayout();grid.ColumnReordered+=(_,_)=>UserEditedLayout();
  var widthDescriptor=System.ComponentModel.DependencyPropertyDescriptor.FromProperty(DataGridColumn.WidthProperty,typeof(DataGridColumn));var visibilityDescriptor=System.ComponentModel.DependencyPropertyDescriptor.FromProperty(DataGridColumn.VisibilityProperty,typeof(DataGridColumn));foreach(var column in grid.Columns){widthDescriptor.AddValueChanged(column,(_,_)=>UserEditedLayout());visibilityDescriptor.AddValueChanged(column,(_,_)=>UserEditedLayout());}
  var detail=new StackPanel{Margin=new Thickness(12,0,0,0)};var scroll=new ScrollViewer{Content=detail,VerticalScrollBarVisibility=ScrollBarVisibility.Auto};
  // #837: the detail's header is docked above the scrolling body, so id / store / status / payment / SLA / exceptions stay in view however far the body scrolls.
  var detailHeader=new Border{Tag="order-detail-header",Padding=new Thickness(10,6,10,6),Margin=new Thickness(12,0,0,4),Visibility=Visibility.Collapsed};var detailHost=new DockPanel{Tag="order-detail-host",LastChildFill=true};DockPanel.SetDock(detailHeader,Dock.Top);detailHost.Children.Add(detailHeader);detailHost.Children.Add(scroll);layout.Children.Add(splitter);layout.Children.Add(detailHost);
  void RenderDetailHeader(OrderDetailHeaderModel? m){if(m==null){detailHeader.Visibility=Visibility.Collapsed;detailHeader.Child=null;return;}var hc=SeverityStyle.IsHighContrast;var accent=SeverityStyle.AccentBrush(m.Level,hc);var body=new StackPanel();
   var title=new TextBlock{Text=$"{m.Glyph} {m.Title}",FontSize=DesignTokens.TextSubsectionTitleSize,FontWeight=DesignTokens.FontWeightTitle,TextTrimming=TextTrimming.CharacterEllipsis,ToolTip="Sipariş "+m.FullId,Foreground=accent};body.Children.Add(title);
   body.Children.Add(new TextBlock{Text=m.Secondary,FontSize=13,TextWrapping=TextWrapping.Wrap});body.Children.Add(new TextBlock{Text=m.Tertiary,FontSize=DesignTokens.TextCaptionSize,Opacity=0.85,TextWrapping=TextWrapping.Wrap});
   detailHeader.Child=body;detailHeader.BorderBrush=accent;detailHeader.BorderThickness=new Thickness(0,0,0,SeverityStyle.For(m.Level,hc).BorderWeight);detailHeader.Visibility=Visibility.Visible;System.Windows.Automation.AutomationProperties.SetName(detailHeader,m.AutomationText);}
  void ApplyWorkspaceMode(double width){var mode=OrderWorkspaceLayout.Mode(width);if(mode==workspaceMode&&layout.ColumnDefinitions.Count+layout.RowDefinitions.Count>0)return;workspaceMode=mode;layout.ColumnDefinitions.Clear();layout.RowDefinitions.Clear();
   if(mode==OrderWorkspaceMode.SideBySide){layout.ColumnDefinitions.Add(new(){Width=new GridLength(1,GridUnitType.Star),MinWidth=OrderWorkspaceLayout.MinListWidth});layout.ColumnDefinitions.Add(new(){Width=GridLength.Auto});layout.ColumnDefinitions.Add(new(){Width=new GridLength(OrderWorkspaceLayout.ClampDetailWidth(detailWidth,width)),MinWidth=OrderWorkspaceLayout.MinDetailWidth});splitter.Width=6;splitter.Height=double.NaN;splitter.ResizeDirection=GridResizeDirection.Columns;Grid.SetRow(grid,0);Grid.SetRow(splitter,0);Grid.SetRow(detailHost,0);Grid.SetColumn(grid,0);Grid.SetColumn(splitter,1);Grid.SetColumn(detailHost,2);}
   else{layout.RowDefinitions.Add(new(){Height=new GridLength(1,GridUnitType.Star)});layout.RowDefinitions.Add(new(){Height=GridLength.Auto});layout.RowDefinitions.Add(new(){Height=new GridLength(OrderWorkspaceLayout.StackedDetailShare,GridUnitType.Star)});splitter.Height=6;splitter.Width=double.NaN;splitter.ResizeDirection=GridResizeDirection.Rows;Grid.SetColumn(grid,0);Grid.SetColumn(splitter,0);Grid.SetColumn(detailHost,0);Grid.SetRow(grid,0);Grid.SetRow(splitter,1);Grid.SetRow(detailHost,2);}}
  ApplyWorkspaceMode(0);layout.SizeChanged+=(_,e)=>ApplyWorkspaceMode(e.NewSize.Width);
  splitter.DragCompleted+=(_,_)=>{if(workspaceMode!=OrderWorkspaceMode.SideBySide||layout.ColumnDefinitions.Count<3)return;var column=layout.ColumnDefinitions[2];detailWidth=OrderWorkspaceLayout.ClampDetailWidth(column.ActualWidth>0?column.ActualWidth:column.Width.Value,layout.ActualWidth);try{viewStore.Set(OrderWorkspaceLayout.SplitPreferenceKey,OrderWorkspaceLayout.Serialize(detailWidth));}catch(Exception){}};
  List<OrderSnapshot> all=[];OrderSnapshot? editing=null;string? selectionKey=null;Dictionary<(string,string,string),int> pendingByOrder=new();Dictionary<string,IReadOnlyList<string>> trackingSeenElsewhere=new(StringComparer.OrdinalIgnoreCase);CancellationTokenSource? running=null;
  // #782: the selected shipment's observation timeline is paged in lazily (see ShipmentEditor); scrolling the
  // detail pane near its bottom requests the next page, and switching order/shipment cancels the in-flight one.
  CancellationTokenSource? timelineCts=null;Func<Task>? timelineLoadMore=null;
  scroll.ScrollChanged+=async(_,_)=>{if(timelineLoadMore is {} loadMore&&OrderTimelineLoader.ShouldLoadOnScroll(scroll.VerticalOffset,scroll.ViewportHeight,scroll.ExtentHeight))await loadMore();};
  void ReloadViews()=>savedViews.ItemsSource=viewStore.ListViews("orders");
  void LoadView(SavedUiView view){using var doc=JsonDocument.Parse(view.Payload);var root=doc.RootElement;search.Text=root.GetProperty("search").GetString()??"";filter.SelectedIndex=root.GetProperty("state").GetInt32();marketplaceFilter.SelectedItem=root.GetProperty("marketplace").GetString()??"Tümü";shopFilter.SelectedItem=root.GetProperty("shop").GetString()??"Tümü";stockFilter.SelectedItem=root.GetProperty("stock").GetString()??"Tümü";}
  void Filter(){string q=search.Text.Trim();var selectedMarketplace=marketplaceFilter.SelectedItem?.ToString()??"Tümü";var selectedShop=shopFilter.SelectedItem?.ToString()??"Tümü";var selectedStock=stockFilter.SelectedItem?.ToString()??"Tümü";var selectedBand=urgencyFilter.SelectedIndex<=0?null:OrderUrgencyScorer.BandOptions[urgencyFilter.SelectedIndex-1].Key;var filtered=all.Where(o=>(selectedBand==null||OrderUrgencyScorer.Band(o.UrgencyScore)==selectedBand||(selectedBand==OrderUrgencyScorer.CancelledBand&&o.UrgencyLabel.StartsWith(OrderUrgencyScorer.CancelledBand,StringComparison.Ordinal)))&&(q.Length==0||$"{o.Marketplace} {o.ShopId} {o.OrderId} {o.TrackingNumbers} {string.Join(' ',o.Items.Select(i=>i.Title+" "+i.Sku))}".Contains(q,StringComparison.CurrentCultureIgnoreCase))&&(filter.SelectedIndex<=0||o.Shipments.Any(s=>s.State==OrdersRules.States[filter.SelectedIndex-1])||(filter.SelectedIndex==1&&o.Shipments.Count==0))&&(selectedMarketplace=="Tümü"||o.Marketplace==selectedMarketplace)&&(selectedShop=="Tümü"||o.ShopId==selectedShop)&&(selectedStock=="Tümü"||(selectedStock=="Stok düşüldü"&&o.StockDecisionLabel=="Stok düşüldü")||(selectedStock=="Stok bekliyor"&&o.StockDecisionLabel!="Stok düşüldü")));var keepKey=grid.SelectedItem is OrderSnapshot kept?OrderWorkspaceLayout.SelectionKey(kept):selectionKey;grid.ItemsSource=urgencySort.IsChecked==true?OrderUrgencyScorer.Sort(filtered,o=>o.UrgencyScore,o=>$"{o.Marketplace}/{o.ShopId}/{o.OrderId}"):filtered.ToList();
   // #836: the same order stays selected across a reload (fresh instances) or a filter change; when it is no longer listed the detail closes -- a detail never shows an order the list does not.
   var restored=OrderWorkspaceLayout.Restore((IEnumerable<OrderSnapshot>)grid.ItemsSource,keepKey);if(restored!=null){if(!ReferenceEquals(grid.SelectedItem,restored))grid.SelectedItem=restored;}else if(keepKey!=null){selectionKey=null;editing=null;RenderDetailHeader(null);detail.Children.Clear();detail.Children.Add(Text("Seçili sipariş bu listede değil; ayrıntı kapatıldı. Listeden bir sipariş seçin."));}}
  void Load(){all=store.ReadAll();try{trackingSeenElsewhere=OrderAnomalyDetector.FindDuplicateTracking(all).ToDictionary(a=>a.Key,a=>a.OrderIds,StringComparer.OrdinalIgnoreCase);}catch(Exception){trackingSeenElsewhere=new(StringComparer.OrdinalIgnoreCase);}foreach(var order in all)order.StockDecisionLabel=catalog.GetOrderStockStatus(order.Marketplace,order.ShopId,order.OrderId)==null?"Stok bekliyor":"Stok düşüldü";
   var knownSkus=catalog.Products().Where(p=>!string.IsNullOrWhiteSpace(p.Sku)).Select(p=>p.Sku.Trim()).ToHashSet(StringComparer.OrdinalIgnoreCase);try{pendingByOrder=new OrderExceptionStore(directory).List(status:"Pending").GroupBy(x=>(x.Marketplace,x.ShopId,x.OrderId)).ToDictionary(g=>g.Key,g=>g.Count());}catch(Exception){pendingByOrder=new();}var pending=pendingByOrder;
   var nowUtc=DateTimeOffset.UtcNow;foreach(var order in all){var urgency=OrderUrgencyScorer.Score(OrderUrgencyScorer.InputFor(order,knownSkus,pending.TryGetValue((order.Marketplace,order.ShopId,order.OrderId),out var n)?n:0,nowUtc));order.UrgencyScore=urgency.Score;order.UrgencyLabel=urgency.Label;}marketplaceFilter.ItemsSource=new[]{"Tümü"}.Concat(all.Select(o=>o.Marketplace).Distinct(StringComparer.OrdinalIgnoreCase).OrderBy(x=>x)).ToArray();shopFilter.ItemsSource=new[]{"Tümü"}.Concat(all.Select(o=>o.ShopId).Distinct(StringComparer.OrdinalIgnoreCase).OrderBy(x=>x)).ToArray();Filter();status.Text=$"{all.Count} kayıt · Liste son yükleme: {DateTime.Now:g}. Boş liste varsa Etsy'den yenileyin veya yerel sipariş ekleyin.";}
  System.Windows.Threading.DispatcherTimer? remaskTimer=null;Border? customerBox=null;
  void RenderCustomerSection(OrderSnapshot o,PiiRevealDecision? granted=null,string? statusLine=null){
   remaskTimer?.Stop();remaskTimer=null;
   var customer=store.ReadCustomer(o.Marketplace,o.ShopId,o.OrderId)??new OrderCustomer(o.Marketplace,o.ShopId,o.OrderId,"","","","");var policy=catalog.GetPiiRevealPolicy();var hc=SeverityStyle.IsHighContrast;
   var box=new Border{Tag="order-customer-section",Padding=new Thickness(8,6,8,6),Margin=new Thickness(3,4,3,6),BorderBrush=SeverityStyle.AccentBrush(granted==null?SeverityLevel.Info:SeverityLevel.Warning,hc),BorderThickness=new Thickness(SeverityStyle.For(granted==null?SeverityLevel.Info:SeverityLevel.Warning,hc).BorderWeight,0,0,0),Focusable=true};FocusStyles.MakeFocusable(box);var body=new StackPanel();box.Child=body;
   body.Children.Add(new TextBlock{Text=granted==null?"Müşteri · maskeli":"Müşteri · AÇIK (otomatik maskelenecek)",FontWeight=FontWeights.SemiBold});
   if(customer.IsEmpty&&granted==null)body.Children.Add(new TextBlock{Tag="order-customer-empty",Text="Kayıtlı müşteri iletişim verisi yok.",TextWrapping=TextWrapping.Wrap});
   var editors=new Dictionary<string,TextBox>();
   foreach(var (field,masked) in PiiReveal.Masked(customer)){
    if(granted==null){var t=new TextBlock{Tag="order-customer-field",Text=$"{field}: {masked}",TextWrapping=TextWrapping.Wrap};System.Windows.Automation.AutomationProperties.SetName(t,$"{field}: maskeli");if(!customer.IsEmpty)body.Children.Add(t);}
    else{var value=field switch{"Ad"=>customer.Name,"E-posta"=>customer.Email,"Telefon"=>customer.Phone,_=>customer.Address};var tb=new TextBox{Tag="order-customer-edit",Text=value,MaxLength=500};System.Windows.Automation.AutomationProperties.SetName(tb,field);body.Children.Add(new TextBlock{Text=field,FontSize=DesignTokens.TextCaptionSize,Opacity=0.85});body.Children.Add(tb);editors[field]=tb;}}
   var actions=new WrapPanel{Margin=Spacing.AboveInline};
   if(granted==null){
    var reason=new TextBox{Tag="order-customer-reason",Width=260,ToolTip="Gösterim gerekçesi (denetim günlüğüne yazılır)"};System.Windows.Automation.AutomationProperties.SetName(reason,"Gösterim gerekçesi");
    var reveal=new Button{Tag="order-customer-reveal",Content="Göster (gerekçeli)",Padding=Spacing.Chip,Margin=new Thickness(6,0,0,0)};
    reveal.Click+=(_,_)=>{var decision=PiiReveal.Request(policy,reason.Text,DateTime.UtcNow);try{new AuditStore(directory).Append(PiiReveal.AuditFor(customer,decision,DateTime.UtcNow));}catch(Exception){}
     if(!decision.Allowed){status.Text="Gösterim reddedildi: "+decision.DeniedBecause;RenderCustomerSection(o,null,decision.DeniedBecause);return;}
     status.Text=$"Müşteri verisi açıldı; {policy.Normalized().RevealSeconds} sn sonra otomatik maskelenir.";RenderCustomerSection(o,decision);};
    actions.Children.Add(reason);actions.Children.Add(reveal);}
   else{
    var save=new Button{Tag="order-customer-save",Content="Müşteri verisini kaydet",Padding=Spacing.Chip};
    save.Click+=(_,_)=>{try{store.SaveCustomer(new OrderCustomer(o.Marketplace,o.ShopId,o.OrderId,editors["Ad"].Text.Trim(),editors["E-posta"].Text.Trim(),editors["Telefon"].Text.Trim(),editors["Adres"].Text.Trim()));status.Text="Müşteri verisi yerel olarak kaydedildi; pazaryerine gönderilmedi.";}catch(Exception e){status.Text="Müşteri verisi kaydedilemedi: "+MarketplaceConnectionStore.Redact(e.Message);}RenderCustomerSection(o);};
    var mask=new Button{Tag="order-customer-mask",Content="Maskele",Padding=Spacing.Chip,Margin=new Thickness(6,0,0,0)};mask.Click+=(_,_)=>RenderCustomerSection(o);
    actions.Children.Add(save);actions.Children.Add(mask);
    var due=granted.RemaskAtUtc??DateTime.UtcNow;var wait=due-DateTime.UtcNow;if(wait<TimeSpan.FromMilliseconds(50))wait=TimeSpan.FromMilliseconds(50);
    remaskTimer=new System.Windows.Threading.DispatcherTimer{Interval=wait};remaskTimer.Tick+=(_,_)=>{remaskTimer?.Stop();if(customerBox!=null&&detail.Children.Contains(customerBox)){status.Text="Müşteri verisi otomatik olarak maskelendi.";RenderCustomerSection(o);}};remaskTimer.Start();}
   body.Children.Add(actions);
   if(statusLine!=null)body.Children.Add(new TextBlock{Tag="order-customer-status",Text=statusLine,TextWrapping=TextWrapping.Wrap,FontSize=DesignTokens.TextCaptionSize,Foreground=SeverityStyle.AccentBrush(SeverityLevel.Warning,hc)});
   System.Windows.Automation.AutomationProperties.SetName(box,granted==null?"Müşteri verisi maskeli":"Müşteri verisi açık");
   if(customerBox!=null&&detail.Children.Contains(customerBox)){var at=detail.Children.IndexOf(customerBox);detail.Children.RemoveAt(at);detail.Children.Insert(at,box);}else detail.Children.Add(box);customerBox=box;}
  void Edit(OrderSnapshot order,bool isNew=false)
  {
   editing=order.Copy();var o=editing;Action captureShipment=()=>{};timelineCts?.Cancel();timelineLoadMore=null;detail.Children.Clear();RenderDetailHeader(isNew?null:OrderDetailHeader.Compose(o,pendingByOrder.TryGetValue((o.Marketplace,o.ShopId,o.OrderId),out var pendingCount)?pendingCount:0,DateTimeOffset.UtcNow));detail.Children.Add(Text(isNew?"Yeni yerel sipariş":"Sipariş ayrıntısı",TextRole.SubsectionTitle));
   var marketplace=Field(detail,"Pazaryeri",o.Marketplace,!isNew);var shop=Field(detail,"Mağaza kimliği",o.ShopId,!isNew);var id=Field(detail,"Sipariş numarası",o.OrderId,!isNew);
   bool api=o.Source=="Etsy API";var raw=Field(detail,"Sipariş durumu (ham değer)",o.RawStatus,api);var payment=Field(detail,"Ödeme durumu",o.PaymentStatus,api);
   detail.Children.Add(Text($"Kaynak: {o.Source}\nSon API alımı: {o.SyncLabel}"));
   // #841: the customer section -- masked by default; a reveal needs the policy and a reason, is audited (fields and reason, never a value) and re-masks itself; edits are possible only after a granted reveal.
   if(!isNew)RenderCustomerSection(o);detail.Children.Add(Text("Ürünler",TextRole.SubsectionTitle));
   // #838: the lines as a reconciliation -- ordered / shipped (what the stock receipt deducted) / returned (the ledger) / cancelled -- with the difference as a state, not a colour.
   if(isNew){foreach(var i in o.Items)detail.Children.Add(Text($"{i.Quantity} × {i.Title} · SKU: {i.Sku}"));}
   else{IReadOnlyDictionary<string,int> returnedBySku;try{returnedBySku=catalog.OrderReturnsApplied(o.Marketplace,o.ShopId,o.OrderId);}catch(Exception){returnedBySku=new Dictionary<string,int>();}
    var lines=OrderLineReconciliation.Build(o,catalog.GetOrderStockStatus(o.Marketplace,o.ShopId,o.OrderId),returnedBySku);var hc=SeverityStyle.IsHighContrast;
    var linesGrid=new DataGrid{Tag="order-lines",IsReadOnly=true,AutoGenerateColumns=false,HeadersVisibility=DataGridHeadersVisibility.Column,CanUserAddRows=false,SelectionMode=DataGridSelectionMode.Single,Margin=new Thickness(3,0,3,4),ItemsSource=lines};
    foreach(var (label,path,width) in new[]{("SKU","Sku",90),("Ürün","Title",170),("Sipariş","Ordered",60),("Sevk","Shipped",55),("İade","Returned",55),("İptal","Cancelled",55),("Açık","Outstanding",50),("Durum","StateLabel",200)})linesGrid.Columns.Add(GridColumns.Text(label,path,width));
    linesGrid.LoadingRow+=(_,e)=>{if(e.Row.Item is OrderLineView line){var style=SeverityStyle.For(line.Level,hc);e.Row.BorderBrush=SeverityStyle.AccentBrush(line.Level,hc);e.Row.BorderThickness=new Thickness(style.BorderWeight,0,0,0);e.Row.ToolTip=line.StateLabel;System.Windows.Automation.AutomationProperties.SetName(e.Row,$"{line.Sku}: sipariş {line.Ordered}, sevk {line.Shipped}, iade {line.Returned}, iptal {line.Cancelled}. {line.StateLabel}");}};
    var linesSummary=Text(OrderLineReconciliation.Summary(lines));linesSummary.FontWeight=FontWeights.SemiBold;var worst=lines.Count==0?SeverityLevel.Info:lines.Max(l=>l.Level);linesSummary.Foreground=SeverityStyle.AccentBrush(worst,hc);System.Windows.Automation.AutomationProperties.SetName(linesSummary,"Satır mutabakatı: "+linesSummary.Text);
    detail.Children.Add(linesSummary);detail.Children.Add(linesGrid);
    // #840: the returns as one section -- requests from the exception queue, each SKU's return position with the reconciliation's stock-impact preview, the applied events, the refund against the order total.
    IReadOnlyList<OrderExceptionRecord> returnRequests;try{returnRequests=new OrderExceptionStore(directory).List(o.Marketplace,o.ShopId).Where(x=>x.OrderId==o.OrderId).ToList();}catch(Exception){returnRequests=Array.Empty<OrderExceptionRecord>();}
    IReadOnlyList<OrderReturnLedgerRow> returnEvents;try{returnEvents=catalog.OrderReturnEvents(o.Marketplace,o.ShopId,o.OrderId);}catch(Exception){returnEvents=Array.Empty<OrderReturnLedgerRow>();}
    var returnsReceipt=catalog.GetOrderStockStatus(o.Marketplace,o.ShopId,o.OrderId);var previewOrder=o;
    var returns=OrderReturnsSection.Compose(o,returnRequests,returnEvents,returnsReceipt,(sku,qty)=>{try{return catalog.PreviewOrderReturn(previewOrder,new OrderReturnEvent(previewOrder.Marketplace,previewOrder.ShopId,previewOrder.OrderId,"preview:"+sku,sku,qty,0m,previewOrder.Currency,DateTimeOffset.UtcNow));}catch(Exception){return null;}});
    var returnsHc=SeverityStyle.IsHighContrast;var returnsBox=new Border{Tag="order-returns-section",Padding=new Thickness(8,6,8,6),Margin=new Thickness(3,4,3,6),BorderBrush=SeverityStyle.AccentBrush(returns.Level,returnsHc),BorderThickness=new Thickness(SeverityStyle.For(returns.Level,returnsHc).BorderWeight,0,0,0),Focusable=true};FocusStyles.MakeFocusable(returnsBox);var returnsBody=new StackPanel();returnsBox.Child=returnsBody;
    returnsBody.Children.Add(new TextBlock{Text=$"{SeverityStyle.For(returns.Level,returnsHc).Glyph} İadeler · {returns.Headline}",FontWeight=FontWeights.SemiBold,TextWrapping=TextWrapping.Wrap,Foreground=SeverityStyle.AccentBrush(returns.Level,returnsHc)});
    foreach(var req in returns.Requests){var r=new Border{Tag="order-return-request",Padding=new Thickness(6,2,6,2),Margin=new Thickness(0,2,0,0),BorderBrush=SeverityStyle.AccentBrush(req.Level,returnsHc),BorderThickness=new Thickness(SeverityStyle.For(req.Level,returnsHc).BorderWeight,0,0,0),Focusable=true,Child=new TextBlock{Text=req.Line,TextWrapping=TextWrapping.Wrap}};FocusStyles.MakeFocusable(r);System.Windows.Automation.AutomationProperties.SetName(r,req.Line);returnsBody.Children.Add(r);}
    foreach(var line in returns.Lines){var t=new TextBlock{Tag="order-return-line",Text=line.Line,TextWrapping=TextWrapping.Wrap,Margin=new Thickness(0,2,0,0),Foreground=SeverityStyle.AccentBrush(line.Level,returnsHc)};System.Windows.Automation.AutomationProperties.SetName(t,line.Line);returnsBody.Children.Add(t);}
    if(returns.Timeline.Count>0){returnsBody.Children.Add(new TextBlock{Text="Kayıtlı iadeler (eskiden yeniye)",FontSize=DesignTokens.TextCaptionSize,Opacity=0.85,Margin=Spacing.AboveInline});foreach(var ev in returns.Timeline)returnsBody.Children.Add(new TextBlock{Tag="order-return-event",Text=ev.Line,TextWrapping=TextWrapping.Wrap,FontSize=DesignTokens.TextCaptionSize});}
    var refund=new TextBlock{Tag="order-return-refund",Text=returns.RefundLine,TextWrapping=TextWrapping.Wrap,Margin=Spacing.AboveInline,FontWeight=FontWeights.SemiBold,Foreground=SeverityStyle.AccentBrush(returns.RefundLevel,returnsHc)};System.Windows.Automation.AutomationProperties.SetName(refund,returns.RefundLine);returnsBody.Children.Add(refund);
    foreach(var note in returns.Notes){var n=Text(note);n.FontSize=DesignTokens.TextCaptionSize;returnsBody.Children.Add(n);}
    System.Windows.Automation.AutomationProperties.SetName(returnsBox,"İadeler: "+returns.Headline+". "+returns.RefundLine);detail.Children.Add(returnsBox);}
   if(!api){var product=Field(detail,"Ürün adı (ekle)","");var sku=Field(detail,"SKU","");var qty=Field(detail,"Adet","1");var itemAdd=Button(detail,"Ürünü ekle");itemAdd.Click+=(_,_)=>{if(string.IsNullOrWhiteSpace(product.Text)||!int.TryParse(qty.Text,out int n)||n<=0){status.Text="Ürün adı ve pozitif tam adet girin.";return;}Capture();captureShipment();o.Items.Add(new(){Title=product.Text.Trim(),Sku=sku.Text.Trim(),Quantity=n});Edit(o,isNew);};}
   if(!isNew){
    detail.Children.Add(Text("Merkezi stok işlemi",TextRole.SubsectionTitle));
    var receipt=catalog.GetOrderStockStatus(o.Marketplace,o.ShopId,o.OrderId);
    if(receipt!=null){detail.Children.Add(Text($"Stok işlendi: {receipt.AppliedUtc.ToLocalTime():g}"));foreach(var movement in receipt.Movements)detail.Children.Add(Text($"{movement.Sku}: {movement.StockBefore} → {movement.StockAfter} (−{movement.Quantity})"));}
    else detail.Children.Add(Text("Bu sipariş için stok düşümü kaydı yok. Stoğunu daha önce elle düşürdüğünüz siparişlerde çalıştırmayın."));
    detail.Children.Add(Text("Yalnız kaydedilmiş sipariş satırları kullanılır. SKU tek ürüne eşleşmelidir; eksik/çakışan SKU veya yetersiz stokta tüm işlem geri alınır. Düşüm yerel ve geçicidir: XML stok kilidi etkinleştirilmez, bir sonraki tedarikçi feed'i stoğu tedarikçinin değeriyle yeniden yazar (kalıcı kilit için ürün kartındaki stok kilidini kullanın). Pazaryerlerine gönderim yapılmaz."));
    if(receipt==null){
     var catalogProducts=catalog.Products();
     var savedPreview=store.ReadAll().Single(x=>x.Marketplace==o.Marketplace&&x.ShopId==o.ShopId&&x.OrderId==o.OrderId);
     foreach(var line in savedPreview.Items.GroupBy(x=>x.Sku,StringComparer.Ordinal)){
      var matches=catalogProducts.Where(x=>x.Sku==line.Key).ToList();var quantity=line.Sum(x=>(long)x.Quantity);
      detail.Children.Add(Text(matches.Count==1?$"{line.Key}: mevcut {matches[0].Stock}, düşülecek {quantity}, kalan {matches[0].Stock-quantity}":$"{line.Key}: ürün eşleşmesi belirsiz ({matches.Count} kayıt)"));
     }
     detail.Children.Add(Text("Önizleme anlık bilgidir; düğmeye basıldığında stok yeniden doğrulanır."));
    }
    var applyStock=Button(detail,"Kaydedilmiş siparişi stoktan düş");applyStock.IsEnabled=receipt==null;
    applyStock.Click+=(_,_)=>{try{
     var saved=store.ReadAll().Single(x=>x.Marketplace==o.Marketplace&&x.ShopId==o.ShopId&&x.OrderId==o.OrderId);
     var preview=new OrderStockDecisionService(catalog).CreatePreview(saved);var result=new OrderStockDecisionService(catalog).ApplyApproved(preview,true);
     catalogChanged?.Invoke();Edit(saved);status.Text=result.AlreadyApplied?"Bu sipariş zaten işlendi; stok tekrar düşmedi.":"Sipariş stoğu tek işlemde düşüldü. Düşüm yerel ve geçicidir (XML stok kilidi etkinleştirilmedi); dış pazaryerlerine gönderim yapılmadı.";
    }catch(InvalidOperationException ex){status.Text=ex.Message;}catch(ArgumentException ex){status.Text=ex.Message;}catch{status.Text="Stok işlemi tamamlanamadı; kayıtlar korunur. Yenileyip tekrar deneyin.";}};
   }
   detail.Children.Add(Text("Paketler / gözlem geçmişi",TextRole.SubsectionTitle));
   var shipments=new ComboBox{ItemsSource=o.Shipments,DisplayMemberPath="Label",MinWidth=260};
   // #839: the shipping overview -- how many packages, what state and SLA each is in, and the flags (duplicate tracking here or in another order, no tracking); tracking masked here, full in the editor below.
   var shippingSection=OrderShippingSection.Compose(o,trackingSeenElsewhere,DateTimeOffset.UtcNow);var shippingHc=SeverityStyle.IsHighContrast;var shippingBox=new Border{Tag="order-shipping-section",Padding=new Thickness(8,6,8,6),Margin=new Thickness(3,0,3,6),BorderBrush=SeverityStyle.AccentBrush(shippingSection.Level,shippingHc),BorderThickness=new Thickness(SeverityStyle.For(shippingSection.Level,shippingHc).BorderWeight,0,0,0)};var shippingBody=new StackPanel();shippingBox.Child=shippingBody;
   var shippingHead=new TextBlock{Text=$"{SeverityStyle.For(shippingSection.Level,shippingHc).Glyph} {shippingSection.Headline}",FontWeight=FontWeights.SemiBold,TextWrapping=TextWrapping.Wrap,Foreground=SeverityStyle.AccentBrush(shippingSection.Level,shippingHc)};shippingBody.Children.Add(shippingHead);
   foreach(var row in shippingSection.Rows){var rowStyle=SeverityStyle.For(row.Level,shippingHc);var b=new Button{Tag=row.Id,HorizontalAlignment=HorizontalAlignment.Stretch,HorizontalContentAlignment=HorizontalAlignment.Left,Padding=new Thickness(6,3,6,3),Margin=new Thickness(0,2,0,0),BorderBrush=SeverityStyle.AccentBrush(row.Level,shippingHc),BorderThickness=new Thickness(rowStyle.BorderWeight,0.5,0.5,0.5),Content=new TextBlock{Text=row.Line,TextWrapping=TextWrapping.Wrap},ToolTip=$"{row.StateLabel} · {row.EventCount} gözlem"+(row.HasTrackingUrl?" · takip bağlantısı var":"")};
    System.Windows.Automation.AutomationProperties.SetName(b,$"Paket {row.Id}: {row.Word}, {row.Carrier}, takip {row.TrackingMasked}, {row.SlaLabel}"+(row.Flags.Count>0?". "+string.Join(". ",row.Flags):"")+". Seçmek için etkinleştirin.");
    b.Click+=(_,_)=>{var target=o.Shipments.FirstOrDefault(x=>x.Id==(string)b.Tag);if(target!=null)shipments.SelectedItem=target;};shippingBody.Children.Add(b);}
   foreach(var note in shippingSection.Notes){var n=Text(note);n.FontSize=DesignTokens.TextCaptionSize;shippingBody.Children.Add(n);}
   detail.Children.Add(shippingBox);detail.Children.Add(shipments);var shippingArea=new StackPanel();detail.Children.Add(shippingArea);
   void ShipmentEditor(OrderShipment s)
   {
    shippingArea.Children.Clear();var carrier=Field(shippingArea,"Taşıyıcı",s.Carrier);var tracking=Field(shippingArea,"Takip numarası",s.TrackingNumber);var url=Field(shippingArea,"HTTPS takip bağlantısı (isteğe bağlı)",s.TrackingUrl);
    shippingArea.Children.Add(Text("Kargo durumu — kullanıcı gözlemi"));var state=new ComboBox{ItemsSource=OrdersRules.States.Select(x=>new StateChoice(x,OrdersRules.Label(x))).ToArray(),DisplayMemberPath="Label",SelectedValuePath="Value",SelectedValue=s.State};shippingArea.Children.Add(state);
    shippingArea.Children.Add(Text($"Teslimat SLA: {OrdersRules.EvaluateSla(s,o.SourceUpdatedAt==default?o.UpdatedAt:o.SourceUpdatedAt,DateTimeOffset.UtcNow).Label} (izin verilen taşıma süresi {OrdersRules.DefaultMaxTransitDays} gün)"));
    shippingArea.Children.Add(Text("Etsy gönderim bildirimi taşıyıcının yolda/teslim teyidi değildir. Aşağıdaki geçmiş yalnız kaydedilen yerel gözlemlerdir."));
    // Lazy timeline (#782): newest-first, one page at a time, appended in chunks with a dispatcher yield in
    // between so a long history never blocks input; the loader itself refuses duplicate/in-flight pages.
    timelineCts?.Cancel();var timelineLifetime=timelineCts=new CancellationTokenSource();var loader=new OrderTimelineLoader(s.Events);
    shippingArea.Children.Add(Text($"{loader.Total} gözlem kaydı · en yeniden eskiye, sayfa sayfa yüklenir."));var timeline=new StackPanel();shippingArea.Children.Add(timeline);var more=Button(shippingArea,"");
    void RefreshMore(){more.Content=$"Daha fazla gözlem yükle ({loader.Remaining} kaldı)";more.Visibility=loader.HasMore?Visibility.Visible:Visibility.Collapsed;}
    async Task LoadMoreAsync(){if(timelineLifetime.IsCancellationRequested)return;try{await loader.LoadPageAsync(loader.Cursor,e=>timeline.Children.Add(Text($"{e.At.ToLocalTime():g} · {OrdersRules.Label(e.State)} · {e.Source}")),static async()=>{await System.Windows.Threading.Dispatcher.Yield(System.Windows.Threading.DispatcherPriority.Background);},timelineLifetime.Token);}catch(Exception ex)when(ex is not OperationCanceledException){status.Text="Gözlem geçmişi yüklenemedi: "+ex.Message;}finally{if(!timelineLifetime.IsCancellationRequested)RefreshMore();}}
    more.Click+=async(_,_)=>await LoadMoreAsync();timelineLoadMore=LoadMoreAsync;RefreshMore();_=LoadMoreAsync();
    var open=Button(shippingArea,"Takip bağlantısını aç");open.Click+=(_,_)=>{if(!OrdersRules.SafeTrackingUrl(url.Text.Trim())){status.Text="Geçerli HTTPS takip bağlantısı girin.";return;}try{Process.Start(new ProcessStartInfo(url.Text.Trim()){UseShellExecute=true});}catch{status.Text="Takip bağlantısı tarayıcıda açılamadı.";}};
    captureShipment=()=>{if(s.Carrier!=carrier.Text.Trim()||s.TrackingNumber!=tracking.Text.Trim()||s.TrackingUrl!=url.Text.Trim())s.Source="Yerel / manuel";s.Carrier=carrier.Text.Trim();s.TrackingNumber=tracking.Text.Trim();s.TrackingUrl=url.Text.Trim();s.State=state.SelectedValue as string??"Unknown";};
   }
   shipments.SelectionChanged+=(_,_)=>{captureShipment();if(shipments.SelectedItem is OrderShipment s)ShipmentEditor(s);};if(o.Shipments.Count>0)shipments.SelectedIndex=0;
   var newShipment=Button(detail,"+ Paket ekle");newShipment.Click+=(_,_)=>{Capture();captureShipment();o.Shipments.Add(new(){Id="local:"+Guid.NewGuid().ToString("N")});Edit(o,isNew);};
   var save=Button(detail,"Yerel kaydı / gözlemleri kaydet");save.Click+=(_,_)=>{try{Capture();captureShipment();if(isNew&&store.ReadAll().Any(x=>x.Marketplace==o.Marketplace&&x.ShopId==o.ShopId&&x.OrderId==o.OrderId))throw new ArgumentException("Bu sipariş zaten kayıtlı; listeden açarak düzenleyin.");store.SaveManual(o);Load();var saved=all.First(x=>x.Marketplace==o.Marketplace&&x.ShopId==o.ShopId&&x.OrderId==o.OrderId);Edit(saved);status.Text="Yerel kayıt kaydedildi. Pazaryerine veya taşıyıcıya gönderim yapılmadı.";}catch(ArgumentException ex){status.Text=ex.Message;}catch{status.Text="Yerel kayıt kaydedilemedi; disk erişimini kontrol edin.";}};
   void Capture(){o.Marketplace=marketplace.Text.Trim();o.ShopId=shop.Text.Trim();o.OrderId=id.Text.Trim();o.RawStatus=raw.Text.Trim();o.PaymentStatus=payment.Text.Trim();}
  }
  var saveView=Button(bar,"Görünümü kaydet");saveView.Click+=(_,_)=>{viewStore.SaveView("orders",viewName.Text,JsonSerializer.Serialize(new{search=search.Text,state=filter.SelectedIndex,marketplace=marketplaceFilter.SelectedItem?.ToString()??"Tümü",shop=shopFilter.SelectedItem?.ToString()??"Tümü",stock=stockFilter.SelectedItem?.ToString()??"Tümü"}));viewName.Clear();ReloadViews();};var deleteView=Button(bar,"Görünümü sil");deleteView.Click+=(_,_)=>{if(savedViews.SelectedItem is not SavedUiView view)throw new InvalidOperationException("Önce görünüm seçin.");viewStore.DeleteView("orders",view.Name);ReloadViews();};grid.SelectionChanged+=(_,_)=>{if(grid.SelectedItem is not OrderSnapshot o)return;if(!OrderWorkspaceLayout.CanOpenDetail(o,marketplaceFilter.SelectedItem?.ToString(),shopFilter.SelectedItem?.ToString())){status.Text="Seçili mağaza filtresi dışındaki siparişin ayrıntısı açılmaz.";grid.SelectedItem=null;return;}selectionKey=OrderWorkspaceLayout.SelectionKey(o);Edit(o);};search.TextChanged+=(_,_)=>Filter();filter.SelectionChanged+=(_,_)=>Filter();marketplaceFilter.SelectionChanged+=(_,_)=>Filter();shopFilter.SelectionChanged+=(_,_)=>Filter();stockFilter.SelectionChanged+=(_,_)=>Filter();urgencyFilter.SelectionChanged+=(_,_)=>Filter();urgencySort.Checked+=(_,_)=>Filter();urgencySort.Unchecked+=(_,_)=>Filter();savedViews.SelectionChanged+=(_,_)=>{if(savedViews.SelectedItem is SavedUiView view)try{LoadView(view);}catch{status.Text="Kayıtlı görünüm okunamadı.";}};add.Click+=(_,_)=>Edit(new(){Marketplace="Yerel",ShopId="Mağazam",RawStatus="Açık"},true);
  cancel.Click+=(_,_)=>running?.Cancel();root.Unloaded+=(_,_)=>{running?.Cancel();timelineCts?.Cancel();};
  refresh.Click+=async(_,_)=>
  {
   if(running!=null)return;using var cts=new CancellationTokenSource(TimeSpan.FromMinutes(3));running=cts;refresh.IsEnabled=add.IsEnabled=false;cancel.IsEnabled=true;detail.IsEnabled=false;status.Text="Etsy siparişleri okunuyor; tüm sayfalar başarılı olunca kayıtlar güncellenecek…";
   try{if(authorize==null)throw new InvalidOperationException("Önce Etsy API sekmesinde mağaza bağlantısını kurun.");var credentials=await authorize();using var http=new HttpClient(new HttpClientHandler{AllowAutoRedirect=false}){Timeout=TimeSpan.FromSeconds(45)};var rows=await new OrdersEtsyClient(http).ReadAsync(credentials,cts.Token);cts.Token.ThrowIfCancellationRequested();await Task.Run(()=>store.SaveBatch(rows),cts.Token);Load();status.Text=$"Etsy: {rows.Count} sipariş alındı · {DateTime.Now:g}. Taşıyıcı teslimat verisi bu API'de sağlanmaz.";}
   catch(OperationCanceledException){status.Text="Alım iptal edildi veya zaman aşımı; önceki kayıtlar korundu.";}
   catch(InvalidOperationException e){status.Text=e.Message;}
   catch{status.Text="Siparişler alınamadı. Bağlantı, mağaza ve transactions_r iznini kontrol edin. Önceki kayıtlar korundu.";}
   finally{running=null;refresh.IsEnabled=add.IsEnabled=true;cancel.IsEnabled=false;detail.IsEnabled=true;}
  };
  // #813: the window reveals an order the same way it reveals a product or a source -- reload, clear the
  // filters that would hide it, select it (selection opens the detail) and scroll to it. False when it is gone.
  exposeReveal?.Invoke((marketplace,shop,orderId)=>{Load();var hit=all.FirstOrDefault(o=>string.Equals(o.Marketplace,marketplace,StringComparison.OrdinalIgnoreCase)&&o.ShopId==shop&&o.OrderId==orderId);if(hit==null)return false;search.Text="";filter.SelectedIndex=0;marketplaceFilter.SelectedIndex=0;shopFilter.SelectedIndex=0;stockFilter.SelectedIndex=0;Filter();grid.SelectedItem=hit;grid.ScrollIntoView(hit);return true;});
  ReloadViews();Load();detail.Children.Add(Text("Ayrıntıları ve paket geçmişini görmek için listeden bir sipariş seçin. İlk kaydı eklemek için + Yerel sipariş düğmesini kullanın."));return root;
 }
 sealed record StateChoice(string Value,string Label);
 static TextBlock Text(string text,TextRole role=TextRole.Body)=>TextStyles.Apply(new TextBlock{Text=text,TextWrapping=TextWrapping.Wrap,Margin=Spacing.BodyBlock,Foreground=Brushes.DarkSlateGray},role);
 static TextBox Field(Panel parent,string label,string value,bool readOnly=false){parent.Children.Add(Text(label));var box=new TextBox{Text=value,IsReadOnly=readOnly};parent.Children.Add(box);return box;}
 static Button Button(Panel parent,string text){var button=new Button{Content=text,Margin=new Thickness(3,5,3,5)};parent.Children.Add(button);return button;}
}

