using System.Globalization;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using TrMarketplaceHubDesktop.Catalog;

namespace TrMarketplaceHubDesktop;

public static class PolicyCenterPanel
{
    public static FrameworkElement Create(string? directory = null)
    {
        var store = new CatalogStore(directory); var tabs = new TabControl { Margin = new Thickness(12) }; tabs.Items.Add(new TabItem { Header = "Stok politikaları", Content = Stock(store, directory) }); tabs.Items.Add(new TabItem { Header = "Fiyat politikaları", Content = Price(store, directory) }); return tabs;
    }
    static FrameworkElement Stock(CatalogStore store, string? directory)
    {
        var root = new StackPanel { Margin = new Thickness(14), MaxWidth = 1050 }; root.Children.Add(Text("Mağaza stok politikaları", 21)); root.Children.Add(Text("Kanal + mağaza bazında güvenlik stoğu, üst sınır, etkinlik ve ürün preview'i. Değişiklikler yerel katalogda kalır; canlı gönderim yapılmaz.")); var grid = new DataGrid { AutoGenerateColumns = false, IsReadOnly = true, Height = 190 }; foreach (var c in new[] { ("Kanal", "Channel", 100d), ("Mağaza", "Shop", 150d), ("Güvenlik", "SafetyStock", 90d), ("Üst sınır", "MaximumStock", 90d), ("Etkin", "Enabled", 70d), ("Sürüm", "Version", 70d), ("Son değişiklik", "UpdatedUtc", 170d) }) grid.Columns.Add(new DataGridTextColumn { Header = c.Item1, Binding = new System.Windows.Data.Binding(c.Item2), Width = c.Item3 }); root.Children.Add(grid);
        var channel = new TextBox { Text = "etsy", Width = 120 }; var shop = new TextBox { Width = 150 }; var safety = new TextBox { Text = "3", Width = 90 }; var maximum = new TextBox { Width = 90 }; var enabled = new CheckBox { Content = "Etkin", IsChecked = true, Margin = new Thickness(5) }; StockPolicy? loaded = null; var status = Text(""); var row = new WrapPanel(); Add(row, "Kanal", channel); Add(row, "Mağaza", shop); Add(row, "Güvenlik", safety); Add(row, "Üst sınır", maximum); row.Children.Add(enabled); root.Children.Add(row);
        void Reload() { grid.ItemsSource = store.ListStockPolicies(); }
        var load = Button("Politikayı yükle"); load.Click += (_, _) => { loaded = store.GetStockPolicy(channel.Text, shop.Text) ?? new() { Channel = channel.Text.Trim().ToLowerInvariant(), Shop = shop.Text.Trim() }; safety.Text = loaded.SafetyStock.ToString(); maximum.Text = loaded.MaximumStock?.ToString() ?? ""; enabled.IsChecked = loaded.Enabled; status.Text = loaded.Version == 0 ? "Yeni politika; kaydedilmedi." : $"Sürüm {loaded.Version} yüklendi."; }; row.Children.Add(load);
        var save = Button("Politikayı kaydet"); save.Click += (_, _) => { try { if (loaded is null || loaded.Channel != channel.Text.Trim().ToLowerInvariant() || loaded.Shop != shop.Text.Trim()) throw new InvalidOperationException("Önce aynı kanal/mağaza politikasını yükleyin."); if (!int.TryParse(safety.Text, out var safe) || safe < 0) throw new ArgumentException("Güvenlik stoğu geçersiz."); int? cap = string.IsNullOrWhiteSpace(maximum.Text) ? null : int.TryParse(maximum.Text, out var parsed) && parsed >= 0 ? parsed : throw new ArgumentException("Üst sınır geçersiz."); loaded = store.SaveStockPolicy(new() { Channel = loaded.Channel, Shop = loaded.Shop, SafetyStock = safe, MaximumStock = cap, Enabled = enabled.IsChecked == true, Version = loaded.Version }); status.Text = "Stok politikası kaydedildi; canlı stok değişmedi."; Reload(); } catch (Exception error) { status.Text = error.Message; } }; row.Children.Add(save);
        var copySourceChannel = new TextBox { Text = "etsy", Width = 100 }; var copySourceShop = new TextBox { Width = 120 }; var copyTargetChannel = new TextBox { Text = "ebay", Width = 100 }; var copyTargetShop = new TextBox { Width = 120 }; var copyRow = new WrapPanel(); Add(copyRow, "Kaynak kanal", copySourceChannel); Add(copyRow, "Kaynak mağaza", copySourceShop); Add(copyRow, "Hedef kanal", copyTargetChannel); Add(copyRow, "Hedef mağaza", copyTargetShop); var copy = Button("Politikayı çoğalt"); copy.Click += (_, _) => { try { if (MessageBox.Show("Stok politikası hedef mağazaya yerel olarak kopyalansın mı?", "Politika kopyalama", MessageBoxButton.YesNo, MessageBoxImage.Question) != MessageBoxResult.Yes) return; store.CopyStockPolicy(copySourceChannel.Text, copySourceShop.Text, copyTargetChannel.Text, copyTargetShop.Text); status.Text = "Stok politikası kopyalandı; canlı kanal değişmedi."; Reload(); } catch (Exception error) { status.Text = error.Message; } }; copyRow.Children.Add(copy); root.Children.Add(copyRow);
        var product = new ComboBox { DisplayMemberPath = "Name", MinWidth = 380 }; var preview = Button("Ürün stok preview"); preview.Click += (_, _) => { try { if (product.SelectedItem is not CatalogProduct p) throw new InvalidOperationException("Ürün seçin."); var result = store.PreviewStockDetailed(channel.Text, shop.Text, p.Id); status.Text = $"{result.Channel}/{result.Shop} · {result.Sku}: {result.Stock} → {result.AvailableStock} gösterilebilir stok · policy v{result.PolicyVersion} · ürün {result.ProductUpdatedUtc.ToLocalTime():g}. Canlı gönderim yapılmadı."; } catch (Exception error) { status.Text = error.Message; } }; var productRow = new WrapPanel(); productRow.Children.Add(new TextBlock { Text = "Ürün", Margin = new Thickness(4, 8, 2, 4), VerticalAlignment = VerticalAlignment.Center }); productRow.Children.Add(product); productRow.Children.Add(Button("Ürünleri yenile", () => product.ItemsSource = store.Products())); productRow.Children.Add(preview); root.Children.Add(productRow); root.Children.Add(status); Reload(); product.ItemsSource = store.Products(); return new ScrollViewer { Content = root, VerticalScrollBarVisibility = ScrollBarVisibility.Auto };
    }
    static FrameworkElement Price(CatalogStore store, string? directory)
    {
        var root = new StackPanel { Margin = new Thickness(14), MaxWidth = 1100 }; root.Children.Add(Text("Mağaza fiyat politikaları", 21)); root.Children.Add(Text("Formül, hedef döviz, manuel kur, minimum fiyat ve izin verilen minimum marjı tek merkezde yönetin. Kritik fiyat alanı bu kapsamda değildir.")); var grid = new DataGrid { AutoGenerateColumns = false, IsReadOnly = true, Height = 190 }; foreach (var c in new[] { ("Kanal", "Channel", 100d), ("Mağaza", "Shop", 150d), ("Döviz", "Currency", 70d), ("Kur", "TryPerUnit", 90d), ("Min fiyat", "MinimumPrice", 90d), ("Min fark", "MinimumMarginTry", 90d), ("Etkin", "Enabled", 70d), ("Sürüm", "Version", 70d) }) grid.Columns.Add(new DataGridTextColumn { Header = c.Item1, Binding = new System.Windows.Data.Binding(c.Item2), Width = c.Item3 }); root.Children.Add(grid);
        var channel = new TextBox { Text = "etsy", Width = 120 }; var shop = new TextBox { Width = 150 }; var formula = new TextBox { Text = "x", Width = 330, Height = 70, AcceptsReturn = true, TextWrapping = TextWrapping.Wrap }; var currency = new ComboBox { ItemsSource = new[] { "TRY", "USD", "EUR", "GBP" }, SelectedIndex = 0, Width = 90 }; var rate = new TextBox { Text = "1", Width = 90 }; var minimum = new TextBox { Text = "0", Width = 90 }; var margin = new TextBox { Text = "0", Width = 90 }; var enabled = new CheckBox { Content = "Etkin", IsChecked = true, Margin = new Thickness(5) }; PricePolicy? loaded = null; var status = Text(""); var row = new WrapPanel(); Add(row, "Kanal", channel); Add(row, "Mağaza", shop); Add(row, "Formül", formula); Add(row, "Döviz", currency); Add(row, "TL/1 döviz", rate); Add(row, "Min fiyat", minimum); Add(row, "Min fark TL", margin); row.Children.Add(enabled); root.Children.Add(row);
        void Reload() { grid.ItemsSource = store.ListPricePolicies(); }
        var load = Button("Politikayı yükle"); load.Click += (_, _) => { loaded = store.GetPricePolicy(channel.Text, shop.Text) ?? new() { Channel = channel.Text.Trim().ToLowerInvariant(), Shop = shop.Text.Trim() }; formula.Text = loaded.Formula; currency.SelectedItem = loaded.Currency; rate.Text = loaded.TryPerUnit.ToString(CultureInfo.InvariantCulture); minimum.Text = loaded.MinimumPrice.ToString(CultureInfo.InvariantCulture); margin.Text = loaded.MinimumMarginTry.ToString(CultureInfo.InvariantCulture); enabled.IsChecked = loaded.Enabled; status.Text = loaded.Version == 0 ? "Yeni politika; kaydedilmedi." : $"Sürüm {loaded.Version} yüklendi."; }; row.Children.Add(load);
        static decimal Number(string value) { if (!decimal.TryParse(value, NumberStyles.AllowDecimalPoint | NumberStyles.AllowLeadingSign, CultureInfo.InvariantCulture, out var result)) throw new ArgumentException("Ondalık ayırıcı nokta olmalı."); return result; }
        var save = Button("Politikayı kaydet"); save.Click += (_, _) => { try { if (loaded is null || loaded.Channel != channel.Text.Trim().ToLowerInvariant() || loaded.Shop != shop.Text.Trim()) throw new InvalidOperationException("Önce aynı kanal/mağaza politikasını yükleyin."); loaded = store.SavePricePolicy(new() { Channel = loaded.Channel, Shop = loaded.Shop, Formula = formula.Text, Currency = currency.SelectedItem?.ToString() ?? "", TryPerUnit = Number(rate.Text), MinimumPrice = Number(minimum.Text), MinimumMarginTry = Number(margin.Text), Enabled = enabled.IsChecked == true, Version = loaded.Version }); status.Text = "Fiyat politikası kaydedildi; canlı fiyat değişmedi."; Reload(); } catch (Exception error) { status.Text = error.Message; } }; row.Children.Add(save);
        var sourceChannel = new TextBox { Text = "etsy", Width = 100 }; var sourceShop = new TextBox { Width = 120 }; var targetChannel = new TextBox { Text = "ebay", Width = 100 }; var targetShop = new TextBox { Width = 120 }; var copyRow = new WrapPanel(); Add(copyRow, "Kaynak kanal", sourceChannel); Add(copyRow, "Kaynak mağaza", sourceShop); Add(copyRow, "Hedef kanal", targetChannel); Add(copyRow, "Hedef mağaza", targetShop); var copy = Button("Politikayı çoğalt"); copy.Click += (_, _) => { try { if (MessageBox.Show("Fiyat politikası hedef mağazaya yerel olarak kopyalansın mı?", "Politika kopyalama", MessageBoxButton.YesNo, MessageBoxImage.Question) != MessageBoxResult.Yes) return; store.CopyPricePolicy(sourceChannel.Text, sourceShop.Text, targetChannel.Text, targetShop.Text); status.Text = "Fiyat politikası kopyalandı; canlı kanal değişmedi."; Reload(); } catch (Exception error) { status.Text = error.Message; } }; copyRow.Children.Add(copy); root.Children.Add(copyRow);
        var product = new ComboBox { DisplayMemberPath = "Name", MinWidth = 380 }; var productRow = new WrapPanel(); productRow.Children.Add(new TextBlock { Text = "Ürün", Margin = new Thickness(4, 8, 2, 4), VerticalAlignment = VerticalAlignment.Center }); productRow.Children.Add(product); productRow.Children.Add(Button("Ürünleri yenile", () => product.ItemsSource = store.Products())); var preview = Button("Ürün fiyat preview"); preview.Click += (_, _) => { try { if (product.SelectedItem is not CatalogProduct p) throw new InvalidOperationException("Ürün seçin."); var result = store.PreviewPriceDetailed(channel.Text, shop.Text, p.Id); status.Text = $"{result.Channel}/{result.Shop} · {result.Sku}: {result.Price} {result.Currency} · formül {result.FormulaPriceTry:N2} TL · policy v{result.PolicyVersion} · ürün {result.ProductUpdatedUtc.ToLocalTime():g}. Canlı gönderim yapılmadı."; } catch (Exception error) { status.Text = error.Message; } }; productRow.Children.Add(preview); root.Children.Add(productRow); root.Children.Add(status); Reload(); product.ItemsSource = store.Products(); return new ScrollViewer { Content = root, VerticalScrollBarVisibility = ScrollBarVisibility.Auto };
    }
    static void Add(Panel panel, string label, UIElement control) { panel.Children.Add(new TextBlock { Text = label, Margin = new Thickness(4, 8, 2, 2) }); panel.Children.Add(control); }
    static TextBlock Text(string value, int size = 12) => new() { Text = value, FontSize = size, TextWrapping = TextWrapping.Wrap, Margin = new Thickness(3, 4, 3, 7), Foreground = Brushes.DarkSlateGray };
    static Button Button(string text) => new() { Content = text, Margin = new Thickness(3, 5, 3, 5) };
    static Button Button(string text, Action action) { var button = Button(text); button.Click += (_, _) => action(); return button; }
}
