using Microsoft.Data.Sqlite;
using System.IO;

namespace TrMarketplaceHubDesktop.Catalog;
public enum AutomationKind { Stock, Price }
public sealed class AutomationJob { public string Id {get;set;}=Guid.NewGuid().ToString("N"); public AutomationKind Kind {get;set;} public int IntervalMinutes {get;set;}=30; public DateTime NextRunUtc {get;set;}=DateTime.UtcNow; public DateTime? LockedUntilUtc {get;set;} public string LastError {get;set;}=""; }
public sealed class AutomationStore
{
 readonly string connectionString;
 public AutomationStore(string? directory=null){directory??=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"MonoBridgeDesktop");Directory.CreateDirectory(directory);connectionString=new SqliteConnectionStringBuilder{DataSource=Path.Combine(directory,"catalog.db")}.ToString();using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="CREATE TABLE IF NOT EXISTS AutomationJobs(Id TEXT PRIMARY KEY, Kind INTEGER NOT NULL, IntervalMinutes INTEGER NOT NULL, NextRunUtc TEXT NOT NULL, LockedUntilUtc TEXT NULL, LastError TEXT NOT NULL)";cmd.ExecuteNonQuery();}
 SqliteConnection Open(){var c=new SqliteConnection(connectionString);c.Open();return c;}
 public AutomationJob Save(AutomationJob job){if(job.IntervalMinutes<1)throw new InvalidOperationException("Otomasyon aralığı en az 1 dakika olmalı.");using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="INSERT INTO AutomationJobs(Id,Kind,IntervalMinutes,NextRunUtc,LockedUntilUtc,LastError) VALUES($id,$kind,$interval,$next,$lock,$error) ON CONFLICT(Id) DO UPDATE SET Kind=excluded.Kind,IntervalMinutes=excluded.IntervalMinutes,NextRunUtc=excluded.NextRunUtc,LockedUntilUtc=excluded.LockedUntilUtc,LastError=excluded.LastError";cmd.Parameters.AddWithValue("$id",job.Id);cmd.Parameters.AddWithValue("$kind",(int)job.Kind);cmd.Parameters.AddWithValue("$interval",job.IntervalMinutes);cmd.Parameters.AddWithValue("$next",job.NextRunUtc.ToString("O"));cmd.Parameters.AddWithValue("$lock",job.LockedUntilUtc.HasValue?job.LockedUntilUtc.Value.ToString("O"):DBNull.Value);cmd.Parameters.AddWithValue("$error",job.LastError);cmd.ExecuteNonQuery();return job;}
 public AutomationJob Get(string id){using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="SELECT Id,Kind,IntervalMinutes,NextRunUtc,LockedUntilUtc,LastError FROM AutomationJobs WHERE Id=$id";cmd.Parameters.AddWithValue("$id",id);using var r=cmd.ExecuteReader();if(!r.Read())throw new InvalidOperationException("Otomasyon işi bulunamadı.");return Read(r);}
 static AutomationJob Read(SqliteDataReader r)=>new(){Id=r.GetString(0),Kind=(AutomationKind)r.GetInt32(1),IntervalMinutes=r.GetInt32(2),NextRunUtc=DateTime.Parse(r.GetString(3),null,System.Globalization.DateTimeStyles.RoundtripKind),LockedUntilUtc=r.IsDBNull(4)?null:DateTime.Parse(r.GetString(4),null,System.Globalization.DateTimeStyles.RoundtripKind),LastError=r.GetString(5)};
 public bool TryClaim(string id,DateTime nowUtc,TimeSpan lease){using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="UPDATE AutomationJobs SET LockedUntilUtc=$lock WHERE Id=$id AND NextRunUtc<=$now AND (LockedUntilUtc IS NULL OR LockedUntilUtc<$now)";cmd.Parameters.AddWithValue("$lock",(nowUtc+lease).ToString("O"));cmd.Parameters.AddWithValue("$id",id);cmd.Parameters.AddWithValue("$now",nowUtc.ToString("O"));return cmd.ExecuteNonQuery()==1;}
 public void Complete(string id,DateTime nowUtc){var job=Get(id);using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="UPDATE AutomationJobs SET NextRunUtc=$next,LockedUntilUtc=NULL,LastError='' WHERE Id=$id";cmd.Parameters.AddWithValue("$next",nowUtc.AddMinutes(job.IntervalMinutes).ToString("O"));cmd.Parameters.AddWithValue("$id",id);cmd.ExecuteNonQuery();}
 public void Fail(string id,string error){using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="UPDATE AutomationJobs SET NextRunUtc=$now,LockedUntilUtc=NULL,LastError=$error WHERE Id=$id";cmd.Parameters.AddWithValue("$now",DateTime.UtcNow.ToString("O"));cmd.Parameters.AddWithValue("$error",error.Trim());cmd.Parameters.AddWithValue("$id",id);cmd.ExecuteNonQuery();}
}
