using Microsoft.Data.Sqlite;
using System.IO;
using System.Text.Json;
namespace TrMarketplaceHubDesktop.Catalog;
public partial class CatalogStore
{
 readonly string connectionString;
 readonly string dataDirectory;
 public CatalogPage Search(string search,int offset=0,int limit=200,CatalogFilter? filter=null, CancellationToken cancellationToken=default)
 {
  cancellationToken.ThrowIfCancellationRequested();
  if(offset<0||limit<1||limit>1000)throw new ArgumentOutOfRangeException(nameof(limit),"Sayfa boyutu 1–1000, başlangıç sıfır veya daha büyük olmalı.");
  filter??=new();
  foreach(var values in new[]{filter.Brands,filter.Categories,filter.Skus,filter.SourceIds})if(values.Length>100||values.Sum(v=>v.Length)>6000)throw new ArgumentException("Filtre en fazla 100 değer ve 6000 karakter olabilir.");
  using var c=Open();using var tx=c.BeginTransaction(deferred:true);
  // Substring search cannot use a B-tree index; filter/count in SQLite and deserialize only the requested page.
  var where=" WHERE ($all=1 OR uifold(json_extract(Json,'$.Name')) LIKE $q ESCAPE '\\' OR uifold(json_extract(Json,'$.Sku')) LIKE $q ESCAPE '\\' OR uifold(json_extract(Json,'$.Barcode')) LIKE $q ESCAPE '\\' OR uifold(json_extract(Json,'$.Brand')) LIKE $q ESCAPE '\\' OR uifold(json_extract(Json,'$.Category')) LIKE $q ESCAPE '\\'";
  where += ") AND ($active=-1 OR COALESCE(json_extract(Json,'$.Active'),1)=$active) AND ($description=-1 OR (length(trim(COALESCE(json_extract(Json,'$.Description'),'')))>0)=$description) AND ($image=-1 OR (length(trim(COALESCE(json_extract(Json,'$.ImageUrls'),'')))>0)=$image) AND ($minPrice IS NULL OR json_extract(Json,'$.Price') >= $minPrice) AND ($maxPrice IS NULL OR json_extract(Json,'$.Price') <= $maxPrice) AND ($minCost IS NULL OR json_extract(Json,'$.Cost') >= $minCost) AND ($maxCost IS NULL OR json_extract(Json,'$.Cost') <= $maxCost) AND ($minStock IS NULL OR json_extract(Json,'$.Stock') >= $minStock) AND ($maxStock IS NULL OR json_extract(Json,'$.Stock') <= $maxStock) AND ($sourceMissing IS NULL OR COALESCE(json_extract(Json,'$.SourceMissing'),0)=$sourceMissing)";
  var extra=new Dictionary<string,string>();
  foreach(var (field,values) in new[]{("Brand",filter.Brands),("Category",filter.Categories),("Sku",filter.Skus),("SourceId",filter.SourceIds)}){
   if(values.Length==0)continue;
   var names=new List<string>();foreach(var value in values){var clean=value.Trim();if(clean.Length==0)continue;var key="$filter"+extra.Count;extra.Add(key,clean);names.Add(key);}if(names.Count==0)continue;
   where+=$" AND json_extract(Json,'$.{field}') COLLATE NOCASE IN ({string.Join(",",names)})";
  }
  // #903: field-level freshness -- each field's recorded observation against its own source's cutoff, as SQL, so the page and the count agree.
  if(filter.Freshness is {Length:>0}){var parts=filter.Freshness.Split(':',2);where+=" AND ("+ProductFreshness.FilterSql(parts[0],parts.Length>1?parts[1]:ProductFreshness.Any,Read<XmlSource>(c,"Sources",tx),DateTime.UtcNow,extra)+")";}
  search=search.Trim();var pattern="%"+UiSearch.Fold(search).Replace("\\","\\\\").Replace("%","\\%").Replace("_","\\_")+"%";
  void Params(SqliteCommand cmd){cmd.Transaction=tx;cmd.Parameters.AddWithValue("$all",search.Length==0?1:0);cmd.Parameters.AddWithValue("$q",pattern);cmd.Parameters.AddWithValue("$active",filter.Active.HasValue?(filter.Active.Value?1:0):-1);cmd.Parameters.AddWithValue("$description",filter.DescriptionPresent.HasValue?(filter.DescriptionPresent.Value?1:0):-1);cmd.Parameters.AddWithValue("$image",filter.ImagePresent.HasValue?(filter.ImagePresent.Value?1:0):-1);cmd.Parameters.AddWithValue("$minPrice",(object?)filter.MinPrice??DBNull.Value);cmd.Parameters.AddWithValue("$maxPrice",(object?)filter.MaxPrice??DBNull.Value);cmd.Parameters.AddWithValue("$minCost",(object?)filter.MinCost??DBNull.Value);cmd.Parameters.AddWithValue("$maxCost",(object?)filter.MaxCost??DBNull.Value);cmd.Parameters.AddWithValue("$minStock",(object?)filter.MinStock??DBNull.Value);cmd.Parameters.AddWithValue("$maxStock",(object?)filter.MaxStock??DBNull.Value);cmd.Parameters.AddWithValue("$sourceMissing",filter.SourceMissing.HasValue?(filter.SourceMissing.Value?1:0):DBNull.Value);foreach(var pair in extra)cmd.Parameters.AddWithValue(pair.Key,pair.Value);}
  int total,inStock,linked;
  using(var count=c.CreateCommand()){cancellationToken.ThrowIfCancellationRequested();Params(count);count.CommandText="SELECT COUNT(*),COALESCE(SUM(CASE WHEN json_extract(Json,'$.Stock')>0 THEN 1 ELSE 0 END),0),COALESCE(SUM(CASE WHEN COALESCE(json_extract(Json,'$.EtsyListingId'),'')<>'' THEN 1 ELSE 0 END),0) FROM CatalogProducts"+where;using var reader=count.ExecuteReader();reader.Read();total=reader.GetInt32(0);inStock=reader.GetInt32(1);linked=reader.GetInt32(2);}
  var sort = filter.SortBy.Trim().ToLowerInvariant() switch { "sku" => "Sku", "barcode" => "Barcode", "price" => "Price", "cost" => "Cost", "stock" => "Stock", "updated" => "UpdatedUtc", _ => "Name" }; var direction = filter.SortDescending ? " DESC" : " ASC";
  var items=new List<CatalogProduct>();using(var page=c.CreateCommand()){cancellationToken.ThrowIfCancellationRequested();Params(page);page.CommandText="SELECT Json FROM CatalogProducts"+where+$" ORDER BY json_extract(Json,'$.{sort}') COLLATE NOCASE{direction},Id LIMIT $limit OFFSET $offset";page.Parameters.AddWithValue("$limit",limit);page.Parameters.AddWithValue("$offset",offset);using var reader=page.ExecuteReader();while(reader.Read()){cancellationToken.ThrowIfCancellationRequested();items.Add(JsonSerializer.Deserialize<CatalogProduct>(reader.GetString(0))!);}}
  tx.Commit();return new(items,total,inStock,linked);
 }
 public CatalogStore(string? directory=null){directory??=System.IO.Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"MonoBridgeDesktop");Directory.CreateDirectory(directory);dataDirectory=directory;connectionString=new SqliteConnectionStringBuilder{DataSource=System.IO.Path.Combine(directory,"catalog.db"),DefaultTimeout=15,Pooling=true}.ToString();using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="PRAGMA journal_mode=WAL;PRAGMA synchronous=NORMAL;PRAGMA busy_timeout=15000;CREATE TABLE IF NOT EXISTS Sources(Id TEXT PRIMARY KEY, Json TEXT NOT NULL);CREATE TABLE IF NOT EXISTS CatalogProducts(Id TEXT PRIMARY KEY, Json TEXT NOT NULL);CREATE INDEX IF NOT EXISTS IX_CatalogProducts_Sku ON CatalogProducts(json_extract(Json,'$.Sku') COLLATE NOCASE);CREATE INDEX IF NOT EXISTS IX_CatalogProducts_Barcode ON CatalogProducts(json_extract(Json,'$.Barcode') COLLATE NOCASE);CREATE INDEX IF NOT EXISTS IX_CatalogProducts_Brand ON CatalogProducts(json_extract(Json,'$.Brand') COLLATE NOCASE);CREATE INDEX IF NOT EXISTS IX_CatalogProducts_Category ON CatalogProducts(json_extract(Json,'$.Category') COLLATE NOCASE);";cmd.ExecuteNonQuery();InitializeOrderStock(c);InitializeStockPolicies(c);InitializePricePolicies(c);SchemaVersion.Ensure(c);SourceRevisionStore.EnsureTable(c);EnsureSightings(c);}
 SqliteConnection Open(){var c=SqliteConnectionPolicy.Open(connectionString);c.CreateFunction("uifold",(string? text)=>UiSearch.Fold(text),isDeterministic:true);return c;}
 static List<T> Read<T>(SqliteConnection c,string table,SqliteTransaction? tx=null){using var cmd=c.CreateCommand();cmd.Transaction=tx;cmd.CommandText=$"SELECT Json FROM {table}";using var r=cmd.ExecuteReader();var list=new List<T>();while(r.Read())list.Add(JsonSerializer.Deserialize<T>(r.GetString(0))!);return list;}
 static void Put<T>(SqliteConnection c,string table,string id,T value,SqliteTransaction? tx=null){using var cmd=c.CreateCommand();cmd.Transaction=tx;cmd.CommandText=$"INSERT INTO {table}(Id,Json) VALUES($id,$json) ON CONFLICT(Id) DO UPDATE SET Json=excluded.Json";cmd.Parameters.AddWithValue("$id",id);cmd.Parameters.AddWithValue("$json",JsonSerializer.Serialize(value));cmd.ExecuteNonQuery();}
 public List<XmlSource> Sources(){using var c=Open();return Read<XmlSource>(c,"Sources");}
 public void SaveSource(XmlSource source)=>SaveSource(source,SourceRevisionStore.SaveReason);
 // #893: every configuration change is one immutable revision written in the same transaction as the source; a state-only save appends nothing; a record loaded at a revision that is no longer current is a concurrent edit and is refused before anything is written (a never-loaded record carries no expectation).
 public void SaveSource(XmlSource source,string reason){XmlCatalog.ValidateSource(source);if(string.IsNullOrWhiteSpace(source.Id))throw new InvalidOperationException("Kaynak kimliği boş.");using var c=Open();using var tx=c.BeginTransaction();using var find=c.CreateCommand();find.Transaction=tx;find.CommandText="SELECT Json FROM Sources WHERE Id=$id";find.Parameters.AddWithValue("$id",source.Id);if(find.ExecuteScalar() is string json){var old=JsonSerializer.Deserialize<XmlSource>(json)!;if(source.ConfigRevision>0&&source.ConfigRevision!=old.ConfigRevision)throw new SourceRevisionConflictException(source.ConfigRevision,old.ConfigRevision);if(!MappingEquivalent(old,source))source.MappingRevision=Math.Max(source.MappingRevision,old.MappingRevision)+1;source.LastAppliedMappingRevision=Math.Max(source.LastAppliedMappingRevision,old.LastAppliedMappingRevision);if(string.IsNullOrWhiteSpace(source.LastMappingShapeFingerprint))source.LastMappingShapeFingerprint=old.LastMappingShapeFingerprint;if(string.IsNullOrWhiteSpace(source.LastSuccessfulFeedHash))source.LastSuccessfulFeedHash=old.LastSuccessfulFeedHash;if(source.LastSuccessfulFeedUtc is null)source.LastSuccessfulFeedUtc=old.LastSuccessfulFeedUtc;if(source.LastSuccessfulFeedCount==0)source.LastSuccessfulFeedCount=old.LastSuccessfulFeedCount;if(source.LastFeedState=="NEVER")source.LastFeedState=old.LastFeedState;}source.ConfigRevision=SourceRevisionStore.Append(c,tx,source,reason);Put(c,"Sources",source.Id,source,tx);tx.Commit();}
 public IReadOnlyList<SourceRevisionSnapshot> SourceRevisions(string sourceId){using var c=Open();return SourceRevisionStore.List(c,sourceId);}
 public SourceRevisionSnapshot? SourceRevision(string sourceId,int revision){using var c=Open();return SourceRevisionStore.Get(c,sourceId,revision);}
 // #893: a rollback never rewrites history -- the chosen revision's configuration goes onto the current record and the save appends a new revision naming it.
 public XmlSource RestoreSourceRevision(string sourceId,int revision){var current=Sources().FirstOrDefault(x=>x.Id==sourceId)??throw new InvalidOperationException("Kaynak bulunamadı.");var snapshot=SourceRevision(sourceId,revision)??throw new InvalidOperationException($"Kaynağın {revision} numaralı sürümü yok.");var config=snapshot.Config??throw new InvalidOperationException("Sürüm kaydı okunamadı.");config.ApplyTo(current);SaveSource(current,$"geri alma: rev. {revision}");return current;}
 // #897: when a feed last carried a product -- one row per (source, product), written inside the import transaction so the fallback verdict can judge freshness per source without rewriting the product record.
 static void EnsureSightings(SqliteConnection c){using var cmd=c.CreateCommand();cmd.CommandText="CREATE TABLE IF NOT EXISTS SourceSightings(SourceId TEXT NOT NULL,ProductId TEXT NOT NULL,SeenUtc TEXT NOT NULL,PRIMARY KEY(SourceId,ProductId))";cmd.ExecuteNonQuery();}
 static void RecordSighting(SqliteConnection c,SqliteTransaction tx,string sourceId,string productId,DateTime seenUtc){var utc=DateTime.SpecifyKind(seenUtc.Kind==DateTimeKind.Local?seenUtc.ToUniversalTime():seenUtc,DateTimeKind.Utc);using var cmd=c.CreateCommand();cmd.Transaction=tx;cmd.CommandText="INSERT INTO SourceSightings(SourceId,ProductId,SeenUtc) VALUES($s,$p,$t) ON CONFLICT(SourceId,ProductId) DO UPDATE SET SeenUtc=excluded.SeenUtc";cmd.Parameters.AddWithValue("$s",sourceId);cmd.Parameters.AddWithValue("$p",productId);cmd.Parameters.AddWithValue("$t",utc.ToString("O",System.Globalization.CultureInfo.InvariantCulture));cmd.ExecuteNonQuery();}
 static void DeleteSightings(SqliteConnection c,SqliteTransaction tx,string productId){using var cmd=c.CreateCommand();cmd.Transaction=tx;cmd.CommandText="DELETE FROM SourceSightings WHERE ProductId=$p";cmd.Parameters.AddWithValue("$p",productId);cmd.ExecuteNonQuery();}
 // #902: a source remap moves a product's home to another source and nothing else -- the canonical id, the SKU, the barcode, the field origins, the sightings and every channel listing keyed by the id stay; recorded in the audit trail.
 public CatalogProduct RemapProductSource(string productId,string newSourceId,string reason=""){ArgumentException.ThrowIfNullOrWhiteSpace(productId);ArgumentException.ThrowIfNullOrWhiteSpace(newSourceId);CatalogProduct product;string fromName,toName;using(var c=Open()){using var tx=c.BeginTransaction();using var find=c.CreateCommand();find.Transaction=tx;find.CommandText="SELECT Json FROM CatalogProducts WHERE Id=$id";find.Parameters.AddWithValue("$id",productId);var json=find.ExecuteScalar() as string??throw new InvalidOperationException("Ürün bulunamadı.");product=JsonSerializer.Deserialize<CatalogProduct>(json)!;var sources=Read<XmlSource>(c,"Sources",tx);var target=sources.FirstOrDefault(x=>x.Id==newSourceId)??throw new InvalidOperationException("Hedef kaynak bulunamadı.");if(product.SourceId==newSourceId)return product;fromName=sources.FirstOrDefault(x=>x.Id==product.SourceId)?.Name??(product.SourceId.Length==0?"kaynaksız":"silinmiş kaynak");toName=target.Name;product.SourceId=newSourceId;product.SourceKind="xml";product.UpdatedUtc=DateTime.UtcNow;Put(c,"CatalogProducts",product.Id,product,tx);tx.Commit();}try{new AuditStore(dataDirectory).Append(new AuditEvent{Module="import",Action=ProductIdentity.RemapAction,ProductId=product.Id,Outcome="Info",Detail=AuditStore.Redact($"kaynak eşlemesi: {fromName} → {toName}"+(string.IsNullOrWhiteSpace(reason)?"":" · "+reason.Trim()))});}catch(Exception){}return product;}
 // #901: what still points at a source -- products, field origins, sightings, run history, quality records, a running import -- and what is the source's own (revisions, cached feeds, a saved credential) and goes with it.
 public SourceReferences SourceReferences(string sourceId,DateTime? nowUtc=null){ArgumentException.ThrowIfNullOrWhiteSpace(sourceId);var now=nowUtc??DateTime.UtcNow;var products=Products();var linked=products.Count(p=>p.SourceId==sourceId);var origins=products.Sum(p=>p.FieldOrigins?.Values.Count(o=>o.SourceId==sourceId)??0);int sightings;using(var c=Open()){using var cmd=c.CreateCommand();cmd.CommandText="SELECT COUNT(*) FROM SourceSightings WHERE SourceId=$s";cmd.Parameters.AddWithValue("$s",sourceId);sightings=Convert.ToInt32(cmd.ExecuteScalar());}var runs=new XmlRunStore(dataDirectory).List(sourceId,1000);var running=runs.Any(r=>r.Status=="Running"&&(r.LeaseUntilUtc is null||r.LeaseUntilUtc>now));int quality=0;try{quality=new DataQualityStore(dataDirectory).List().Count(i=>i.SourceId==sourceId);}catch(Exception){}int cached=0;try{cached=FeedCache.List(dataDirectory,sourceId).Count;}catch(Exception){}var revisions=SourceRevisions(sourceId).Count;var credential=Guid.TryParse(sourceId,out _)&&XmlAuthStore.Presence(sourceId,dataDirectory)==CredentialPresence.Saved;return new(linked,origins,sightings,runs.Count,quality,running,revisions,cached,credential);}
 // #901: a guarded hard delete -- refused with the references when anything still points at the source (nothing changes); otherwise the record, its revisions and its sightings go in one transaction, then its cached feeds and its saved credential.
 public SourceDeleteVerdict DeleteSource(string sourceId,DateTime? nowUtc=null){var source=Sources().SingleOrDefault(x=>x.Id==sourceId)??throw new InvalidOperationException("Kaynak bulunamadı.");var verdict=SourceDeleteGuard.Evaluate(source,SourceReferences(sourceId,nowUtc));if(!verdict.Allowed)return verdict;using(var c=Open()){using var tx=c.BeginTransaction();foreach(var (table,column) in new[]{("Sources","Id"),("SourceRevisions","SourceId"),("SourceSightings","SourceId")}){using var cmd=c.CreateCommand();cmd.Transaction=tx;cmd.CommandText=$"DELETE FROM {table} WHERE {column}=$id";cmd.Parameters.AddWithValue("$id",sourceId);cmd.ExecuteNonQuery();}tx.Commit();}try{XmlAuthStore.Delete(sourceId,dataDirectory);}catch(Exception){}try{var folder=Path.Combine(FeedCache.Root(dataDirectory),sourceId);if(Directory.Exists(folder))Directory.Delete(folder,true);}catch(Exception){}return verdict;}
 /// <summary>#900: every sighting at once, keyed by product then source (UTC), for previews over many products.</summary>
 public IReadOnlyDictionary<string,IReadOnlyDictionary<string,DateTime>> SightingsByProduct(){var all=new Dictionary<string,Dictionary<string,DateTime>>(StringComparer.Ordinal);using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="SELECT ProductId,SourceId,SeenUtc FROM SourceSightings";using var reader=cmd.ExecuteReader();while(reader.Read()){if(!DateTime.TryParse(reader.GetString(2),System.Globalization.CultureInfo.InvariantCulture,System.Globalization.DateTimeStyles.RoundtripKind,out var at))continue;var product=reader.GetString(0);if(!all.TryGetValue(product,out var seen)){seen=new Dictionary<string,DateTime>(StringComparer.Ordinal);all[product]=seen;}seen[reader.GetString(1)]=at;}return all.ToDictionary(kv=>kv.Key,kv=>(IReadOnlyDictionary<string,DateTime>)kv.Value,StringComparer.Ordinal);}
 /// <summary>#897: when each source last carried the product (UTC), for the fallback verdict.</summary>
 public IReadOnlyDictionary<string,DateTime> Sightings(string productId){var seen=new Dictionary<string,DateTime>(StringComparer.Ordinal);using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="SELECT SourceId,SeenUtc FROM SourceSightings WHERE ProductId=$p";cmd.Parameters.AddWithValue("$p",productId);using var reader=cmd.ExecuteReader();while(reader.Read()){if(DateTime.TryParse(reader.GetString(1),System.Globalization.CultureInfo.InvariantCulture,System.Globalization.DateTimeStyles.RoundtripKind,out var at))seen[reader.GetString(0)]=at;}return seen;}
 // #895: the fields a feed writes on a new product -- every one it maps; an existing product's written set is decided field by field above.
 static IEnumerable<string> WrittenFields(XmlSource source,CatalogProduct? old){var fields=new List<string>{"Cost","Price","Currency","Stock","Name","Description","ImageUrls"};if(source.Fields.ContainsKey("Gtin"))fields.Add("Gtin");if(source.Fields.ContainsKey("Weight"))fields.Add("WeightText");if(source.Fields.ContainsKey("Dimensions"))fields.Add("DimensionsText"); /* #908 */if(source.Fields.ContainsKey("TaxClass"))fields.Add("TaxClass"); /* #909 */if(source.Fields.ContainsKey("CountryOfOrigin"))fields.Add("CountryOfOrigin"); /* #910 */return fields;}
 // #896: a decision's words go onto the field's origin -- the winner's when the feed wrote it, the holder's when the feed was refused -- so the product carries the explanation across a restart; true when any words changed.
 static bool MarkDecisions(CatalogProduct product,IReadOnlyList<SourcePriorityDecision> marks,Func<string,string> nameOf){if(marks.Count==0)return false;var changed=false;product.FieldOrigins??=new Dictionary<string,FieldOrigin>(StringComparer.Ordinal);foreach(var d in marks){if(!product.FieldOrigins.TryGetValue(d.Field,out var origin)){origin=new FieldOrigin{Kind=FieldProvenance.ManualKind,ObservedUtc=d.DecidedUtc};product.FieldOrigins[d.Field]=origin;changed=true;}var words=d.Words(nameOf);if(origin.Decision!=words){origin.Decision=words;changed=true;}}return changed;}
 // #910: one audit row per change of the resolved country of origin a feed made -- codes only, after the commit like the decisions.
 void WriteOriginChanges(List<(string ProductId,OriginChange Change)> changes){if(changes.Count==0)return;try{var audit=new AuditStore(dataDirectory);foreach(var (productId,change) in changes)audit.Append(ProductOrigin.ToAudit(productId,change,FieldProvenance.FeedKind));}catch(Exception){}}
 void WriteDecisions(IReadOnlyList<SourcePriorityDecision> decisions,Func<string,string> nameOf){if(decisions.Count==0)return;try{var audit=new AuditStore(dataDirectory);foreach(var d in decisions)audit.Append(SourcePriority.ToAudit(d,nameOf));}catch(Exception){}}
 static bool MappingEquivalent(XmlSource left,XmlSource right)=>left.ItemPath==right.ItemPath&&left.DecimalSeparator==right.DecimalSeparator&&left.NumberCultureName==right.NumberCultureName&&left.Fields.OrderBy(x=>x.Key,StringComparer.OrdinalIgnoreCase).SequenceEqual(right.Fields.OrderBy(x=>x.Key,StringComparer.OrdinalIgnoreCase));
 public List<CatalogProduct> Products(string search=""){using var c=Open();return Read<CatalogProduct>(c,"CatalogProducts").Where(p=>search==""||new[]{p.Name,p.Sku,p.Barcode,p.Brand,p.Category}.Any(v=>UiSearch.Matches(v,search))).ToList();}
 // The blocking rules live in ProductValidation (#803) so the workspace's summary panel and this refusal are
 // the same rule set: a panel that says "saveable" while the store throws -- or the reverse -- is the failure
 // mode of writing them twice. A null property is still guarded here, because the evaluator reads them.
 static void Valid(CatalogProduct p){
  if(p.Mpn==null||p.InvoiceName==null||p.Subtitle==null||p.Shelf==null||p.Name==null||p.Sku==null||p.Barcode==null||p.Brand==null||p.Category==null||p.Description==null||p.Currency==null)throw new InvalidOperationException("Ürün metin alanları boş bırakılabilir ama null olamaz.");
  if(ProductValidation.BlockingMessage(p) is {} problem)throw new InvalidOperationException(problem);
 }
 public CatalogProduct? FindProduct(string id){using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="SELECT Json FROM CatalogProducts WHERE Id=$id";cmd.Parameters.AddWithValue("$id",id);return cmd.ExecuteScalar() is string json?JsonSerializer.Deserialize<CatalogProduct>(json):null;}
 public void SaveProduct(CatalogProduct product){product.Name=TitleNormalizer.Normalize(product.Name).Normalized; /* #905: one pipeline for every title write */if(ProductUnits.Apply(product,System.Globalization.CultureInfo.CurrentCulture.Name,FindProduct(product.Id)).FirstOrDefault(f=>f.Blocking) is {} unitBlock)throw new InvalidOperationException(unitBlock.Message); /* #907: the operator's text, read the operator's way; #908: an unchanged text keeps its stored value */ProductTaxClass.Apply(product,FieldProvenance.ManualKind,DateTime.UtcNow); /* #909: a known class sets the VAT rate; a change is kept in the history */ProductOrigin.Apply(product); /* #910: the code beside the value as given */Valid(product);using var c=Open();using var tx=c.BeginTransaction();using var find=c.CreateCommand();find.Transaction=tx;find.CommandText="SELECT Json FROM CatalogProducts WHERE Id=$id";find.Parameters.AddWithValue("$id",product.Id);var json=find.ExecuteScalar() as string??throw new InvalidOperationException("Ürün bulunamadı.");var old=JsonSerializer.Deserialize<CatalogProduct>(json)!;if(old.SourceId!=product.SourceId||old.Sku!=product.Sku||old.Barcode!=product.Barcode)throw new InvalidOperationException("Ürün kimliği elle değiştirilemez.");EnsureUniqueIdentity(c,tx,product);if(product.UpdatedUtc!=old.UpdatedUtc)throw new InvalidOperationException("Ürün başka bir işlemde güncellendi. Yenileyip tekrar düzenleyin.");if(product.Price!=old.Price||product.Currency!=old.Currency){product.FormulaPriceTry=null;product.AppliedTryRate=null;product.FxRateDate=null;}FieldProvenance.StampManual(old,product,DateTime.UtcNow);ProductDimensions.Apply(old,product,DateTime.UtcNow); /* #908: a typed desi is the operator's; a cleared or derived one follows the box */var originChange=ProductOrigin.Change(ProductOrigin.Snapshot(old),product); /* #910 */var lockChanges=ProductLocks.Stamp(old,product,DateTime.UtcNow);product.UpdatedUtc=DateTime.UtcNow;Put(c,"CatalogProducts",product.Id,product,tx);tx.Commit();
 // #904: every lock switched on this save is one audit row -- the label and the operator's reason, never a value.
 if(lockChanges.Count>0){try{var audit=new AuditStore(dataDirectory);foreach(var change in lockChanges)audit.Append(ProductLocks.ToAudit(product,change));}catch(Exception){}}
 // #910: a change of the resolved country of origin is one audit row -- codes and who, never the text.
 if(originChange is not null){try{new AuditStore(dataDirectory).Append(ProductOrigin.ToAudit(product.Id,originChange,FieldProvenance.ManualKind));}catch(Exception){}}
 // #930: the saved price is a snapshot; a jump against the previous one is a review item, never a correction.
 try{new PriceAnomalyStore(dataDirectory).Observe(product,FieldProvenance.ManualKind,DateTime.UtcNow);}catch(Exception){}}
 static void EnsureUniqueIdentity(SqliteConnection c,SqliteTransaction tx,CatalogProduct product){using var cmd=c.CreateCommand();cmd.Transaction=tx;cmd.CommandText="SELECT Json FROM CatalogProducts WHERE Id<>$id AND ((json_extract(Json,'$.Sku')=$sku AND $sku<>'') OR (json_extract(Json,'$.Barcode')=$barcode AND $barcode<>'')) LIMIT 1";cmd.Parameters.AddWithValue("$id",product.Id);cmd.Parameters.AddWithValue("$sku",product.Sku.Trim());cmd.Parameters.AddWithValue("$barcode",product.Barcode.Trim());if(cmd.ExecuteScalar() is string)throw new InvalidOperationException("SKU veya barkod başka bir üründe zaten kayıtlı.");}
 public void DeleteProduct(CatalogProduct product){using var c=Open();using var tx=c.BeginTransaction();DeleteSightings(c,tx,product.Id);using var find=c.CreateCommand();find.Transaction=tx;find.CommandText="SELECT Json FROM CatalogProducts WHERE Id=$id";find.Parameters.AddWithValue("$id",product.Id);var json=find.ExecuteScalar() as string??throw new InvalidOperationException("Ürün bulunamadı.");var old=JsonSerializer.Deserialize<CatalogProduct>(json)!;if(old.UpdatedUtc!=product.UpdatedUtc)throw new InvalidOperationException("Ürün değişti; yenileyip tekrar deneyin.");if(old.EtsyCreationAttempted||!string.IsNullOrEmpty(old.EtsyListingId))throw new InvalidOperationException("Etsy bağlantısı veya gönderim kaydı olan ürünü silmek yerine pasife alın.");using var cmd=c.CreateCommand();cmd.Transaction=tx;cmd.CommandText="DELETE FROM CatalogProducts WHERE Id=$id";cmd.Parameters.AddWithValue("$id",product.Id);cmd.ExecuteNonQuery();tx.Commit();}
 static void Index(Dictionary<string,List<CatalogProduct>> index,string key,CatalogProduct product){if(key=="")return;if(!index.TryGetValue(key,out var values))index[key]=values=new();values.Add(product);}
 public ImportSummary Import(XmlSource source,IReadOnlyList<CatalogProduct> incoming)=>Import(source,incoming,CancellationToken.None,null);
 public ImportSummary Import(XmlSource source,IReadOnlyList<CatalogProduct> incoming,CancellationToken cancellationToken)=>Import(source,incoming,cancellationToken,null);
 public ImportSummary Import(XmlSource source,IReadOnlyList<CatalogProduct> incoming,CancellationToken cancellationToken,XmlImportContext? context)=>Import(source,incoming,cancellationToken,context,null);
 // #827: an optional progress sink; the row count is known, so the apply stage reports a real total.
 public ImportSummary Import(XmlSource source,IReadOnlyList<CatalogProduct> incoming,CancellationToken cancellationToken,XmlImportContext? context,IProgress<ImportProgressEvent>? progress)
 {
  cancellationToken.ThrowIfCancellationRequested();
  if(context?.CompleteFeed==true&&context.MappingShapeFingerprint.Length>0)XmlCatalog.EnsureMappingReady(source,new XmlMappingSnapshot(context.MappingShapeFingerprint,incoming.Count,Array.Empty<string>(),Array.Empty<string>()),scheduled:false);
  EnsureDropshipFeedSafe(source,incoming);
  ImportSummary? result=null;
  XmlSourceExecutionGate.RunAsync(source.Id,()=>{result=ImportCore(source,incoming,cancellationToken,context,progress);return Task.CompletedTask;},cancellationToken).GetAwaiter().GetResult();
  return result!;
 }
 void EnsureDropshipFeedSafe(XmlSource source,IReadOnlyList<CatalogProduct> incoming)
 {
  var existing=Products().Where(x=>x.SourceId==source.Id).ToList();
  // The caller has already selected a source; this guard is deliberately fail-closed for
  // suspicious supplier deltas before the write transaction starts.
  var currentCount=incoming.Count;var zeroCount=incoming.Count(x=>x.Stock<=0);var average=incoming.Count==0?0:incoming.Average(x=>x.Price);
  var previous=existing.Count==0?null:new FeedRunMetrics(source.Id,existing.Count,existing.Count(x=>x.Stock<=0),existing.Average(x=>x.Price),0,0,DateTimeOffset.UtcNow);
  var guard=new DropshipAnomalyGuard();
  var report=guard.Evaluate(new FeedRunMetrics(source.Id,currentCount,zeroCount,average,0,0,DateTimeOffset.UtcNow),previous);
  if(report.ApplyBlocked)throw new InvalidOperationException("Dropshipping anomaly gate blocked import: "+string.Join(", ",report.Reasons));
 }
 internal ImportSummary ImportCore(XmlSource source,IReadOnlyList<CatalogProduct> incoming,CancellationToken cancellationToken=default,XmlImportContext? context=null,IProgress<ImportProgressEvent>? progress=null)
 {
  XmlCatalog.ValidateSource(source);var categoryAliases=new TaxonomyAliasStore(dataDirectory).ApprovedMap(); /* #912: the approved aliases, loaded once per run and before the transaction -- the alias store opens its own connection and creates its table, which must not wait on this write lock */var reviewQueue=new CategoryReviewQueue(dataDirectory);var knownCategories=reviewQueue.KnownMap();var unmappedCategories=new List<CategoryReviewSighting>(); /* #913: built before the transaction for the same reason */var brandMapping=new BrandMappingStore(dataDirectory);var knownBrands=brandMapping.KnownMap();var unmappedBrands=new List<BrandSighting>(); /* #917 */using var c=Open();using var tx=c.BeginTransaction(deferred:false);var allSources=Read<XmlSource>(c,"Sources",tx);var persistedSource=allSources.SingleOrDefault(x=>x.Id==source.Id);XmlSource? SourceById(string id)=>allSources.FirstOrDefault(x=>x.Id==id);string NameOf(string id)=>id.Length==0?"operatör":SourceById(id)?.Name is {Length:>0} n?n:"silinmiş kaynak";var decisions=new List<SourcePriorityDecision>();if(context?.CompleteFeed==true&&!string.IsNullOrWhiteSpace(context.FeedHash)&&persistedSource?.LastSuccessfulFeedHash==context.FeedHash){tx.Rollback();return new ImportSummary(0,0,0,true,context.FeedHash);}var products=Read<CatalogProduct>(c,"CatalogProducts",tx);var previousSourceProducts=products.Where(p=>p.SourceId==source.Id).Select(CloneProduct).ToList();int added=0,updated=0,unchanged=0;var skus=new HashSet<string>(StringComparer.OrdinalIgnoreCase);var bars=new HashSet<string>(StringComparer.OrdinalIgnoreCase);var touched=new HashSet<string>();var skuIndex=new Dictionary<string,List<CatalogProduct>>(StringComparer.OrdinalIgnoreCase);var barcodeIndex=new Dictionary<string,List<CatalogProduct>>(StringComparer.OrdinalIgnoreCase);// #896: the match is across sources, so a second feed carrying the same SKU or barcode meets the product instead of creating a twin.
foreach(var p in products){Index(skuIndex,p.Sku,p);Index(barcodeIndex,p.Barcode,p);}
  var originChanges=new List<(string ProductId,OriginChange Change)>(); /* #910 */var importDone=0;var observedUtc=context?.ObservedAtUtc?.UtcDateTime??DateTime.UtcNow;foreach(var row in incoming){cancellationToken.ThrowIfCancellationRequested();if(progress!=null&&(++importDone%200==0||importDone==incoming.Count))progress.Report(new(ImportProgressStage.Apply,ImportProgressStatus.Running,importDone,incoming.Count));row.Name=TitleNormalizer.Normalize(row.Name).Normalized; /* #905 */if(TaxonomyAliasStore.Match(categoryAliases,row.Category) is {} canonicalCategory)row.Category=canonicalCategory; /* #912: an approved exact alias is the only auto-apply */else if(row.Category.Trim().Length>0&&!knownCategories.ContainsKey(TaxonomyAliasStore.Key(row.Category)))unmappedCategories.Add(new CategoryReviewSighting(row.Category,row.Sku)); /* #913: an unmapped value is evidence for the review queue */if(BrandMappingStore.Match(knownBrands,row.Brand) is {} canonicalBrand)row.Brand=canonicalBrand;else if(row.Brand.Trim().Length>0)unmappedBrands.Add(new BrandSighting(row.Brand,row.Sku)); /* #917: an exact known brand is the only auto-apply; the rest is evidence with a suggestion */if(ProductUnits.Apply(row,source.NumberCultureName).FirstOrDefault(f=>f.Blocking) is {} unitBlock)throw new InvalidOperationException($"{row.Sku}: {unitBlock.Message}"); /* #907 */ProductDimensions.Refresh(row,observedUtc); /* #908: the desi follows the feed's box */ProductTaxClass.Apply(row,FieldProvenance.FeedKind,observedUtc); /* #909 */ProductOrigin.Apply(row); /* #910 */Valid(row);if(row.SourceId!=source.Id)throw new InvalidOperationException("Kaynak kimliği uyuşmuyor.");if((row.Sku!=""&&!skus.Add(row.Sku))||(row.Barcode!=""&&!bars.Add(row.Barcode)))throw new InvalidOperationException("Yinelenen SKU veya barkod; aktarım iptal edildi.");// #902: one identity rule for every module -- the import decides through ProductIdentity, exactly as the preview and the order lines do.
   var match=ProductIdentity.Resolve(skuIndex.GetValueOrDefault(row.Sku)??new List<CatalogProduct>(),row.Barcode!=""?barcodeIndex.GetValueOrDefault(row.Barcode)??new List<CatalogProduct>():new List<CatalogProduct>(),row.Sku,row.Barcode);if(match.Outcome is ProductIdentity.Conflict or ProductIdentity.Ambiguous)throw new InvalidOperationException(match.Reason);
   var old=match.Product;if(old==null){var p=JsonSerializer.Deserialize<CatalogProduct>(JsonSerializer.Serialize(row))!;p.Id=Guid.NewGuid().ToString("N");p.UpdatedUtc=DateTime.UtcNow;FieldProvenance.StampFeed(p,WrittenFields(source,null),source.Id,context?.SourceRevision??0,context?.RunId??"",context?.ObservedAtUtc?.UtcDateTime??DateTime.UtcNow);products.Add(p);Index(skuIndex,p.Sku,p);Index(barcodeIndex,p.Barcode,p);Put(c,"CatalogProducts",p.Id,p,tx);RecordSighting(c,tx,source.Id,p.Id,observedUtc);touched.Add(p.Id);added++;continue;}
    if(!touched.Add(old.Id))throw new InvalidOperationException("Birden fazla satır aynı ürüne eşleşiyor.");var before=JsonSerializer.Serialize(old);var foreign=old.SourceId.Length>0&&old.SourceId!=source.Id;if(!foreign){old.SourceKind="xml";old.SourceId=source.Id;}var written=new List<string>();var marks=new List<SourcePriorityDecision>();
    // #896: every field goes through the decision -- lock, priority, freshness, staleness; a feed rewriting its own field is no contest -- the outcome is kept on the origin and audited once per change of outcome, not once per run.
    bool May(string field,bool locked){var holder=FieldProvenance.Of(old,field);var d=SourcePriority.Decide(old.Id,field,source,holder,holder is null?null:SourceById(holder.SourceId),locked,observedUtc);if(d is null){if(!locked)written.Add(field);return !locked;}marks.Add(d);if((holder?.Decision??"")!=d.Words(NameOf))decisions.Add(d);if(d.IncomingWins)written.Add(field);return d.IncomingWins;}if(source.Fields.ContainsKey("Weight")){old.WeightText=row.WeightText;old.WeightKg=row.WeightKg;written.Add("WeightText");}if(source.Fields.ContainsKey("Dimensions")){old.DimensionsText=row.DimensionsText;old.LengthCm=row.LengthCm;old.WidthCm=row.WidthCm;old.HeightCm=row.HeightCm;written.Add("DimensionsText");ProductDimensions.Refresh(old,observedUtc);} /* #907, #908: a derived desi follows the box, a manual one is kept */if(source.Fields.ContainsKey("TaxClass")&&May("TaxClass",false)){old.TaxClass=row.TaxClass;ProductTaxClass.Apply(old,FieldProvenance.FeedKind,observedUtc);} /* #909 */if(source.Fields.ContainsKey("CountryOfOrigin")&&May("CountryOfOrigin",false)){var originBefore=ProductOrigin.Snapshot(old);old.CountryOfOrigin=row.CountryOfOrigin;ProductOrigin.Apply(old);if(ProductOrigin.Change(originBefore,old) is {} originChange)originChanges.Add((old.Id,originChange));} /* #910 */if(source.Fields.ContainsKey("Gtin")&&May("Gtin",false))old.Gtin=row.Gtin;if(May("Cost",false)){old.Cost=row.Cost;old.CostCurrency=row.CostCurrency;}if(May("Price",old.LockPrice)){written.Add("Currency");old.Price=row.Price;old.Currency=row.Currency;old.PriceSource="xml";old.FormulaPriceTry=row.FormulaPriceTry;old.AppliedTryRate=row.AppliedTryRate;old.FxRateDate=row.FxRateDate;}if(May("Stock",old.LockStock)){old.Stock=row.Stock;old.StockSource="xml";}if(source.UpdateName&&May("Name",old.LockName))old.Name=row.Name;if(source.UpdateDescription&&May("Description",old.LockDescription))old.Description=row.Description;if(source.UpdateImages&&May("ImageUrls",old.LockImages)){old.ImageUrls=row.ImageUrls;old.MediaSource="xml";}
    if(before==JsonSerializer.Serialize(old)){if(MarkDecisions(old,marks,NameOf))Put(c,"CatalogProducts",old.Id,old,tx);RecordSighting(c,tx,source.Id,old.Id,observedUtc);unchanged++;continue;}old.SourceUpdatedUtc=DateTime.UtcNow;old.UpdatedUtc=DateTime.UtcNow;FieldProvenance.StampFeed(old,written,source.Id,context?.SourceRevision??0,context?.RunId??"",observedUtc);MarkDecisions(old,marks,NameOf);Put(c,"CatalogProducts",old.Id,old,tx);RecordSighting(c,tx,source.Id,old.Id,observedUtc);updated++;
   }
   cancellationToken.ThrowIfCancellationRequested();var sourceState=CloneSource(source);if(context?.CompleteFeed==true){sourceState.LastSuccessfulFeedHash=context.FeedHash??"";sourceState.LastSuccessfulFeedUtc=(context.ObservedAtUtc??DateTimeOffset.UtcNow).UtcDateTime;sourceState.LastSuccessfulFeedCount=incoming.Count;sourceState.LastMappingShapeFingerprint=context.MappingShapeFingerprint;sourceState.LastAppliedMappingRevision=source.MappingRevision;sourceState.LastFeedState="COMPLETE";}else if(context is not null)sourceState.LastFeedState="INCOMPLETE";Put(c,"Sources",sourceState.Id,sourceState,tx);tx.Commit();WriteDecisions(decisions,NameOf);WriteOriginChanges(originChanges); /* #910 */if(unmappedCategories.Count>0){try{reviewQueue.Record(source.Id,unmappedCategories,observedUtc);}catch(Exception){}} /* #913: the queue is evidence, written after the commit like the decisions */if(unmappedBrands.Count>0){try{brandMapping.Record(source.Id,unmappedBrands,observedUtc);}catch(Exception){}} /* #917 */try{var priceAnomalies=new PriceAnomalyStore(dataDirectory);foreach(var written in products.Where(x=>touched.Contains(x.Id)))priceAnomalies.Observe(written,FieldProvenance.FeedKind,observedUtc);}catch(Exception){} /* #930: every price the run wrote is a snapshot; a jump against the previous one is a review item, never a correction */try{new TaxonomySnapshotStore(dataDirectory).Refresh(TaxonomySnapshotStore.LocalScope,observedUtc);}catch(Exception){} /* #918: the local taxonomy version confirmed after every run */source.LastSuccessfulFeedHash=sourceState.LastSuccessfulFeedHash;source.LastSuccessfulFeedUtc=sourceState.LastSuccessfulFeedUtc;source.LastSuccessfulFeedCount=sourceState.LastSuccessfulFeedCount;source.LastMappingShapeFingerprint=sourceState.LastMappingShapeFingerprint;source.LastAppliedMappingRevision=sourceState.LastAppliedMappingRevision;source.LastFeedState=sourceState.LastFeedState;if(context?.CompleteFeed==true)ReconcileMissingSource(sourceState,previousSourceProducts,incoming,context.ObservedAtUtc??DateTimeOffset.UtcNow);return new ImportSummary(added,updated,unchanged,false,context?.FeedHash??"");
 }
 static CatalogProduct CloneProduct(CatalogProduct p)=>JsonSerializer.Deserialize<CatalogProduct>(JsonSerializer.Serialize(p))!;
 static XmlSource CloneSource(XmlSource s)=>JsonSerializer.Deserialize<XmlSource>(JsonSerializer.Serialize(s))!;
 void ReconcileMissingSource(XmlSource source,IReadOnlyList<CatalogProduct> previous,IReadOnlyList<CatalogProduct> incoming,DateTimeOffset now){var quarantine=new SourceMissingQuarantine(dataDirectory);var incomingKeys=incoming.Select(Key).Where(x=>x.Length>0).ToHashSet(StringComparer.OrdinalIgnoreCase);var policy=new MissingSourcePolicy(TimeSpan.FromMinutes(source.MissingSourceGraceMinutes));foreach(var product in previous){var key=Key(product);if(key.Length>0)quarantine.Observe(source.Id,ProductId(product),incomingKeys.Contains(key),product.Stock,product.Price,now,policy);}}
 static string Key(CatalogProduct product)=>!string.IsNullOrWhiteSpace(product.Sku)?"sku:"+product.Sku.Trim():!string.IsNullOrWhiteSpace(product.Barcode)?"barcode:"+product.Barcode.Trim():"";
 static string ProductId(CatalogProduct product)=>!string.IsNullOrWhiteSpace(product.Sku)?product.Sku.Trim():product.Barcode.Trim();
 public CatalogUndoReceipt ImportWithUndo(XmlSource source,IReadOnlyList<CatalogProduct> incoming,CancellationToken cancellationToken=default){var before=Products().Select(CloneProduct).ToList();Import(source,incoming,cancellationToken);cancellationToken.ThrowIfCancellationRequested();var after=Products().Select(CloneProduct).ToList();return new(Guid.NewGuid().ToString("N"),before,after);}
 public void Undo(CatalogUndoReceipt receipt){using var c=Open();using var tx=c.BeginTransaction();var current=Read<CatalogProduct>(c,"CatalogProducts",tx);var expected=JsonSerializer.Serialize(receipt.After.OrderBy(p=>p.Id));var actual=JsonSerializer.Serialize(current.OrderBy(p=>p.Id));if(expected!=actual)throw new InvalidOperationException("Katalog bu içe aktarmadan sonra değişti; geri alma güvenlik nedeniyle durduruldu.");using(var delete=c.CreateCommand()){delete.Transaction=tx;delete.CommandText="DELETE FROM CatalogProducts";delete.ExecuteNonQuery();}foreach(var p in receipt.Before)Put(c,"CatalogProducts",p.Id,p,tx);tx.Commit();}
}
