using ClosedXML.Excel;
using System.Globalization;
using System.IO;
using System.Text;
namespace TrMarketplaceHubDesktop.Catalog;
public sealed record ExcelPreview(IReadOnlyList<CatalogProduct> Rows,IReadOnlyList<string> Errors);
public static class ExcelPreviewExtensions { public static int IndexOf<T>(this IReadOnlyList<T> source,T value)=>Enumerable.Range(0,source.Count).FirstOrDefault(i=>EqualityComparer<T>.Default.Equals(source[i],value),-1); }
public sealed record ExcelColumnMapping(IReadOnlyDictionary<string,int> Columns)
{
 public static ExcelColumnMapping FromHeaders(IXLRow header){var aliases=new Dictionary<string,string[]>(StringComparer.OrdinalIgnoreCase){["Sku"]=["sku","stockcode","stokkodu","code"],["Barcode"]=["barkod","barcode","ean"],["Name"]=["ürün","urun","ürün adı","urun adi","name","title"],["Brand"]=["marka","brand"],["Category"]=["kategori","category"],["Description"]=["açıklama","aciklama","description"],["Cost"]=["alış","alis","maliyet","cost"],["Price"]=["satış","satis","fiyat","price"],["Currency"]=["döviz","doviz","currency"],["Stock"]=["stok","stock","qty","quantity"],["Active"]=["aktif","active","enabled"],["Gtin"]=["gtin","gtin13","gtin14"]};var found=new Dictionary<string,int>(StringComparer.OrdinalIgnoreCase);foreach(var cell in header.CellsUsed()){var value=Normalize(cell.GetString());foreach(var pair in aliases)if(pair.Value.Any(a=>Normalize(a)==value)){found[pair.Key]=cell.Address.ColumnNumber;break;}}return new(found);}
 static string Normalize(string value)=>value.Trim().ToLowerInvariant().Replace("ı","i").Normalize(NormalizationForm.FormD).Where(c=>CharUnicodeInfo.GetUnicodeCategory(c)!=UnicodeCategory.NonSpacingMark).Aggregate(new StringBuilder(),(b,c)=>b.Append(char.IsWhiteSpace(c)?' ':c)).ToString();
}
public static class CatalogExcel {
 public static IReadOnlyList<string> Headers(string path){if(!File.Exists(path))throw new FileNotFoundException("Excel dosyası bulunamadı.",path);using var book=new XLWorkbook(path);var sheet=book.Worksheets.FirstOrDefault()??throw new InvalidDataException("Çalışma sayfası bulunamadı.");var row=sheet.FirstRowUsed()??throw new InvalidDataException("Başlık satırı bulunamadı.");return row.CellsUsed().Select(c=>c.GetString().Trim()).ToList();}
 public static void ExportErrors(string path,ExcelPreview preview){using var book=new XLWorkbook();var sheet=book.AddWorksheet("Hatalar");sheet.Cell(1,1).Value="Hata";for(var i=0;i<preview.Errors.Count;i++)sheet.Cell(i+2,1).Value=preview.Errors[i];sheet.Columns().AdjustToContents();book.SaveAs(path);}
 public static void Export(string path,IReadOnlyList<CatalogProduct> products){using var book=new XLWorkbook();var sheet=book.AddWorksheet("Ürünler");var headers=new[]{"SKU","Barkod","Ürün","Marka","Kategori","Açıklama","Alış","Satış","Döviz","Stok","Aktif"};for(var i=0;i<headers.Length;i++)sheet.Cell(1,i+1).Value=headers[i];var row=2;foreach(var p in products){var v=new object?[]{p.Sku,p.Barcode,p.Name,p.Brand,p.Category,p.Description,p.Cost,p.Price,p.Currency,p.Stock,p.Active};for(var i=0;i<v.Length;i++)sheet.Cell(row,i+1).Value=v[i]?.ToString()??"";row++;}sheet.Columns().AdjustToContents();book.SaveAs(path);}
 public static ExcelPreview Preview(string path,ExcelColumnMapping? mapping=null){if(!File.Exists(path))throw new FileNotFoundException("Excel dosyası bulunamadı.",path);using var book=new XLWorkbook(path);var sheet=book.Worksheets.FirstOrDefault()??throw new InvalidDataException("Çalışma sayfası bulunamadı.");var map=mapping??ExcelColumnMapping.FromHeaders(sheet.FirstRowUsed()??throw new InvalidDataException("Başlık satırı bulunamadı."));var rows=new List<CatalogProduct>();var errors=new List<string>();int Col(string key)=>map.Columns.TryGetValue(key,out var c)?c:0;string Text(IXLRow r,string key)=>Col(key)==0?"":r.Cell(Col(key)).GetString().Trim();foreach(var key in new[]{"Sku","Name","Cost","Price","Stock"})if(Col(key)==0)errors.Add($"Kolon eşleme eksik: {key}.");if(errors.Count>0)return new(rows,errors);foreach(var r in sheet.RowsUsed().Skip(1)){var sku=Text(r,"Sku");if(sku.Length==0){errors.Add($"Satır {r.RowNumber()}: SKU zorunlu.");continue;}if(!decimal.TryParse(Text(r,"Cost"),NumberStyles.Any,CultureInfo.CurrentCulture,out var cost)||!decimal.TryParse(Text(r,"Price"),NumberStyles.Any,CultureInfo.CurrentCulture,out var price)||!int.TryParse(Text(r,"Stock"),NumberStyles.Any,CultureInfo.CurrentCulture,out var stock)||cost<0||price<0||stock<0){errors.Add($"Satır {r.RowNumber()}: fiyat/stok geçersiz.");continue;}var currency=Text(r,"Currency");rows.Add(new CatalogProduct{Sku=sku,Barcode=Text(r,"Barcode"),Name=Text(r,"Name"),Brand=Text(r,"Brand"),Category=Text(r,"Category"),Description=Text(r,"Description"),Cost=cost,Price=price,Currency=currency.Length==3?currency:"TRY",Stock=stock,Active=!string.Equals(Text(r,"Active"),"false",StringComparison.OrdinalIgnoreCase),Gtin=Text(r,"Gtin")});}return new(rows,errors);}
 public static ImportSummary Apply(CatalogStore store,XmlSource source,ExcelPreview preview){if(preview.Errors.Count>0)throw new InvalidOperationException("Hatalı Excel satırları düzeltilmeden katalog güncellenemez.");source.UpdateName=true;source.UpdateDescription=true;source.UpdateImages=true;source.Fields["Gtin"]="excel";var rows=preview.Rows.Select(p=>{p.SourceId=source.Id;return p;}).ToList();return store.Import(source,rows);}
 public static ImportSummary Apply(CatalogStore store,XmlSource source,ExcelPreview preview,IReadOnlyCollection<int> selectedRows){if(selectedRows.Count==0)throw new InvalidOperationException("Uygulamak için en az bir satır seçin.");if(preview.Errors.Count>0)throw new InvalidOperationException("Hatalı Excel satırları düzeltilmeden katalog güncellenemez.");var rows=preview.Rows.Where((_,index)=>selectedRows.Contains(index)).ToList();if(rows.Count!=selectedRows.Count)throw new InvalidOperationException("Seçili satır numarası önizleme dışında.");return Apply(store,source,new ExcelPreview(rows,Array.Empty<string>()));}
 public static CatalogUndoReceipt ApplyWithUndo(CatalogStore store,XmlSource source,ExcelPreview preview,IReadOnlyCollection<int> selectedRows){if(selectedRows.Count==0)throw new InvalidOperationException("Uygulamak için en az bir satır seçin.");if(preview.Errors.Count>0)throw new InvalidOperationException("Hatalı Excel satırları düzeltilmeden katalog güncellenemez.");var rows=preview.Rows.Where((_,index)=>selectedRows.Contains(index)).ToList();if(rows.Count!=selectedRows.Count)throw new InvalidOperationException("Seçili satır numarası önizleme dışında.");source.UpdateName=true;source.UpdateDescription=true;source.UpdateImages=true;source.Fields["Gtin"]="excel";rows.ForEach(p=>p.SourceId=source.Id);return store.ImportWithUndo(source,rows);}
}
