using Microsoft.Data.Sqlite;
using System.Text.Json;
namespace TrMarketplaceHubDesktop.Catalog;
public sealed class PricePolicy { string currency="TRY"; public string Channel {get;set;}=""; public string Shop {get;set;}=""; public string Formula {get;set;}="x"; public string ListFormula {get;set;}="x"; public string Currency {get=>currency;set=>currency=(value??"").Trim().ToUpperInvariant();} public decimal TryPerUnit {get;set;}=1; public decimal MinimumPrice {get;set;} public decimal MinimumMarginTry {get;set;} public bool Enabled {get;set;}=true; public DateTime UpdatedUtc {get;set;} public int Version {get;set;} }
public sealed record PricePreview(string Sku, decimal Price, decimal ListPrice, string Currency, decimal FormulaPriceTry, decimal CostTry);
public partial class CatalogStore {
 static void InitializePricePolicies(SqliteConnection c){using var x=c.CreateCommand();x.CommandText="CREATE TABLE IF NOT EXISTS PricePolicies(Channel TEXT NOT NULL,Shop TEXT NOT NULL,Json TEXT NOT NULL,PRIMARY KEY(Channel,Shop))";x.ExecuteNonQuery();}
 public PricePolicy? GetPricePolicy(string ch,string shop){var k=PolicyKey(ch,shop);using var c=Open();using var x=c.CreateCommand();x.CommandText="SELECT Json FROM PricePolicies WHERE Channel=$c AND Shop=$s";x.Parameters.AddWithValue("$c",k.Channel);x.Parameters.AddWithValue("$s",k.Shop);return x.ExecuteScalar() is string j?JsonSerializer.Deserialize<PricePolicy>(j):null;}
 public PricePolicy SavePricePolicy(PricePolicy p){var k=PolicyKey(p.Channel,p.Shop);if(p.Formula.Length is 0 or >8192||p.ListFormula.Length is 0 or >8192||p.Currency.Length!=3||p.TryPerUnit<=0||p.MinimumPrice<0||p.MinimumMarginTry<0)throw new ArgumentException("Fiyat kuralı geçersiz.");if(p.Currency is not("TRY" or "USD" or "EUR" or "GBP"))throw new ArgumentException("Desteklenmeyen döviz.");_=PriceFormula.Compile(p.Formula);_=PriceFormula.Compile(p.ListFormula);using var c=Open();using var tx=c.BeginTransaction();var old=GetPricePolicy(c,tx,k.Channel,k.Shop);if((old?.Version??0)!=p.Version)throw new InvalidOperationException("Fiyat kuralı başka işlemde değişti.");p.Channel=k.Channel;p.Shop=k.Shop;p.UpdatedUtc=DateTime.UtcNow;p.Version++;using var x=c.CreateCommand();x.Transaction=tx;x.CommandText="INSERT INTO PricePolicies VALUES($c,$s,$j) ON CONFLICT(Channel,Shop) DO UPDATE SET Json=excluded.Json";x.Parameters.AddWithValue("$c",p.Channel);x.Parameters.AddWithValue("$s",p.Shop);x.Parameters.AddWithValue("$j",JsonSerializer.Serialize(p));x.ExecuteNonQuery();tx.Commit();return p;}
 static PricePolicy? GetPricePolicy(SqliteConnection c,SqliteTransaction tx,string ch,string shop){using var x=c.CreateCommand();x.Transaction=tx;x.CommandText="SELECT Json FROM PricePolicies WHERE Channel=$c AND Shop=$s";x.Parameters.AddWithValue("$c",ch);x.Parameters.AddWithValue("$s",shop);return x.ExecuteScalar() is string j?JsonSerializer.Deserialize<PricePolicy>(j):null;}
 // Enabled must gate before any formula/rate work, not after: a disabled policy
 // must never silently keep producing prices from stale rule data.
 public PricePreview PreviewPrice(string ch,string shop,string id){var p=GetPricePolicy(ch,shop)??throw new InvalidOperationException("Önce fiyat kuralı kaydedin.");if(!p.Enabled)throw new InvalidOperationException("Fiyat kuralı pasif; önizleme üretilemez.");using var c=Open();using var x=c.CreateCommand();x.CommandText="SELECT Json FROM CatalogProducts WHERE Id=$id";x.Parameters.AddWithValue("$id",id);if(x.ExecuteScalar() is not string j)throw new InvalidOperationException("Ürün bulunamadı.");var product=JsonSerializer.Deserialize<CatalogProduct>(j)!;if(!product.Active)throw new InvalidOperationException("Pasif ürün için fiyat üretilemez.");var formula=PriceFormula.Evaluate(p.Formula,product.Cost);var listFormula=PriceFormula.Evaluate(p.ListFormula,product.Cost);if(formula<=0||listFormula<=0)throw new InvalidOperationException("Formül pozitif fiyat üretmedi.");var rate=p.Currency=="TRY"?1:p.TryPerUnit;var result=Math.Round(formula/rate,2,MidpointRounding.AwayFromZero);var listResult=Math.Round(listFormula/rate,2,MidpointRounding.AwayFromZero);if(result<p.MinimumPrice||formula-product.Cost<p.MinimumMarginTry)throw new InvalidOperationException("Fiyat koruması kuralı reddetti.");return new(product.Sku,result,listResult,p.Currency,formula,product.Cost);}
}
