using Microsoft.Data.Sqlite;
using System.IO;

namespace TrMarketplaceHubDesktop.Catalog;
public enum SyncStatus { Pending, Running, Succeeded, Failed, Cancelled }
public enum SyncErrorClass { None, Network, Authentication, Mapping, Validation, RateLimit, Stale, Idempotency, Unsupported, Unknown }
public sealed record SyncRequest(string Channel,string Operation,string EntityId,string Version,string ShopId="default");
public sealed class SyncJob { public string Id {get;set;}=Guid.NewGuid().ToString("N"); public string Channel {get;set;}=""; public string ShopId {get;set;}="default"; public string Operation {get;set;}=""; public string EntityId {get;set;}=""; public string Version {get;set;}=""; public SyncStatus Status {get;set;}=SyncStatus.Pending; public int FailureCount {get;set;} public string LastError {get;set;}=""; public SyncErrorClass ErrorClass {get;set;}=SyncErrorClass.None; public DateTime UpdatedUtc {get;set;}=DateTime.UtcNow; }
public sealed class SyncStore
{
 readonly string connectionString;
 public SyncStore(string? directory=null){directory??=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"MonoBridgeDesktop");Directory.CreateDirectory(directory);connectionString=new SqliteConnectionStringBuilder{DataSource=Path.Combine(directory,"catalog.db"),DefaultTimeout=15,Pooling=true}.ToString();using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="PRAGMA journal_mode=WAL;PRAGMA synchronous=NORMAL;PRAGMA busy_timeout=15000;CREATE TABLE IF NOT EXISTS SyncJobs(Id TEXT PRIMARY KEY, Channel TEXT NOT NULL, ShopId TEXT NOT NULL DEFAULT 'default', Operation TEXT NOT NULL, EntityId TEXT NOT NULL, Version TEXT NOT NULL, Status INTEGER NOT NULL, FailureCount INTEGER NOT NULL, LastError TEXT NOT NULL, ErrorClass INTEGER NOT NULL DEFAULT 0, UpdatedUtc TEXT NOT NULL);CREATE INDEX IF NOT EXISTS UX_SyncJobs_Key ON SyncJobs(Channel,ShopId,Operation,EntityId,Version);CREATE INDEX IF NOT EXISTS IX_SyncJobs_StatusUpdated ON SyncJobs(Status,UpdatedUtc)";cmd.ExecuteNonQuery();EnsureColumn(c,"ShopId","TEXT NOT NULL DEFAULT 'default'");EnsureColumn(c,"ErrorClass","INTEGER NOT NULL DEFAULT 0");SchemaVersion.Ensure(c);}
 static void EnsureColumn(SqliteConnection c,string name,string definition){using var check=c.CreateCommand();check.CommandText="SELECT 1 FROM pragma_table_info('SyncJobs') WHERE name=$name";check.Parameters.AddWithValue("$name",name);if(check.ExecuteScalar()!=null)return;using var add=c.CreateCommand();add.CommandText=$"ALTER TABLE SyncJobs ADD COLUMN {name} {definition}";add.ExecuteNonQuery();}
 SqliteConnection Open(){var c=new SqliteConnection(connectionString);c.Open();using var pragma=c.CreateCommand();pragma.CommandText="PRAGMA busy_timeout=15000";pragma.ExecuteNonQuery();if(TableExists(c,"SyncJobs")){using var key=c.CreateCommand();key.CommandText="DROP INDEX IF EXISTS UX_SyncJobs_Key;CREATE UNIQUE INDEX IF NOT EXISTS UX_SyncJobs_Key ON SyncJobs(Channel,ShopId,Operation,EntityId,Version)";key.ExecuteNonQuery();}return c;}
 static bool TableExists(SqliteConnection c,string name){using var command=c.CreateCommand();command.CommandText="SELECT 1 FROM sqlite_master WHERE type='table' AND name=$name";command.Parameters.AddWithValue("$name",name);return command.ExecuteScalar() is not null;}
 public SyncJob Enqueue(SyncRequest request){if(string.IsNullOrWhiteSpace(request.Channel)||string.IsNullOrWhiteSpace(request.ShopId)||string.IsNullOrWhiteSpace(request.Operation)||string.IsNullOrWhiteSpace(request.EntityId)||string.IsNullOrWhiteSpace(request.Version))throw new InvalidOperationException("Sync işi için kanal, mağaza, işlem, varlık ve sürüm zorunlu.");using var c=Open();using var find=c.CreateCommand();find.CommandText="SELECT Id,Channel,ShopId,Operation,EntityId,Version,Status,FailureCount,LastError,ErrorClass,UpdatedUtc FROM SyncJobs WHERE Channel=$channel AND ShopId=$shop AND Operation=$operation AND EntityId=$entity AND Version=$version";find.Parameters.AddWithValue("$channel",request.Channel.Trim().ToLowerInvariant());find.Parameters.AddWithValue("$shop",request.ShopId.Trim());find.Parameters.AddWithValue("$operation",request.Operation);find.Parameters.AddWithValue("$entity",request.EntityId);find.Parameters.AddWithValue("$version",request.Version);using(var r=find.ExecuteReader())if(r.Read())return Read(r);var job=new SyncJob{Channel=request.Channel.Trim().ToLowerInvariant(),ShopId=request.ShopId.Trim(),Operation=request.Operation,EntityId=request.EntityId,Version=request.Version};using var cmd=c.CreateCommand();cmd.CommandText="INSERT INTO SyncJobs(Id,Channel,ShopId,Operation,EntityId,Version,Status,FailureCount,LastError,ErrorClass,UpdatedUtc) VALUES($id,$channel,$shop,$operation,$entity,$version,$status,0,'',0,$updated)";cmd.Parameters.AddWithValue("$id",job.Id);cmd.Parameters.AddWithValue("$channel",job.Channel);cmd.Parameters.AddWithValue("$shop",job.ShopId);cmd.Parameters.AddWithValue("$operation",job.Operation);cmd.Parameters.AddWithValue("$entity",job.EntityId);cmd.Parameters.AddWithValue("$version",job.Version);cmd.Parameters.AddWithValue("$status",(int)job.Status);cmd.Parameters.AddWithValue("$updated",job.UpdatedUtc.ToString("O"));cmd.ExecuteNonQuery();return job;}
 static SyncJob Read(SqliteDataReader r)=>new(){Id=r.GetString(0),Channel=r.GetString(1),ShopId=r.GetString(2),Operation=r.GetString(3),EntityId=r.GetString(4),Version=r.GetString(5),Status=(SyncStatus)r.GetInt32(6),FailureCount=r.GetInt32(7),LastError=r.GetString(8),ErrorClass=(SyncErrorClass)r.GetInt32(9),UpdatedUtc=DateTime.Parse(r.GetString(10),null,System.Globalization.DateTimeStyles.RoundtripKind)};
 public SyncJob Get(string id){using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="SELECT Id,Channel,ShopId,Operation,EntityId,Version,Status,FailureCount,LastError,ErrorClass,UpdatedUtc FROM SyncJobs WHERE Id=$id";cmd.Parameters.AddWithValue("$id",id);using var r=cmd.ExecuteReader();if(!r.Read())throw new InvalidOperationException("Sync işi bulunamadı.");return Read(r);}
 public bool TryStart(string id){using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="UPDATE SyncJobs SET Status=$running,UpdatedUtc=$updated WHERE Id=$id AND Status=$pending";cmd.Parameters.AddWithValue("$running",(int)SyncStatus.Running);cmd.Parameters.AddWithValue("$pending",(int)SyncStatus.Pending);cmd.Parameters.AddWithValue("$updated",DateTime.UtcNow.ToString("O"));cmd.Parameters.AddWithValue("$id",id);return cmd.ExecuteNonQuery()==1;}
 public bool Cancel(string id){using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="UPDATE SyncJobs SET Status=$cancelled,LastError=$error,ErrorClass=0,UpdatedUtc=$updated WHERE Id=$id AND Status IN ($pending,$running)";cmd.Parameters.AddWithValue("$cancelled",(int)SyncStatus.Cancelled);cmd.Parameters.AddWithValue("$pending",(int)SyncStatus.Pending);cmd.Parameters.AddWithValue("$running",(int)SyncStatus.Running);cmd.Parameters.AddWithValue("$error","Kullanıcı tarafından iptal edildi; yeniden dispatch edilmez.");cmd.Parameters.AddWithValue("$updated",DateTime.UtcNow.ToString("O"));cmd.Parameters.AddWithValue("$id",id);return cmd.ExecuteNonQuery()==1;}
 public int RecoverAbandonedRunning(TimeSpan lease, DateTime? nowUtc = null){if(lease<=TimeSpan.Zero)throw new ArgumentOutOfRangeException(nameof(lease));var now=nowUtc??DateTime.UtcNow;var cutoff=now-lease;using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="UPDATE SyncJobs SET Status=$pending,LastError=$error,ErrorClass=$class,UpdatedUtc=$updated WHERE Status=$running AND UpdatedUtc < $cutoff";cmd.Parameters.AddWithValue("$pending",(int)SyncStatus.Pending);cmd.Parameters.AddWithValue("$running",(int)SyncStatus.Running);cmd.Parameters.AddWithValue("$error","Önceki çalışma sonlandı; iş güvenli yeniden deneme için kuyruğa alındı.");cmd.Parameters.AddWithValue("$class",(int)SyncErrorClass.Unknown);cmd.Parameters.AddWithValue("$updated",now.ToString("O"));cmd.Parameters.AddWithValue("$cutoff",cutoff.ToString("O"));return cmd.ExecuteNonQuery();}
 public void Succeed(string id){using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="UPDATE SyncJobs SET Status=$status,LastError='',ErrorClass=0,UpdatedUtc=$updated WHERE Id=$id";cmd.Parameters.AddWithValue("$status",(int)SyncStatus.Succeeded);cmd.Parameters.AddWithValue("$updated",DateTime.UtcNow.ToString("O"));cmd.Parameters.AddWithValue("$id",id);if(cmd.ExecuteNonQuery()!=1)throw new InvalidOperationException("Sync işi bulunamadı.");}
 public void Fail(string id,string error){var safe=Redact(error);var classification=Classify(safe);using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="UPDATE SyncJobs SET Status=$status,FailureCount=FailureCount+1,LastError=$error,ErrorClass=$class,UpdatedUtc=$updated WHERE Id=$id";cmd.Parameters.AddWithValue("$status",(int)SyncStatus.Failed);cmd.Parameters.AddWithValue("$error",safe);cmd.Parameters.AddWithValue("$class",(int)classification);cmd.Parameters.AddWithValue("$updated",DateTime.UtcNow.ToString("O"));cmd.Parameters.AddWithValue("$id",id);if(cmd.ExecuteNonQuery()!=1)throw new InvalidOperationException("Sync işi bulunamadı.");}
 public void Retry(string id){var job=Get(id);if(job.Status!=SyncStatus.Failed)throw new InvalidOperationException("Yalnızca başarısız sync işleri tekrarlanabilir.");if(!IsRetryable(job.ErrorClass))throw new InvalidOperationException($"{job.ErrorClass} sınıfındaki sync işi otomatik tekrar denenemez; veriyi düzeltip yeni önizleme oluşturun.");if(job.FailureCount>=3)throw new InvalidOperationException("Sync işi üç başarısız denemeden sonra durduruldu.");using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="UPDATE SyncJobs SET Status=$status,LastError='',ErrorClass=0,UpdatedUtc=$updated WHERE Id=$id";cmd.Parameters.AddWithValue("$status",(int)SyncStatus.Pending);cmd.Parameters.AddWithValue("$updated",DateTime.UtcNow.ToString("O"));cmd.Parameters.AddWithValue("$id",id);cmd.ExecuteNonQuery();}
 public static TimeSpan RetryDelay(int failureCount){if(failureCount<1)throw new ArgumentOutOfRangeException(nameof(failureCount));return TimeSpan.FromSeconds(Math.Min(300,Math.Pow(2,failureCount)*5));}
 public IReadOnlyList<SyncJob> List(){using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="SELECT Id,Channel,ShopId,Operation,EntityId,Version,Status,FailureCount,LastError,ErrorClass,UpdatedUtc FROM SyncJobs ORDER BY UpdatedUtc DESC";using var r=cmd.ExecuteReader();var result=new List<SyncJob>();while(r.Read())result.Add(Read(r));return result;}
 public static SyncErrorClass Classify(string error){var text=error.ToLowerInvariant();if(text.Contains("429")||text.Contains("rate")||text.Contains("istek sınır"))return SyncErrorClass.RateLimit;if(text.Contains("401")||text.Contains("403")||text.Contains("auth")||text.Contains("yetki")||text.Contains("credential"))return SyncErrorClass.Authentication;if(text.Contains("timeout")||text.Contains("zaman aş")||text.Contains("network")||text.Contains("ağ"))return SyncErrorClass.Network;if(text.Contains("mapping")||text.Contains("eşleş"))return SyncErrorClass.Mapping;if(text.Contains("stale")||text.Contains("önizleme")||text.Contains("güncelliğini"))return SyncErrorClass.Stale;if(text.Contains("duplicate")||text.Contains("idempot")||text.Contains("zaten"))return SyncErrorClass.Idempotency;if(text.Contains("validation")||text.Contains("geçersiz")||text.Contains("zorunlu")||text.Contains("eksik"))return SyncErrorClass.Validation;if(text.Contains("blocked")||text.Contains("desteklenmiyor"))return SyncErrorClass.Unsupported;return SyncErrorClass.Unknown;}
 public static bool IsRetryable(SyncErrorClass classification)=>classification is SyncErrorClass.Network or SyncErrorClass.RateLimit or SyncErrorClass.Authentication or SyncErrorClass.Unknown;
 static string Redact(string value){var safe=(value??"").Replace("access_token","[redacted]",StringComparison.OrdinalIgnoreCase).Replace("refresh_token","[redacted]",StringComparison.OrdinalIgnoreCase).Replace("api-key","[redacted]",StringComparison.OrdinalIgnoreCase).Replace("api_key","[redacted]",StringComparison.OrdinalIgnoreCase).Replace("client_secret","[redacted]",StringComparison.OrdinalIgnoreCase).Replace("secret","[redacted]",StringComparison.OrdinalIgnoreCase).Replace("token","[redacted]",StringComparison.OrdinalIgnoreCase).Trim();return safe.Length>1000?safe[..1000]:safe;}
 public static string Explain(SyncErrorClass c)=>c switch { SyncErrorClass.Network=>"Ağ bağlantısı veya zaman aşımı; tekrar deneyin.", SyncErrorClass.Authentication=>"Yetkilendirme geçersiz veya süresi dolmuş; bağlantıyı yenileyin.", SyncErrorClass.RateLimit=>"İstek sınırına ulaşıldı; bekleyip tekrar deneyin.", SyncErrorClass.Mapping=>"Alan veya kategori eşleşmesi eksik.", SyncErrorClass.Validation=>"Gönderilen veri doğrulama kurallarını karşılamıyor.", SyncErrorClass.Stale=>"Önizleme güncel değil; yenileyin.", SyncErrorClass.Idempotency=>"Aynı işlem daha önce kaydedildi.", SyncErrorClass.Unsupported=>"Bu işlem connector tarafından desteklenmiyor.", _=>"Beklenmeyen senkronizasyon hatası." };}

