using Microsoft.Data.Sqlite;
using System.IO;

namespace TrMarketplaceHubDesktop.Catalog;
public enum SyncStatus { Pending, Running, Succeeded, Failed }
public sealed record SyncRequest(string Channel,string Operation,string EntityId,string Version);
public sealed class SyncJob { public string Id {get;set;}=Guid.NewGuid().ToString("N"); public string Channel {get;set;}=""; public string Operation {get;set;}=""; public string EntityId {get;set;}=""; public string Version {get;set;}=""; public SyncStatus Status {get;set;}=SyncStatus.Pending; public int FailureCount {get;set;} public string LastError {get;set;}=""; public DateTime UpdatedUtc {get;set;}=DateTime.UtcNow; }
public sealed class SyncStore
{
 readonly string connectionString;
 public SyncStore(string? directory=null){directory??=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"MonoBridgeDesktop");Directory.CreateDirectory(directory);connectionString=new SqliteConnectionStringBuilder{DataSource=Path.Combine(directory,"catalog.db")}.ToString();using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="CREATE TABLE IF NOT EXISTS SyncJobs(Id TEXT PRIMARY KEY, Channel TEXT NOT NULL, Operation TEXT NOT NULL, EntityId TEXT NOT NULL, Version TEXT NOT NULL, Status INTEGER NOT NULL, FailureCount INTEGER NOT NULL, LastError TEXT NOT NULL, UpdatedUtc TEXT NOT NULL);CREATE UNIQUE INDEX IF NOT EXISTS UX_SyncJobs_Key ON SyncJobs(Channel,Operation,EntityId,Version)";cmd.ExecuteNonQuery();}
 SqliteConnection Open(){var c=new SqliteConnection(connectionString);c.Open();return c;}
 public SyncJob Enqueue(SyncRequest request){if(string.IsNullOrWhiteSpace(request.Channel)||string.IsNullOrWhiteSpace(request.Operation)||string.IsNullOrWhiteSpace(request.EntityId)||string.IsNullOrWhiteSpace(request.Version))throw new InvalidOperationException("Sync işi için kanal, işlem, varlık ve sürüm zorunlu.");using var c=Open();using var find=c.CreateCommand();find.CommandText="SELECT Id,Channel,Operation,EntityId,Version,Status,FailureCount,LastError,UpdatedUtc FROM SyncJobs WHERE Channel=$channel AND Operation=$operation AND EntityId=$entity AND Version=$version";find.Parameters.AddWithValue("$channel",request.Channel);find.Parameters.AddWithValue("$operation",request.Operation);find.Parameters.AddWithValue("$entity",request.EntityId);find.Parameters.AddWithValue("$version",request.Version);using(var r=find.ExecuteReader())if(r.Read())return Read(r);var job=new SyncJob{Channel=request.Channel,Operation=request.Operation,EntityId=request.EntityId,Version=request.Version};using var cmd=c.CreateCommand();cmd.CommandText="INSERT INTO SyncJobs(Id,Channel,Operation,EntityId,Version,Status,FailureCount,LastError,UpdatedUtc) VALUES($id,$channel,$operation,$entity,$version,$status,0,'',$updated)";cmd.Parameters.AddWithValue("$id",job.Id);cmd.Parameters.AddWithValue("$channel",job.Channel);cmd.Parameters.AddWithValue("$operation",job.Operation);cmd.Parameters.AddWithValue("$entity",job.EntityId);cmd.Parameters.AddWithValue("$version",job.Version);cmd.Parameters.AddWithValue("$status",(int)job.Status);cmd.Parameters.AddWithValue("$updated",job.UpdatedUtc.ToString("O"));cmd.ExecuteNonQuery();return job;}
 static SyncJob Read(SqliteDataReader r)=>new(){Id=r.GetString(0),Channel=r.GetString(1),Operation=r.GetString(2),EntityId=r.GetString(3),Version=r.GetString(4),Status=(SyncStatus)r.GetInt32(5),FailureCount=r.GetInt32(6),LastError=r.GetString(7),UpdatedUtc=DateTime.Parse(r.GetString(8),null,System.Globalization.DateTimeStyles.RoundtripKind)};
 public SyncJob Get(string id){using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="SELECT Id,Channel,Operation,EntityId,Version,Status,FailureCount,LastError,UpdatedUtc FROM SyncJobs WHERE Id=$id";cmd.Parameters.AddWithValue("$id",id);using var r=cmd.ExecuteReader();if(!r.Read())throw new InvalidOperationException("Sync işi bulunamadı.");return Read(r);}
 public void Fail(string id,string error){using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="UPDATE SyncJobs SET Status=$status,FailureCount=FailureCount+1,LastError=$error,UpdatedUtc=$updated WHERE Id=$id";cmd.Parameters.AddWithValue("$status",(int)SyncStatus.Failed);cmd.Parameters.AddWithValue("$error",error.Trim());cmd.Parameters.AddWithValue("$updated",DateTime.UtcNow.ToString("O"));cmd.Parameters.AddWithValue("$id",id);if(cmd.ExecuteNonQuery()!=1)throw new InvalidOperationException("Sync işi bulunamadı.");}
 public void Retry(string id){var job=Get(id);if(job.Status!=SyncStatus.Failed)throw new InvalidOperationException("Yalnızca başarısız sync işleri tekrarlanabilir.");if(job.FailureCount>=3)throw new InvalidOperationException("Sync işi üç başarısız denemeden sonra durduruldu.");using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="UPDATE SyncJobs SET Status=$status,LastError='',UpdatedUtc=$updated WHERE Id=$id";cmd.Parameters.AddWithValue("$status",(int)SyncStatus.Pending);cmd.Parameters.AddWithValue("$updated",DateTime.UtcNow.ToString("O"));cmd.Parameters.AddWithValue("$id",id);cmd.ExecuteNonQuery();}
 public IReadOnlyList<SyncJob> List(){using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="SELECT Id,Channel,Operation,EntityId,Version,Status,FailureCount,LastError,UpdatedUtc FROM SyncJobs ORDER BY UpdatedUtc DESC";using var r=cmd.ExecuteReader();var result=new List<SyncJob>();while(r.Read())result.Add(Read(r));return result;}
}
