using Microsoft.Data.Sqlite;
using System.IO;

namespace TrMarketplaceHubDesktop.Catalog;
public enum TaxonomyKind { Category, Brand, Attribute }
public sealed class TaxonomyEntry { public string Id {get;set;}=Guid.NewGuid().ToString("N"); public TaxonomyKind Kind {get;set;} public string Name {get;set;}=""; public string Value {get;set;}=""; public bool Active {get;set;}=true; }
public sealed record TaxonomyMapping(TaxonomyKind Kind,string Marketplace,string ShopId,string ExternalKey,string LocalId);
public sealed class TaxonomyStore
{
 readonly string connectionString;
 public TaxonomyStore(string? directory=null){directory??=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"MonoBridgeDesktop");Directory.CreateDirectory(directory);connectionString=new SqliteConnectionStringBuilder{DataSource=Path.Combine(directory,"catalog.db")}.ToString();using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="CREATE TABLE IF NOT EXISTS TaxonomyEntries(Id TEXT PRIMARY KEY, Kind INTEGER NOT NULL, Name TEXT NOT NULL, Value TEXT NOT NULL, Active INTEGER NOT NULL);CREATE UNIQUE INDEX IF NOT EXISTS UX_TaxonomyEntries_KindNameValue ON TaxonomyEntries(Kind,Name,Value);CREATE TABLE IF NOT EXISTS TaxonomyMappings(Kind INTEGER NOT NULL, Marketplace TEXT NOT NULL DEFAULT 'local', ShopId TEXT NOT NULL DEFAULT 'default', ExternalKey TEXT NOT NULL, LocalId TEXT NOT NULL, PRIMARY KEY(Kind,Marketplace,ShopId,ExternalKey));";cmd.ExecuteNonQuery();}
 SqliteConnection Open(){var c=new SqliteConnection(connectionString);c.Open();return c;}
 static void Validate(TaxonomyEntry entry){entry.Name=entry.Name.Trim();entry.Value=entry.Value.Trim();if(entry.Name.Length==0||entry.Name.Length>200)throw new InvalidOperationException("Kategori, marka veya özellik adı 1-200 karakter olmalı.");if(entry.Value.Length>200)throw new InvalidOperationException("Özellik değeri en fazla 200 karakter olabilir.");}
 public TaxonomyEntry Save(TaxonomyEntry entry){Validate(entry);using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="SELECT Id FROM TaxonomyEntries WHERE Kind=$kind AND lower(Name)=lower($name) AND lower(Value)=lower($value) AND Id<>$id";cmd.Parameters.AddWithValue("$kind",(int)entry.Kind);cmd.Parameters.AddWithValue("$name",entry.Name);cmd.Parameters.AddWithValue("$value",entry.Value);cmd.Parameters.AddWithValue("$id",entry.Id);if(cmd.ExecuteScalar()!=null)throw new InvalidOperationException("Aynı türde aynı ad/değer zaten var.");cmd.Parameters.Clear();cmd.CommandText="INSERT INTO TaxonomyEntries(Id,Kind,Name,Value,Active) VALUES($id,$kind,$name,$value,$active) ON CONFLICT(Id) DO UPDATE SET Kind=excluded.Kind,Name=excluded.Name,Value=excluded.Value,Active=excluded.Active";cmd.Parameters.AddWithValue("$id",entry.Id);cmd.Parameters.AddWithValue("$kind",(int)entry.Kind);cmd.Parameters.AddWithValue("$name",entry.Name);cmd.Parameters.AddWithValue("$value",entry.Value);cmd.Parameters.AddWithValue("$active",entry.Active?1:0);cmd.ExecuteNonQuery();return entry;}
 public IReadOnlyList<TaxonomyEntry> List(TaxonomyKind kind){using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="SELECT Id,Kind,Name,Value,Active FROM TaxonomyEntries WHERE Kind=$kind ORDER BY Name,Value";cmd.Parameters.AddWithValue("$kind",(int)kind);using var r=cmd.ExecuteReader();var result=new List<TaxonomyEntry>();while(r.Read())result.Add(new(){Id=r.GetString(0),Kind=(TaxonomyKind)r.GetInt32(1),Name=r.GetString(2),Value=r.GetString(3),Active=r.GetInt32(4)!=0});return result;}
 public void Map(TaxonomyKind kind,string externalKey,string localId,string marketplace="local",string shopId="default"){if(string.IsNullOrWhiteSpace(externalKey)||string.IsNullOrWhiteSpace(localId)||string.IsNullOrWhiteSpace(marketplace)||string.IsNullOrWhiteSpace(shopId))throw new InvalidOperationException("Pazaryeri, mağaza, harici anahtar ve yerel eşleme zorunlu.");using var c=Open();using var tx=c.BeginTransaction();using var exists=c.CreateCommand();exists.Transaction=tx;exists.CommandText="SELECT Active FROM TaxonomyEntries WHERE Id=$id AND Kind=$kind";exists.Parameters.AddWithValue("$id",localId);exists.Parameters.AddWithValue("$kind",(int)kind);var active=exists.ExecuteScalar();if(active is null)throw new InvalidOperationException("Eşlenecek yerel kayıt bulunamadı.");if(Convert.ToInt32(active)==0)throw new InvalidOperationException("Pasif yerel kayıt eşlenemez.");using var cmd=c.CreateCommand();cmd.Transaction=tx;cmd.CommandText="INSERT INTO TaxonomyMappings(Kind,Marketplace,ShopId,ExternalKey,LocalId) VALUES($kind,$market,$shop,$key,$id) ON CONFLICT(Kind,Marketplace,ShopId,ExternalKey) DO UPDATE SET LocalId=excluded.LocalId";cmd.Parameters.AddWithValue("$kind",(int)kind);cmd.Parameters.AddWithValue("$market",marketplace.Trim().ToLowerInvariant());cmd.Parameters.AddWithValue("$shop",shopId.Trim());cmd.Parameters.AddWithValue("$key",externalKey.Trim());cmd.Parameters.AddWithValue("$id",localId);cmd.ExecuteNonQuery();tx.Commit();}
 public string? Resolve(TaxonomyKind kind,string externalKey,string marketplace="local",string shopId="default"){using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="SELECT LocalId FROM TaxonomyMappings WHERE Kind=$kind AND Marketplace=$market AND ShopId=$shop AND ExternalKey=$key";cmd.Parameters.AddWithValue("$kind",(int)kind);cmd.Parameters.AddWithValue("$market",marketplace.Trim().ToLowerInvariant());cmd.Parameters.AddWithValue("$shop",shopId.Trim());cmd.Parameters.AddWithValue("$key",externalKey.Trim());return cmd.ExecuteScalar() as string;}
 public IReadOnlyList<TaxonomyMapping> Mappings(TaxonomyKind kind){using var c=Open();using var cmd=c.CreateCommand();cmd.CommandText="SELECT Marketplace,ShopId,ExternalKey,LocalId FROM TaxonomyMappings WHERE Kind=$kind ORDER BY Marketplace,ShopId,ExternalKey";cmd.Parameters.AddWithValue("$kind",(int)kind);using var r=cmd.ExecuteReader();var result=new List<TaxonomyMapping>();while(r.Read())result.Add(new(kind,r.GetString(0),r.GetString(1),r.GetString(2),r.GetString(3)));return result;}
}
